### ISSUE TITLE
About full integer quantization to the edge tpu one

### ISSUE THREAD

**Issue by willfu** [PINTO0309/PINTO_model_zoo#1]
Thanks for the great work. I have a question about how to convert the model to edge tpu one. 
I can see the steps in 03posenet, but how to convert the model to edge tpu one? Thanks.

**Comment by PINTO0309** [comment]
The following is an example of the command. The .tflite file to be converted must specify the Full Integer Quantization model.
```bash
$ edgetpu_compiler -s model-mobilenet_v1_101_257_full_integer_quant.tflite
```

For details on how to install the EdgeTPU compiler, see the URL below.
**https://coral.ai/docs/edgetpu/compiler/**

**Comment by willfu** [comment]
thanks
