### ISSUE TITLE
Blazeface back camera model (quantized)

### ISSUE THREAD

**Issue by metanav** [PINTO0309/PINTO_model_zoo#10]
I could not find any quantized version for face_detection_back.tflite model.

**Comment by PINTO0309** [comment]
The model before quantization is not available in either the mediapipe or tfjs repositories, so it cannot be generated.

**Comment by metanav** [comment]
You can find FP32 model here: https://github.com/google/mediapipe/blob/master/mediapipe/models/face_detection_back.tflite

**Comment by PINTO0309** [comment]
This is a model quantized to Float16. The Back model is a new model that was added 21 days ago. The Float32 model was not committed from the beginning.
![Screenshot 2020-06-11 23:42:07](https://user-images.githubusercontent.com/33194443/84400598-33c8c680-ac3d-11ea-8b17-ff0f67735ade.png)

>How did you generate for "front" one?

I took the Float32 model from a commit older than 22 days ago and quantized it.

**Comment by metanav** [comment]
I see! I have asked them to share the FP32 or saved model. It seems they are not willing to do so.

**Comment by metanav** [comment]
Can the edge tpu quantized model be run without the coral edge accelerator? i mean only on Raspberry Pi.

**Comment by PINTO0309** [comment]
It does not work because it contains a dedicated EdgeTPU custom OP.
![Screenshot 2020-06-12 01:29:14](https://user-images.githubusercontent.com/33194443/84413868-2a932600-ac4c-11ea-977d-ee666659f12e.png)

**Comment by metanav** [comment]
That's what I thought.

**Comment by PINTO0309** [comment]
The situation is closed as there is no room for improvement. Issue another issue if necessary.
