### ISSUE TITLE
BodyPix model to work with WASM?

### ISSUE THREAD

**Issue by charliesantos** [PINTO0309/PINTO_model_zoo#101]
Hi @PINTO0309 , I like your work. Thank you for putting all these together! I submitted an issue [here](https://github.com/Volcomix/virtual-background/issues/11) which is related to google meet tflite model used in WASM. I also noticed your work on ML Kit Selfie model (thank you again). Is it possible to get your [bodypix tflite models](https://github.com/PINTO0309/PINTO_model_zoo/tree/main/035_BodyPix) to work with the WASM pipeline as mentioned in this [issue](https://github.com/Volcomix/virtual-background/issues/11)? Thank you so much in advance!

**Comment by PINTO0309** [comment]
Please see here.
https://github.com/w-okada/image-analyze-workers
