### ISSUE TITLE
Selfie_Segmentation STREAM_MODE

### ISSUE THREAD

**Issue by benbro** [PINTO0309/PINTO_model_zoo#104]
Does the converted selfie segmentation model use STREAM_MODE or SINGLE_IMAGE_MODE?
STREAM_MODE is optimized for video and smooth the segmentation result.
https://developers.google.com/ml-kit/vision/selfie-segmentation/android#detector_mode

**Comment by PINTO0309** [comment]
I just converted the model I downloaded from the link in this issue. I was not aware of the fact that different modes have different models. I will convert the tflite model if you can provide it.
https://github.com/Volcomix/virtual-background/issues/2

**Comment by benbro** [comment]
I don't know where to get the model. I'll close this issue. Thanks

**Comment by carter54** [comment]
@benbro these two different modes are used for the postprocessing, and not related to the model itself
