### ISSUE TITLE
Iris landmark TensorRT

### ISSUE THREAD

**Issue by romain87400** [PINTO0309/PINTO_model_zoo#105]
Hello @PINTO0309 , I am currently using your tensorRT model from Iris landmark.
I work on Jetson Xavier NX with tensorflow 1.15.2. 
My concern is to obtain the tables of the values ​​of the coordinates of the pupils.
Can you help me to decode the tensors and get the coordinates of the points on an image? With a simple example.
Because in your example you just apply models on random value without postpressing.
I have an example with the tflite model, but they use "tf.lite.Interpreter" type objects to decode the tensors.

Thanks for your reply, best regards.
Romain

**Comment by PINTO0309** [comment]
Sorry, I'm not familiar with TensorRT.
