### ISSUE TITLE
Question about demo ?

### ISSUE THREAD

**Issue by hoangkhoiLE** [PINTO0309/PINTO_model_zoo#106]
#### Version of OpenVINO e.g. 2021.2.185, etc

Hello; Thank for your excellent work ! Now I want to used your converted model Openvino but i can't not see a template to use it. Please guide me. Thank you a lot !

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/PINTO_model_zoo#pinto_model_zoo

> I have been working on quantization of various models as a hobby, but I have skipped the work of making sample code to check the operation because it takes a lot of time. I welcome a pull request from volunteers to provide sample code.
