### ISSUE TITLE
MoveNet int8 model doesn't detect pose

### ISSUE THREAD

**Issue by iwatake2222** [PINTO0309/PINTO_model_zoo#107]
#### 1. OS you are using e.g. Ubuntu 20.04, WIndows10, etc
- Raspberry Pi 4 (Raspberry Pi OS (32-bit), 2021-05-07)
- Windows 10 + Visual Studio 2019

#### 2. OS Architecture e.g. x86_64, armv7l, aarch64, etc
- armv7l
- x86_64

#### 3. Version of OpenVINO e.g. 2021.2.185, etc
- None

#### 4. Version of TensorFlow e.g. v2.4.1, tf-nightly==2.5.0.dev20210128, etc
- TensorFlow Lite v2.4.0 (582c8d236cb079023657287c318ff26adb239002)

#### 5. Version of TensorRT e.g. TensorRT6.0 GA, etc
- None

#### 6. Version of TFJS e.g. 1.5.0, etc
- None

#### 7. Version of coremltools e.g. 4.0, etc
- None

#### 8. Version of ONNX e.g. v1.8.0, etc
- None

#### 9. URL of the repository from which the transformed model was taken
- https://github.com/PINTO0309/PINTO_model_zoo/tree/main/115_MoveNet

#### 10. URL or source code for simple inference testing code
- https://github.com/iwatake2222/play_with_tflite/tree/master/pj_tflite_pose_movenet

#### 11. Issue Details
- Issue
	- MoveNet int8 model doesn't detect pose
	- The output scores are very low, so no points are detected
- What I tried
	- When I use the same code, same preprocess and same input image,  WQ model (model_weight_quant.tflite) can detect pose
	- I tried using some normalization, [-1, 1], [0, 1], [0, 255]. However, always got low scores

- Outputs of WQ model (Correct result)
```
x, y, score
0.362019, 0.284556, 0.552823
0.386783, 0.264618, 0.526143
0.352213, 0.264542, 0.543260
0.425948, 0.285047, 0.479948
0.327979, 0.271992, 0.550301
0.460493, 0.382395, 0.757958
0.261695, 0.359047, 0.474937
0.455809, 0.476711, 0.463639
0.222942, 0.479214, 0.619574
0.492206, 0.590007, 0.416923
0.161311, 0.570904, 0.556857
0.402901, 0.557082, 0.610471
0.281061, 0.544552, 0.461256
0.357106, 0.616616, 0.364850
0.296230, 0.592794, 0.357634
0.356735, 0.820699, 0.630975
0.228626, 0.759591, 0.618845
```
- Outputs of INT8 model (scores are low)
```
x, y, score
0.912508, 0.061345, 0.122690
0.897172, 0.061345, 0.122690
0.897172, 0.061345, 0.092018
0.874168, 0.728473, 0.042175
0.663294, 0.023004, 0.072847
0.747644, 0.019170, 0.157197
0.019170, 0.517599, 0.245380
0.517599, 0.521433, 0.042175
0.498429, 0.498429, 0.042175
0.601949, 0.540604, 0.030673
0.517599, 0.559774, 0.030673
0.521433, 0.540604, 0.072847
0.540604, 0.540604, 0.042175
0.601949, 0.644124, 0.042175
0.475425, 0.624953, 0.042175
0.578944, 0.601949, 0.019170
0.475425, 0.644124, 0.042175
```

- Possible cause
	- I'm not sure it's the reason but dividing by 255 may not be needed.
		- https://github.com/PINTO0309/PINTO_model_zoo/blob/main/115_MoveNet/convert_script.txt#L40
		- It's because, this model expects input of RGB with values in [0, 255]

**Comment by PINTO0309** [comment]
I understand everything, I'm a little worried about getting the correct accuracy without dividing by 255, but I will convert again.

**Comment by PINTO0309** [comment]
Fixed it. ae76db45dc1234023b11fe2b0ef699503c85d4f4
I have replaced the files in Google Drive, so please try downloading them again.

**Comment by iwatake2222** [comment]
@PINTO0309 
Thank you. Now, it's working!
The accuracy dropped as you were worried, but it somehow works.

I attached two images. the first one is the previous model, and the second one is the new model. The threshold of score is 0.1

Thanks a lot :)

![before](https://user-images.githubusercontent.com/11009876/121936013-1e243a80-cd84-11eb-81be-ff5734839714.jpg)
![after](https://user-images.githubusercontent.com/11009876/121936025-211f2b00-cd84-11eb-9819-a73b3d7d298b.jpg)

**Comment by PINTO0309** [comment]
Can you try this one with Float32?
https://github.com/PINTO0309/TensorflowLite-bin

**Comment by iwatake2222** [comment]
Yes, I'm working in C++, so I cannot use those wheels in my project, sorry.
Just FYI, it's the result of Float32 model. It looks almost the same as the result of WQ model.
![fp32](https://user-images.githubusercontent.com/11009876/121937319-87587d80-cd85-11eb-8b12-c52fd8b6922d.jpg)

**Comment by PINTO0309** [comment]
Thanks!

**Comment by APeiZou** [comment]
@iwatake2222 ,Hi, what is the WQ model?

**Comment by iwatake2222** [comment]
@APeiZou 
Model with Weight Quantization

**Comment by APeiZou** [comment]
@PINTO0309 Hi,Why is your int8 quantitative model not as effective as the official int8 quantitative model?  How did you choose the quantitative calibration images？

**Comment by PINTO0309** [comment]
This is because it was released much earlier than the official release.
