### ISSUE TITLE
Run TFLITE Faster Grad-CAM on Google Edge-TPU

### ISSUE THREAD

**Issue by TannerGilbert** [PINTO0309/PINTO_model_zoo#108]
I'm interested in running a grad-cam model on a Google Edge-TPU device like the Google Coral USB Accelerator. Do you have a idea on how this can be implemented?

Any help is greatly appreciated.

**Comment by PINTO0309** [comment]
Please take a look here.
https://github.com/shinmura0/Faster-Grad-CAM
