### ISSUE TITLE
repository structure

### ISSUE THREAD

**Issue by vpenades** [PINTO0309/PINTO_model_zoo#11]
Hi again!

I've kept playing with all the amazing models you're collecting in the zoo repository, but lately, as the repository keeps growing, it's becoming more difficult to find models.

I would like to suggest you to reorganize the repository so it's arranged as themes

So far I would suggest these root repositories:
- Artistic
- Face Detection
- Hand Detection
- Body Pose Detection
- Object Detection
- Depth from monocular images
- Misc

That way it would be easier to find and compare different models...

**Comment by PINTO0309** [comment]
I've categorized the models to make them easier to find.
