### ISSUE TITLE
How did you have manage to made  the weights file to edgetpu.tflite?

### ISSUE THREAD

**Issue by maazullah96** [PINTO0309/PINTO_model_zoo#113]
I have converted my custom yolov4 weights file to TensorFlow pb format as required by the 031_yolov4 repository. but when I run the 04_full_integer_quantization.py file, I get the error "operators not supported by TensorFlow runtime". Can you guide me on how I can convert my file to edgetpu quantized tflite format?

My Error logs 
[error_logs.txt](https://github.com/PINTO0309/PINTO_model_zoo/files/6830732/error_logs.txt)
Thanks

**Comment by PINTO0309** [comment]
It was successful a year ago, but the current version of TensorFlow seems to terminate abnormally on core dump. There is no other way to do it. It seems better to use other YoloV4 repositories.

```
docker run -it --rm \
-v `pwd`:/home/user/workdir \
pinto0309/openvino2tensorflow:latest

python3 -m tf2onnx.convert \
--saved-model saved_model \
--output model.onnx \
--opset 11 \
--inputs input_1:0[1,416,416,3] \
--inputs-as-nchw input_1:0

python3 -m onnxsim model.onnx model_opt.onnx

$INTEL_OPENVINO_DIR/deployment_tools/model_optimizer/mo.py \
--input_model model_opt.onnx \
--data_type FP32 \
--output_dir openvino/FP32

openvino2tensorflow \
--model_path openvino/FP32/model_opt.xml \
--output_edgetpu
```

**Comment by maazullah96** [comment]
@PINTO0309 
thanks for your reply. 
Do you think it will be possible if I try to use the previous TensorFlow version? Because maybe previous ones have the support about it.

**Comment by maazullah96** [comment]
@PINTO0309 why yolov5 is easily convertible to tflite than yolov4.Do you think yolov5 can be easily convertible to edgetpu tflite file.My main aim is to run the edgetpu file .The only edgetpu tflite which works fine for me is provided by you .
Do you think there is some way to convert yolov4 to edgetpu tflite.

**Comment by PINTO0309** [comment]
You may want to try the following.
https://wiki.loliot.net/docs/lang/python/libraries/yolov4/python-yolov4-edge-tpu/

**Comment by maazullah96** [comment]
I tried it as well and it works fine for yolov4-tiny but not works for the yolov4.
The error logs are in this file:
[fulleror.txt](https://github.com/PINTO0309/PINTO_model_zoo/files/6834363/fulleror.txt)

**Comment by PINTO0309** [comment]
This is a TensorFlow problem. I can't do anything about it.
```
Converting unsupported operation: StatelessIf
Check failed: attr.value_case() == AttrValue::kType (1 vs. 6)
```

**Comment by PINTO0309** [comment]
Closed due to lack of progress.
