### ISSUE TITLE
Yolox inference

### ISSUE THREAD

**Issue by tucachmo2202** [PINTO0309/PINTO_model_zoo#114]
Hi, Thanks for your great works!
I have downloaded tensorflow lite Yolox [model](https://github.com/PINTO0309/PINTO_model_zoo/tree/main/132_YOLOX) converted by you. I also wrote code inference for tensorflow lite model follow [this file](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/demo/ONNXRuntime/onnx_inference.py), just change load model, change input shape with tensorflow lite format. It run but return none object...
Could help me fix this or do you plan to complete inference code for yolox?
Thank you very much!

**Comment by DonkeySmall** [comment]
Can you provide converted .tflite file?

**Comment by tucachmo2202** [comment]
@DonkeySmall You can go to go to [this link](https://github.com/PINTO0309/PINTO_model_zoo/tree/main/132_YOLOX) then `sh download_nano.sh` to download model. I also up the float 32 [model](https://drive.google.com/file/d/1XIk_TNnYxxcdtvSQdBLtnS4I_WYA9rUM/view?usp=sharing) to google drive.

**Comment by DonkeySmall** [comment]
The original output is 1x8400x85

![image_000000](https://user-images.githubusercontent.com/66531939/127462911-0972cab0-7c8b-4a13-a255-f181aa2c407e.jpg)

but your tflite model output is 1x2100x85

![image_000001](https://user-images.githubusercontent.com/66531939/127463127-eaf94c65-eb2e-4142-858e-a69a34b62fce.jpg)
![image_000002](https://user-images.githubusercontent.com/66531939/127463144-d293f3b5-c23c-4a28-be57-00bcbf0f5381.jpg)
maybe this is the problem?

**Comment by tucachmo2202** [comment]
@DonkeySmall, 
Origin model using input 416x416 so its output is larger than tflite with 320x320 input. However, I think that is not a problem. I guess something difference in preprocess I have to change not only reshape input image.

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/openvino2tensorflow/issues/48

**Comment by tucachmo2202** [comment]
@PINTO0309,
Hope you fix it soon!
Best regard!

**Comment by PINTO0309** [comment]
Fixes: https://github.com/PINTO0309/openvino2tensorflow/issues/48

https://twitter.com/Nextremer_nb_o/status/1421461443501649920?s=20

**Comment by tucachmo2202** [comment]
Hi @PINTO0309,
Glad to hear you fix this bug. However, when I convert model from [yolox_nano_416x416.onnx](https://megvii-my.sharepoint.cn/:u:/g/personal/gezheng_megvii_com/EfAGwvevU-lNhW5OqFAyHbwBJdI_7EaKu5yU04fgF5BU7w?e=gvq4hf) with [your script](https://github.com/PINTO0309/PINTO_model_zoo/blob/main/132_YOLOX/convert_script.txt), I met an error

 `ValueError: Dimension 1 in both shapes must be equal, but are 676 and 169. Shapes are [1,676] and [1,169]. for '{{node tf.concat_17/concat}} = ConcatV2[N=3, T=DT_FLOAT, Tidx=DT_INT32](Placeholder, Placeholder_1, Placeholder_2, tf.concat_17/concat/axis)' with input shapes: [1,2704,85], [1,676,85], [1,169,85], [] and with computed input tensors: input[3] = <2>.`

I installed openvino with docker. Could you please help me? Thank you very much!

**Comment by PINTO0309** [comment]
```
$ rm yolox_nano_320x320_tf.xml
$ cp yolox_nano_320x320_tf.xml yolox_nano_320x320.xml
```
Re-Run.

**Comment by tucachmo2202** [comment]
I don't really understand you. I can't find any file `yolox_nano_320x320_tf.xml` or 'yolox_nano_416x416_tf.xml' in my case. My all script is:

`xhost +local: && \
docker run -it --rm \
-v `pwd`:/home/user/workdir \
-v /tmp/.X11-unix/:/tmp/.X11-unix:rw \
--device /dev/video0:/dev/video0:mwr \
--net=host \
-e XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR \
-e DISPLAY=$DISPLAY \
--privileged \
pinto0309/openvino2tensorflow:latest

MODEL=yolox_nano
H=416
W=416
$INTEL_OPENVINO_DIR/deployment_tools/model_optimizer/mo.py \
--input_model ${MODEL}_${H}x${W}.onnx \
--data_type FP32 \
--output_dir openvino/${MODEL}/${H}x${W}/FP32
$INTEL_OPENVINO_DIR/deployment_tools/model_optimizer/mo.py \
--input_model ${MODEL}_${H}x${W}.onnx \
--data_type FP16 \
--output_dir openvino/${MODEL}/${H}x${W}/FP16
mkdir -p openvino/${MODEL}/${H}x${W}/myriad
${INTEL_OPENVINO_DIR}/deployment_tools/inference_engine/lib/intel64/myriad_compile \
-m openvino/${MODEL}/${H}x${W}/FP16/${MODEL}_${H}x${W}.xml \
-ip U8 \
-VPU_NUMBER_OF_SHAVES 4 \
-VPU_NUMBER_OF_CMX_SLICES 4 \
-o openvino/${MODEL}/${H}x${W}/myriad/${MODEL}_${H}x${W}.blob

openvino2tensorflow \
--model_path openvino/${MODEL}/${H}x${W}/FP32/${MODEL}_${H}x${W}.xml \
--output_saved_model \
--output_pb \
--output_no_quant_float32_tflite \
--output_weight_quant_tflite \
--output_float16_quant_tflite \
--output_integer_quant_tflite \
--string_formulas_for_normalization 'data / 255' \
--output_integer_quant_type 'uint8' \
--output_tfjs \
--output_coreml \
--weight_replacement_config weight_replacement_config_${MODEL}.json
mv saved_model saved_model_${MODEL}_${H}x${W}
`

Could you help me to fix my script? 
Thank you!

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/PINTO_model_zoo/issues/126
