### ISSUE TITLE
[EdgeTPU] RuntimeError: Found too many dimensions in the input array of operation 'reshape'.

### ISSUE THREAD

**Issue by sinclairnick** [PINTO0309/PINTO_model_zoo#12]
I have experimented with a few models in the repo and run into this error several times. Namely, YOLOv3-lite and the mobilenet-MNSFPN compiled using the edge-tpu compiler result in this error when run using the DetectionEngine. Is this some error on my part, or have you also found the same errors?

P.S. the compilation works successfully

**Comment by Namburger** [comment]
@sinclairnick The detection engine expects 4 outputs tensors, I don't know much about these models but the outputs may be mismatched. You can try using the tflite interpreter to check the model outputs or use `netron` tool to understand the model

**Comment by sinclairnick** [comment]
The detection engine throws a very specific error when this is the case, along the lines of “Expected 4 output tensors, but got {}”. I came across this error when using TFLite also.

Thanks Nam

**Comment by PINTO0309** [comment]
same issue https://github.com/PINTO0309/PINTO_model_zoo/issues/7
