### ISSUE TITLE
Can you give an example of XNNPACK speeding up inference movenet-v4?

### ISSUE THREAD

**Issue by APeiZou** [PINTO0309/PINTO_model_zoo#122]
Hi，can you give an example of XNNPACK speeding up inference movenet-v4?

**Comment by APeiZou** [comment]
@PINTO0309

**Comment by PINTO0309** [comment]
All you have to do is install TensorFlow or TensorFlowLite with XNNPACK enabled and run the Float32 tflite model.
https://github.com/PINTO0309/Tensorflow-bin
https://github.com/PINTO0309/TensorflowLite-bin

**Comment by APeiZou** [comment]
@PINTO0309 Thanks, is there an Android demo of XNNPACK?

**Comment by APeiZou** [comment]
@PINTO0309 Thanks, is there an Android demo accelerated by XNNPACK for the movenet-v4 int8 model?

**Comment by PINTO0309** [comment]
I'm sorry. I don't know much about that.
