### ISSUE TITLE
Quantization Aware Training

### ISSUE THREAD

**Issue by GhaziXX** [PINTO0309/PINTO_model_zoo#129]
#### Issue Details
Hello @PINTO0309, this is more like a question rather than an issue. 
Can you please provide us with some details about how QAT is happening with transfer learning? 
I've been stuck for a while on trying to use QAT with transfer learning (more specifically using feature vectors and tf_hub.KerasLayer) but no luck. I am wondering what approach are you using.

**Comment by PINTO0309** [comment]
See this tutorial for more information.
https://www.tensorflow.org/model_optimization/guide/quantization/training
