### ISSUE TITLE
Need a PyTorch model for road segmentation on OAK-D camera

### ISSUE THREAD

**Issue by franva** [PINTO0309/PINTO_model_zoo#131]
#### 9. URL of the repository from which the transformed model was taken

https://github.com/PINTO0309/PINTO_model_zoo/tree/main/026_mobile-deeplabv3-plus

#### 11. Issue Details

I need a PyTorch Model which can do road segmentation on OAK-D camera.

The model can run on OAK-D camera, but it has too many unwanted classes.
In my case I only need road class for segmentation.

Could you please provide a tutorial on how to re-train a model to require smaller input size(e.g. 224*224) and 2 classes (e.g. road and the rest)?
Or point out where I could find such a tutorial?

Thanks

**Comment by PINTO0309** [comment]
Unfortunately, I can't do anything about Intel's model because they don't disclose their training code or data sets. Try posting an issue to open_model_zoo.

**Comment by franva** [comment]
@PINTO0309  thanks a lot for your timely reply.

I have updated my question to point to the open model zoo.

Hope it helps.

**Comment by PINTO0309** [comment]
The resolution could not be changed, but the conversion to Blob was successful, so I committed the model to be added.
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/136_road-segmentation-adas-0001
