### ISSUE TITLE
Is there any demo code or tutorial of how to use tft-trt converted models

### ISSUE THREAD

**Issue by isra60** [PINTO0309/PINTO_model_zoo#134]
Hi I'm interested in Movenet Multipose and I´ve found you have also converted to tft-trt.

I'm trying to achieve the better performance on a Jetson Xavier NX. Currently with play_with_tflite repo I get around 15 fps using tensorflow lite xnnpack delegate for cpu, with gpu delegate I get worse performance. I suppose the problem is the lack on OpenCL in Jetson Platforms. 
To complete the benchmark I also have tried with the tensorhub model using the given full tensorflow for Jetson Platforms and there I get around 20fps.

So my question is if I can use the tftrt models to achieve better perfomance than those 20 fps (Maybe I can use a proper GPU like a 1080 to benchmark too) and is there are any tutorial I can refer to?

Thanks in advance.

Also I have an open issue in https://github.com/iwatake2222/play_with_tflite/issues/21#issue-976947961 that maybe is interesting for you

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/PINTO_model_zoo/blob/main/014_tf-monodepth2/02_imagenet_pre-trained/01_float32/23_tensorrt_inf_test.py#L87

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/PINTO_model_zoo/blob/main/036_Objectron/01_float32/10_tensorrt_inf_test.py

**Comment by PINTO0309** [comment]
You will not get proper performance using the tftrt model I generated in your environment. Please regenerate the model on your GPU environment.

**Comment by isra60** [comment]
Thank you @PINTO0309  You are refering to this right?? https://github.com/PINTO0309/PINTO_model_zoo/blob/main/137_MoveNet_MultiPose/convert_script.txt

**Comment by isra60** [comment]
Hi again @PINTO0309, trying to use the docker to regenerate the models on a Jetson Xavier NX, I've found the following problem.
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --video --require=cuda>=9.0 --pid=10492 /var/lib/docker/overlay2/d853facc0baa76acd649e0fd4e601aa39f3d37b90554203966466bc2f384db0d/merged]
nvidia-container-cli: mount error: mount operation failed: /usr/src/tensorrt: no such file or directory: unknown.
```
Do you have any docker image compatible with Jetson Platform? Or do you suggest to use on the host directly?

Thanks

**Comment by PINTO0309** [comment]
>Do you have any docker image compatible with Jetson Platform? Or do you suggest to use on the host directly?

It is meaningless unless you compile it on an actual device that can communicate with the GPU.

Only the amd64 base image is provided.
https://ngc.nvidia.com/catalog/containers/nvidia:tensorrt/tags

This may be helpful.
https://github.com/NVIDIA-AI-IOT/tf_trt_models

Please post a separate issue if you wish to discuss a different subject. A flood of different information makes it difficult for other engineers to search for useful information. The last topic you posted is about how to set up the TF-TRT environment, so you might get more useful information if you ask your question in the TF-TRT repository.
