### ISSUE TITLE
Updates for 33_Hand_Detection_and_Tracking

### ISSUE THREAD

**Issue by vpenades** [PINTO0309/PINTO_model_zoo#14]
It seems google has improved the hand landmark model, the announcement is [here](https://twitter.com/googleai/status/1265319835283537921?s=21)  , so maybe you might want to revisit it and update the models.

Also, I've noticed there's also updates for BlazeFace, where it seems there's two models, one for front facing cameras (selfie camera) and another for back facing (main) cameras.

Models seem to have been updated 2 months ago [here](https://github.com/google/mediapipe/tree/master/mediapipe/models).

**Comment by PINTO0309** [comment]
I was aware of the day the models were released. Also, I was trying quantization immediately, but I gave up because it was a Float16 quantized model.

Unfortunately, this model doesn't have a significant performance boost unless you're using Android with a GPU.

**Comment by vpenades** [comment]
Ah, well, my impression on the announcement was that they improved in accuracy, not in performance, or at least that's what it seems they did, based in the video comparing the old and the new hand tracker.

Also, I am puzzled about splitting the face tracking to front and back, I have to investigate.... maybe they use different anchors for each one? if they did a training specific for front and back cameras, there must be some subtle detail that's worth the cost...

Anyway, I'm working on a project for which I have not decided yet whether to go to desktop or smartphone... currently I'm working on desktop, so it's better for me to consume .PB frozen models. It seems .tflite is optimized for mobile/IOT platforms... so .tflite models can be run on desktop, but they're almost unusable.

**Comment by PINTO0309** [comment]
I released it a few months ago so download it again and give it a try.
