### ISSUE TITLE
blazepose模型多人检测问题

### ISSUE THREAD

**Issue by j201111100523** [PINTO0309/PINTO_model_zoo#140]
请问一下blazepose文件夹下的densify_pose_detection是否是用于多人骨骼点检测的

**Comment by PINTO0309** [comment]
https://github.com/google/mediapipe/issues/1691#issuecomment-797159603
https://github.com/google/mediapipe/issues/2524
https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_detection

**Comment by PINTO0309** [comment]
- MultiPose (MoveNet)
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/137_MoveNet_MultiPose
