### ISSUE TITLE
Request - provide models for MST inpainting

### ISSUE THREAD

**Issue by ofirkris** [PINTO0309/PINTO_model_zoo#141]
Thanks for your amazing work.
Would love to see if https://github.com/ewrfcas/MST_inpainting can be ported to CoreML/Tflite using your automation

**Comment by PINTO0309** [comment]
Provide trained models and license files. Unlicensed models are not converted because of the risk involved.

**Comment by ofirkris** [comment]
Thanks!
Here it is - https://github.com/ewrfcas/MST_inpainting/blob/main/LICENSE

**Comment by PINTO0309** [comment]
>Model - https://drive.google.com/drive/folders/1td0SNBdSdzMdj4Ei_GnMmglFYOgwUcM0

Is this the checkpoint you want to specify for **`--PATH ./check_points/MST_P2C`** ?

**Comment by PINTO0309** [comment]
Commited.
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/163_MST_inpainting

**Comment by DanielZanchi** [comment]
Thank for the work. How do we use the MST_inpainting on mobile? Trying with coreML or TFLite.
I was trying even the HiFill inpainting (there a _model_float32.tflite_ file) but no indication on how to provide input image and mask.
@PINTO0309
