### ISSUE TITLE
YolactEdge Onnx Convertion 

### ISSUE THREAD

**Issue by telemetrieTP23** [PINTO0309/PINTO_model_zoo#142]
Very nice that you presented a new Yolact Edge Mobilnet2 Convertation...
One question about the onnx File in there, is it still from the eval.py & yolact.py Files you posted 9 Month ago ?
They are changes of the commit made on 24.12.2020 in the yolact_edge github repo.

When I check out this commit and use your eval.py & yolact.py  together with the YolactEdge | MobileNet-V2 Checkpoint, I dont came to the same model_float32.onnx like you when comparing it with Netron.

Thanks for Infos !

**Comment by PINTO0309** [comment]
Unfortunately, the input resolution is fixed at the time the OpenVINO IR model is generated. Therefore, it is possible to export an ONNX model with variable input resolution before converting to OpenVINO IR, or an ONNX with arbitrary input resolution of MobileNetV2's YolactEdge model from PyTorch, if we know the procedure.

However, hylrh2008 did not share the procedures and config files exported to ONNX for a long time. I had no choice but to reverse-convert the OpenVINO IR model, which was the only one he provided to me. I can generate models of any resolution if I can figure out how to export them to ONNX.

**Comment by telemetrieTP23** [comment]
So the huge difference between the 2 converted Models 
(one from your changed eval.py & yolact.py and the other one from hylrh2008 [where we not know what he had changed,  but may he removed the FPN_phase_1 through changing the flow_base set in the Config file, like MiaoRain stated in https://github.com/haotian-liu/yolact_edge/issues/7, and maybe hylrh2008 changed some other things] ) 
is that hylrh2008 model has completly different sizes of outputlayers then yours.

hylrh2008: 
locationBlob = inferRequest->GetBlob("828");     //4*19248
maskmapsBlob = inferRequest->GetBlob("Conv_265");//138*138*32
maskBlob = inferRequest->GetBlob("830");         //32*19248
Ptr confidenceBlob = inferRequest->GetBlob("832");   //81*19248

your conversation (as i stated in https://github.com/PINTO0309/PINTO_model_zoo/issues/85):
Outputs ONNX:
name: 595
type: float32[1,256,40,40]
name: 574
type: float32[1,256,20,20]
name: 553
type: float32[1,256,10,10]
name: 594
type: float32[1,256,40,40]
name: 595
type: float32[1,256,40,40]
name: 574
type: float32[1,256,20,20]
name: 553
type: float32[1,256,10,10]
name: 601
type: float32[1,256,40,40]
name: 599
type: float32[1,256,20,20]
name: 597
type: float32[1,256,10,10]
name: 602
type: float32[1,256,5,5]
name: 603
type: float32[1,256,3,3]

So its not possible to use yolact.cpp with your model because of different output layer sizes.
But is this only a matter of postprocessing, because the postprocessing in hylhr2008 is also still not in his onnx, instead its done in yolact.cpp.
The big question still is how we get a onnx conversation with outputlayers like hylhr2008 or we make the postprocessing in c++ with the outputlayers sizes from your conversation. 
Or how convert your outputlayer sizes to the one from hylhr2008...

Maybe MiaoRain,hylhr2008 or someone else can help ? [but i dont find a email adress or other conntact from them]

Greetings !

**Comment by PINTO0309** [comment]
There is no progress, so I'm closing it.

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/085_Yolact_Edge/32_Multi-class_NonMaximumSuppression_compliant_version
![image](https://user-images.githubusercontent.com/33194443/173258044-f2dc6908-b02b-4f1f-a417-372fa21237b6.png)

**Comment by UPwangcheng** [comment]
> 
Hello, Thank you for your work, there is something wrong with my onnx when using your code to convert, It seems the structure of onnx is different, could you please help me? thank you

![structure](https://user-images.githubusercontent.com/41177451/188637154-d3b655ba-49a9-4ca3-8f84-8652a73d5ddf.png)
