### ISSUE TITLE
Efficientdet related doubt

### ISSUE THREAD

**Issue by aafaqin** [PINTO0309/PINTO_model_zoo#145]
I have trained my own efficientDet models using object detection API of tensorflow 2.
How do i convert my ED4 or ED6 models to tensorRT.

I could not find ant conversion scripts. (please correct me if  am wrong)

And what scripts to use for infer with the TensorRT model

**Comment by PINTO0309** [comment]
saved_model -> onnx -> onnx2trt

`onnx2trt xxxx.onnx -o xxxx.trt -b 1 -d 16 -v`
