### ISSUE TITLE
Support LSTR

### ISSUE THREAD

**Issue by yyuzhongpv** [PINTO0309/PINTO_model_zoo#147]
#### 10. URL or source code for simple inference testing code
```python
```
#### 11. Issue Details

Thanks for the wonderful work.
Do you have any plan to support LSTR model?  https://github.com/liuruijin17/LSTR

Regards

**Comment by PINTO0309** [comment]
This model is not very good.
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/167_LSTR
