### ISSUE TITLE
Please convert AGLLNet

### ISSUE THREAD

**Issue by MariasStory** [PINTO0309/PINTO_model_zoo#151]
Hi,
Your models conversion is the best.
Can you please convert AGLLNet:
https://github.com/yu-li/AGLLNet
I am mostly interested in tfjs.

**Comment by PINTO0309** [comment]
I converted and committed the model with much better performance.
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/176_StableLLVE
![5047](https://user-images.githubusercontent.com/33194443/141608134-b6dee8ff-5c52-402a-ba58-e07934e4e2c6.png)
![5047](https://user-images.githubusercontent.com/33194443/141608138-4ffb6551-3f20-4434-a15c-f55d7e7690ef.png)

**Comment by PINTO0309** [comment]
Commited.
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/200_AGLLNet

**Comment by MariasStory** [comment]
Cool. It seems that there is something going on in the field.
There is another interesting (more powerful) model
https://github.com/wyf0912/LLFlow
The light weight model is ~20M.

**Comment by PINTO0309** [comment]
The performance seems to be very high, but what is a little disappointing is that it is a model for non-commercial use only.
`CC BY-NC-SA 4.0 (Attribution-NonCommercial-ShareAlike 4.0 International)`
