### ISSUE TITLE
[YOLOX-Nano] Get error while converting ONNX model to TFLite model

### ISSUE THREAD

**Issue by yyuzhongpv** [PINTO0309/PINTO_model_zoo#153]
#### 1. OS you are using e.g. Ubuntu 20.04, WIndows10, etc
Ubuntu 18.04
#### 2. OS Architecture e.g. x86_64, armv7l, aarch64, etc
x86_64
#### 3. Version of OpenVINO e.g. 2021.2.185, etc
openvino_2021.4.582
#### 4. Version of TensorFlow e.g. v2.4.1, tf-nightly==2.5.0.dev20210128, etc
2.7.0
#### 5. Version of TensorRT e.g. TensorRT6.0 GA, etc
8.2.0
#### 8. Version of ONNX e.g. v1.8.0, etc
1.10.2
#### 9. URL of the repository from which the transformed model was taken

https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_nano.pth

#### 10. URL or source code for simple inference testing code
```python
Please check next step.
```
#### 11. Issue Details

Here are the steps I followed.

- sudo docker pull ghcr.io/pinto0309/openvino2tensorflow:latest
- download yolox-nano model from https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_nano.pth
- clone https://github.com/Megvii-BaseDetection/YOLOX.git and run pip3 install -v -e .
- python3 tools/export_onnx.py --output-name yolox_nano.onnx -n yolox-nano -c yolox_nano.pth -o 10
- in docker environment of ghcr.io/pinto0309/openvino2tensorflow:latest, run
/opt/intel/openvino_2021.4.582/deployment_tools/model_optimizer/mo.py --input_model yolox_nano.onnx --data_type FP32 --output_dir mine/FP32

openvino2tensorflow --model_path mine/FP32/yolox_nano.xml --output_saved_model --output_pb --output_no_quant_float32_tflite --output_weight_quant_tflite --output_float16_quant_tflite --output_integer_quant_tflite --string_formulas_for_normalization 'data / 255' --output_integer_quant_type 'uint8' --output_tfjs --output_coreml --weight_replacement_config weight_replacement_config_yolox_nano.json

The error pops at last step:

```
====================================================================================
layer_type: Const
layer_id: 664
tf_layers_dict: (3,)
====================================================================================
layer_type: Reshape
layer_id: 665
input_layer0: layer_id=663: KerasTensor(type_spec=TensorSpec(shape=(1, 13, 13, 85), dtype=tf.float32, name=None), name='tf.concat_16/concat:0', description="created by layer 'tf.concat_16'")
input_layer1: layer_id=664: Const(ndarray).shape (3,)
tf_layers_dict: KerasTensor(type_spec=TensorSpec(shape=(1, 169, 85), dtype=tf.float32, name=None), name='tf.reshape_2/Reshape:0', description="created by layer 'tf.reshape_2'")
====================================================================================
ERROR: Exception encountered when calling layer "tf.concat_17" (type TFOpLambda).

Dimension 1 in both shapes must be equal, but are 676 and 169. Shapes are [1,676] and [1,169]. for '{{node tf.concat_17/concat}} = ConcatV2[N=3, T=DT_FLOAT, Tidx=DT_INT32](Placeholder, Placeholder_1, Placeholder_2, tf.concat_17/concat/axis)' with input shapes: [1,2704,85], [1,676,85], [1,169,85], [] and with computed input tensors: input[3] = <2>.

Call arguments received:
  • values=['tf.Tensor(shape=(1, 2704, 85), dtype=float32)', 'tf.Tensor(shape=(1, 676, 85), dtype=float32)', 'tf.Tensor(shape=(1, 169, 85), dtype=float32)']
  • axis=2
  • name=concat
ERROR: model_path  : mine/FP32/yolox_nano.xml
ERROR: weights_path: mine/FP32/yolox_nano.bin
ERROR: layer_id    : 666
ERROR: input_layer0 layer_id=457: KerasTensor(type_spec=TensorSpec(shape=(1, 2704, 85), dtype=tf.float32, name=None), name='tf.reshape/Reshape:0', description="created by layer 'tf.reshape'")
ERROR: input_layer1 layer_id=561: KerasTensor(type_spec=TensorSpec(shape=(1, 676, 85), dtype=tf.float32, name=None), name='tf.reshape_1/Reshape:0', description="created by layer 'tf.reshape_1'")
ERROR: input_layer2 layer_id=665: KerasTensor(type_spec=TensorSpec(shape=(1, 169, 85), dtype=tf.float32, name=None), name='tf.reshape_2/Reshape:0', description="created by layer 'tf.reshape_2'")
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/usr/local/bin/openvino2tensorflow", line 1981, in convert
    inp = tf.concat(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/keras/layers/core/tf_op_layer.py", line 107, in handle
    return TFOpLambda(op)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
ValueError: Exception encountered when calling layer "tf.concat_17" (type TFOpLambda).

Dimension 1 in both shapes must be equal, but are 676 and 169. Shapes are [1,676] and [1,169]. for '{{node tf.concat_17/concat}} = ConcatV2[N=3, T=DT_FLOAT, Tidx=DT_INT32](Placeholder, Placeholder_1, Placeholder_2, tf.concat_17/concat/axis)' with input shapes: [1,2704,85], [1,676,85], [1,169,85], [] and with computed input tensors: input[3] = <2>.

Call arguments received:
  • values=['tf.Tensor(shape=(1, 2704, 85), dtype=float32)', 'tf.Tensor(shape=(1, 676, 85), dtype=float32)', 'tf.Tensor(shape=(1, 169, 85), dtype=float32)']
  • axis=2
  • name=concat

```

I looked through the issues, and looks like this isn't the issue related to yolox_nano_tf.xml, which is not found in my environment.

Would you please give any suggestions?

Thank you so much!

**Comment by yyuzhongpv** [comment]
I reviewed the other issue again, and change the xml like this. It looks good while converting the model. I will try inference and update it. Thanks anyway.

![image](https://user-images.githubusercontent.com/30056223/141506528-63124a28-203c-407f-86a2-edd2e5c47422.png)

**Comment by PINTO0309** [comment]
You can rewrite axis by giving JSON of external parameters.
https://github.com/PINTO0309/openvino2tensorflow#6-7-replace-weights-or-constant-values-in-const-op-and-add-transpose-or-reshape-or-cast-just-beforeafter-the-operation-specified-by-layer_id
![Screenshot 2021-11-13 02:14:32](https://user-images.githubusercontent.com/33194443/141507468-00848211-3f56-4bcc-8b23-a30577ebd007.png)

**Comment by yyuzhongpv** [comment]
Thanks for your kindly reply.

My orginal .xml looks like this:

![image](https://user-images.githubusercontent.com/30056223/141512972-0c94996c-d8de-410e-a573-7935de059200.png)

if I change .json like this:
![image](https://user-images.githubusercontent.com/30056223/141513098-f6b5ef4f-6dfb-44ff-9fd1-45a23a943be3.png)


It pop the error,

![image](https://user-images.githubusercontent.com/30056223/141513183-a74ddc5a-1e85-421e-87a3-77c7f5b58952.png)


If I change the .json like this,

![image](https://user-images.githubusercontent.com/30056223/141513255-1c8d3849-f9cc-420e-abfa-48737f8aa1fb.png)


It still pop the original error, and means the change_axis isn't working from .json file.

![image](https://user-images.githubusercontent.com/30056223/141513345-04ad5b5e-f8ed-48b7-aec9-39d78a6132ef.png)


Any suggestions?

Thanks and best regards,

**Comment by PINTO0309** [comment]
`"format_varsion": 2`

**Comment by yyuzhongpv** [comment]
Thanks you so much. The converting looks good now. I will try inference and update it.

Here is my final changes of the .json file for the reference.

![image](https://user-images.githubusercontent.com/30056223/141514663-1d0e0d3f-160f-4248-b4c8-b1685f000297.png)

**Comment by PINTO0309** [comment]
As stated in the README notes, it is recommended that you carefully check the connection status before and after Reshape and Interporate, and before and after Transpose.

**Comment by yyuzhongpv** [comment]
Thanks for the reminder.
Since I change nothing for the structure of the model yet, I will visualize the network with Netron, and try to test the inference results.

**Comment by PINTO0309** [comment]
Models with 5D, 3D, and 2D shape changes may break the structure even if the transformation is successful.

**Comment by yyuzhongpv** [comment]
The inference looks good. The only thing need to mention is that the official repo. of YOLOX changed the preprocessing recently, no need to normalize input now.
