### ISSUE TITLE
Can i convert NHWC to NCHW while conversion from .h5 model to .onnx?

### ISSUE THREAD

**Issue by rahulsharma11** [PINTO0309/PINTO_model_zoo#154]
#### 10. [URL or source code for simple inference testing code](https://github.com/PINTO0309/PINTO_model_zoo/blob/678d525ce1c5da5eb76194b8031c40ae62a772d3/046_yolov4-tiny/01_float32/06_keras_to_saved_model.py)
```python
model = VideoUtils.load_keras_model(MODEL_PATH)
onnx_model = keras2onnx.convert_keras(model, model.name, channel_first_inputs=['input_1'])
keras2onnx.save_model(onnx_model, 'tf2onnx.onnx')
```
#### 11. Issue Details
Hi,
my keras model supports NHWC input but i need NCHW onnx model.

Is there way i can add something in above code to generate onnx with NCHW support?

Thanks.

**Comment by PINTO0309** [comment]
Please read the README of keras2onnx.
https://github.com/onnx/keras-onnx
