### ISSUE TITLE
onnxsim model onnx Tinypose by Paddelpaddel

### ISSUE THREAD

**Issue by NoLoPhe** [PINTO0309/PINTO_model_zoo#156]
I have problem when onnxsim model onnx Tinypose by Paddelpaddel

Base: https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/keypoint/tiny_pose

I run:

> python tools/export_model.py -c configs/keypoint/tiny_pose/tinypose_128x96.yml --output_dir=outut_inference -o weights=https://bj.bcebos.com/v1/paddledet/models/keypoint/tinypose_128x96.pdparams use_gpu=false

> paddle2onnx --model_dir D:/Xu/Openpipaf_/openpifpaf/paddledetection_new/outut_inference/tinypose_128x96/ --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 11 --save_file tinypose_128x96.onnx

> python -m onnxsim D:/Xu/Openpipaf_/openpifpaf/paddledetection_new/tinypose_128x96.onnx D:/Xu/Openpipaf_/openpifpaf/paddledetection_new/tinypose_128x96_.onnx

I have problem with onnxsim

> The shape of input "image" has dynamic size "[-1, 3, 128, 96]", please determine the input size manually by "--dynamic-input-shape --input-shape xxx" o r "--input-shape xxx". Run "python3 -m onnxsim -h" for details

after that, I add '--dynamic-input-shape --input-shape 1,3,128,96'

> python -m onnxsim D:/Xu/Openpipaf_/openpifpaf/paddledetection_new/tinypose_128x96.onnx D:/Xu/Openpipaf_/openpifpaf/paddledetection_new/tinypose_128x96_.onnx --dynamic-input-shape --input-shape 1,3,128,96

Done onnxsim

Warring when I run:

> 2021-11-18 11:12:08.9506790 [W:onnxruntime:, graph.cc:1074 onnxruntime::Graph::Graph] Initializer conv2d_268.w_0 appears in graph inputs and will not be treated as constant value/weight. This may prevent some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.

Can you onnxsim help me with the Tinypose model? Thankyou very much!

**Comment by NoLoPhe** [comment]
Link model before onnxsim:
https://github.com/NoLoPhe/nolopeai/blob/master/tinypose_128x96.onnx

**Comment by PINTO0309** [comment]
Please do not submit issues that are not related to this repository. Why don't you guys try to look at the samples that are committed? Have you checked to see if there is actually a problem with the operation? Warning is not an error, did not work?

https://github.com/PINTO0309/PINTO_model_zoo/blob/main/174_PP-PicoDet/onnx_optimization_process.py

**Comment by NoLoPhe** [comment]
I apologize for my haste. Thanks for your feedback, I will try your solution.
