### ISSUE TITLE
Is There the C++ or python demo for the 178_vehicle-detection-0200?

### ISSUE THREAD

**Issue by zhongwenkun886** [PINTO0309/PINTO_model_zoo#158]
looking forward to it !

**Comment by PINTO0309** [comment]
You can modify the demo code here by yourself.
https://github.com/openvinotoolkit/open_model_zoo/tree/2021.4.2/demos

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/178_vehicle-detection-0200/demo

**Comment by zhongwenkun886** [comment]
Thanks very much !
