### ISSUE TITLE
Convert onnx to tensorflow fails

### ISSUE THREAD

**Issue by liamsun2019** [PINTO0309/PINTO_model_zoo#162]
### Issue Type

Support

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

ONNX

### Description

Sorry to bother. I intend to convert an onnx model to tensorflow and then to tflite. The story goes like this: The int8 quantization has very awful accuracy for lite-model_movenet_singlepose_thunder_3.tflite. So I plan to inverse quantize lite-model_movenet_singlepose_thunder_tflite_int8_4.tflite, a quantization-aware model, to float32 version, and then check the quantization accuracy for int8. You know, I want to do some fine tune based on the thunder model, not just simply integrate the model to applications. One possible flow is: tflite INT8 -> onnx float32 -> tensorflow -> tflite. I can now succeed in converting tflite to onnx but fail in onnx to tensorflow:

<1> convert tflite to onnx:
python3.6 -m tf2onnx.convert --opset 13--tflite lite-model_movenet_singlepose_thunder_tflite_int8_4.tflite --output model.onnx --inputs-as-nchw serving_default_input:0
The opset must be set to 13 since per-axis quantization for some layers must be supported. Above command can be executed normally on my side.

<2> convert onnx to tf
from onnx_tf.backend import prepare
import onnx
import os
import sys

TF_PATH = "./my_tf_model.pb"
ONNX_PATH = "./simplified.onnx"
onnx_model = onnx.load(ONNX_PATH)

tf_rep = prepare(onnx_model)
tf_rep.export_graph(TF_PATH)

where "simplified.onnx" is the model simplified by onnxsim using above model.onnx as the input.
The following error is then reported:
onnx_tf_prefix_truediv_1;truediv_1/y1_prequant' is not a valid scope name

I cannot google any similar information. Any suggestions? Thanks.

### Relevant Log Output

```shell
/usr/local/lib/python3.6/dist-packages/onnx_tf/backend_tf_module.py:98 __call__  *
        output_ops = self.backend._onnx_node_to_tensorflow_op(onnx_node,
    /usr/local/lib/python3.6/dist-packages/onnx_tf/backend.py:328 _onnx_node_to_tensorflow_op  *
        return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
    /usr/local/lib/python3.6/dist-packages/onnx_tf/handlers/handler.py:59 handle  *
        return ver_handle(node, **kwargs)
    /usr/local/lib/python3.6/dist-packages/onnx_tf/handlers/backend/mul.py:27 version_13  *
        return [cls.make_tensor_from_onnx_node(node, **kwargs)]
    /usr/local/lib/python3.6/dist-packages/onnx_tf/handlers/backend_handler.py:157 make_tensor_from_onnx_node  *
        return cls._run_tf_func(tf_func, inputs, attrs)
    /usr/local/lib/python3.6/dist-packages/onnx_tf/handlers/backend_handler.py:237 _run_tf_func  *
        return tf_func(**kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py:206 wrapper  **
        return target(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py:530 multiply
        return gen_math_ops.mul(x, y, name)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_math_ops.py:6250 mul
        "Mul", x=x, y=y, name=name)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:377 _apply_op_helper
        with g.as_default(), ops.name_scope(name) as scope:
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:6542 __enter__
        return self._name_scope.__enter__()
    /usr/lib/python3.6/contextlib.py:81 __enter__
        return next(self.gen)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:4275 name_scope
        raise ValueError("'%s' is not a valid scope name" % name)

    ValueError: 'onnx_tf_prefix_truediv_1;truediv_1/y1_prequant' is not a valid scope name
```

### URL or source code for simple inference testing code

from onnx_tf.backend import prepare
import onnx
import os
import sys

TF_PATH = "./my_tf_model.pb"
ONNX_PATH = "./simplified.onnx"
onnx_model = onnx.load(ONNX_PATH)

tf_rep = prepare(onnx_model)
tf_rep.export_graph(TF_PATH)

**Comment by PINTO0309** [comment]
Did you read the issue I just suggested? Have you not read it? Have you tried it? Only a partial response is attached. I think you should try to work on it yourself.
[lite-model_movenet_singlepose_thunder_tflite_int8_4_float32.onnx.zip](https://github.com/PINTO0309/PINTO_model_zoo/files/7617897/lite-model_movenet_singlepose_thunder_tflite_int8_4_float32.onnx.zip)
