### ISSUE TITLE
[ESPCN] ONNX model to TFLite error due to tf.Transpose

### ISSUE THREAD

**Issue by yyuzhongpv** [PINTO0309/PINTO_model_zoo#166]
### Issue Type

Support

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

PyTorch, ONNX, TensorFlowLite

### Description

I am working on making this ESPN model run in TFLite. https://github.com/Lornatang/ESPCN-PyTorch/releases/download/1.0/espcn_2x.pth
1. Export the .pth to ONNX file, as shown in espcn_relu_1080_2x.zip 
    [espcn_relu_1080_2x.zip](https://github.com/PINTO0309/PINTO_model_zoo/files/7724277/espcn_relu_1080_2x.zip)
2. I use the script to convert ONNX file into .pb. https://github.com/sithu31296/PyTorch-ONNX-TFLite/blob/master/conversion/onnx_to_tf.py
3. While converting the .pb to TFlite in the last step, I get this error due to the tf.Transpose. I saw your comments here https://github.com/sithu31296/PyTorch-ONNX-TFLite/issues/2, but still not sure how can I make it work.
    Would you please help to give any suggestions?

### Relevant Log Output

```shell
2021-12-16 02:36:34.604439: I tensorflow/cc/saved_model/loader.cc:283] SavedModel load for tags { serve }; Status: success: OK. Took 18414 microseconds.
2021-12-16 02:36:34.616770: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:210] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
loc(callsite(callsite("onnx_tf_prefix_Transpose_7@__inference___call___98" at "PartitionedCall@__inference_signature_wrapper_117") at "PartitionedCall")): error: 'tf.Transpose' op is neither a custom op nor a flex op
error: failed while converting: 'main': 
Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select 
TF Select ops: Transpose
Details:
	tf.Transpose(tensor<1x1x2x2x1080x1920xf32>, tensor<6xi32>) -> (tensor<1x1x1080x2x1920x2xf32>) : {device = ""}

Traceback (most recent call last):
  File "tf_to_tflite.py", line 8, in <module>
    tflite_model = converter.convert()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py", line 729, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py", line 715, in _convert_and_export_metrics
    result = convert_func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py", line 994, in convert
    result = _convert_saved_model(**converter_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert_phase.py", line 215, in wrapper
    raise converter_error from None  # Re-throws the exception.
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert_phase.py", line 208, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert.py", line 821, in convert_saved_model
    data = toco_convert_protos(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert.py", line 313, in toco_convert_protos
    raise converter_error
tensorflow.lite.python.convert_phase.ConverterError: <unknown>:0: error: loc(callsite(callsite("onnx_tf_prefix_Transpose_7@__inference___call___98" at "PartitionedCall@__inference_signature_wrapper_117") at "PartitionedCall")): 'tf.Transpose' op is neither a custom op nor a flex op
<unknown>:0: note: loc("PartitionedCall"): called from
<unknown>:0: note: loc(callsite(callsite("onnx_tf_prefix_Transpose_7@__inference___call___98" at "PartitionedCall@__inference_signature_wrapper_117") at "PartitionedCall")): Error code: ERROR_NEEDS_FLEX_OPS
<unknown>:0: error: failed while converting: 'main': 
Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select 
TF Select ops: Transpose
Details:
	tf.Transpose(tensor<1x1x2x2x1080x1920xf32>, tensor<6xi32>) -> (tensor<1x1x1080x2x1920x2xf32>) : {device = ""}
```

**Comment by PINTO0309** [comment]
![Screenshot from 2021-12-16 12-45-08](https://user-images.githubusercontent.com/33194443/146304715-dc489caf-7875-4688-9688-8bb7dd4bebc3.png)

**Comment by yyuzhongpv** [comment]
Thank you so much.
I tried these two steps, and I can generate the .tflite models. I will try to run it in TFLite. 

- /opt/intel/openvino_2021.4.582/deployment_tools/model_optimizer/mo.py --input_model espcn_relu_1080_2x.onnx --data_type FP32 --output_dir espcn

- openvino2tensorflow --model_path espcn/espcn_relu_1080_2x.xml --output_saved_model --output_pb --output_no_quant_float32_tflite --output_weight_quant_tflite --output_float16_quant_tflite

**Comment by PINTO0309** [comment]
![Screenshot from 2021-12-16 13-05-24](https://user-images.githubusercontent.com/33194443/146306395-80c73800-2aaa-4b4a-8ea6-17f93b9e34a2.png)
[model_float32.tflite.tar.gz](https://github.com/PINTO0309/PINTO_model_zoo/files/7724475/model_float32.tflite.tar.gz)

**Comment by PINTO0309** [comment]
"Prebuilt binary for TensorflowLite's standalone installer. For RaspberryPi. I provide a FlexDelegate, MediaPipe Custom OP, XNNPACK and XNNPACK Multi-Thread PythonAPI enabled binary."
https://github.com/PINTO0309/TensorflowLite-bin
