### ISSUE TITLE
What the difference between the four tflite models.

### ISSUE THREAD

**Issue by yahuuu** [PINTO0309/PINTO_model_zoo#167]
### Issue Type

Documentation Feature Request

### OS

Other

### OS architecture

aarch64

### Programming Language

C++

### Framework

TensorFlowLite

### Description

Hi, @PINTO0309
   I only see [online quantization](https://www.tensorflow.org/model_optimization/guide/quantization/training) and [post-quantization methods](https://www.tensorflow.org/lite/performance/post_training_quantization) on the tensorflow official website, and I am confused about [the four](https://github.com/PINTO0309/PINTO_model_zoo/tree/main/011_mobilenetv2/01_mobilenet_v2_1.0_224) (integer quant, full inter quant, weight quant, etpu) quantization models that you released. I did not find the difference between mobilenet_v2_224_dm10_full_integer_quant.tflite and mobilenet_v2_224_dm10_integer_quant.tflite.
 1. What is the difference between four models.  
 2. What equipment they are suitable for. 
 3. The Methods to quantify the weight quantized tflite? 
 Maybe you would like to add this feature in the documentation.
 Nice to see a huge and great model zoo!

**Comment by PINTO0309** [comment]
>1. What is the difference between four models.

This is as described in the official documentation.
Float32, Float16, INT8, EdgeTPU
https://www.tensorflow.org/lite/performance/post_training_quantization

>2. What equipment they are suitable for.

ARM64 or EdgeTPU

>3. The Methods to quantify the weight quantized tflite?

I don't implement it because it makes no sense.

**Comment by PINTO0309** [comment]
There has been no progress, so it is closed.
