### ISSUE TITLE
I got the latest facemesh files from Google ARCore, you can try to put them in your project

### ISSUE THREAD

**Issue by jiangzhongbo** [PINTO0309/PINTO_model_zoo#17]
[facemesh_from_google_arcore.zip](https://github.com/PINTO0309/PINTO_model_zoo/files/4952442/facemesh_from_google_arcore.zip)

**Comment by PINTO0309** [comment]
What is the license for this model?

**Comment by PINTO0309** [comment]
Closed due to lack of progress.
