### ISSUE TITLE
132-Yolox : yolox_tflite_demo.py returning none objects 

### ISSUE THREAD

**Issue by HimanshuMoliya** [PINTO0309/PINTO_model_zoo#170]
### Issue Type

Bug

### OS

Mac OS

### OS architecture

x86_64

### Programming Language

Python

### Framework

TensorFlowLite

### Description

132-Yolox : yolox_tflite_demo.py returning none objects as output... 
yolox_tflite_demo.py does not return any objects.

**Comment by HimanshuMoliya** [comment]
132-Yolox : yolox_tflite_demo.py returning none objects as output...
yolox_tflite_demo.py does not return any objects.

**Comment by PINTO0309** [comment]
![Screenshot 2022-01-05 16:42:57](https://user-images.githubusercontent.com/33194443/148179218-7f0f6cd4-553c-48b7-b00a-56ed485cbcba.png)

**Comment by HimanshuMoliya** [comment]
@PINTO0309 Thank you for sharing snap!
Which pre-trained model are you using?
![Screenshot 2022-01-07 at 1 43 17 AM](https://user-images.githubusercontent.com/33668957/148445314-dd9bb685-fbf2-4d0c-9f8d-cb868592e1ce.png)

**Comment by Christy-V** [comment]
Hi @PINTO0309 
 I tried running it on my PC it had dependency issue for `import tflite_runtime.interpreter as tflite` do tried it with `from tensorflow.lite.python.interpreter import Interpreter` the inference executed without error but the result i got was None type .

OS
Linux

OS architecture
x64

Programming Language
Python

Framework
TensorFlowLite

**Comment by iwatake2222** [comment]
Maybe you guys are using `download_nano.sh` . Try `download_nano_new.sh` to download models.
Using the models with `download_nano.sh` returns no object, but using the models with `download_nano_new.sh` can detect objects in my PC.

**Comment by PINTO0309** [comment]
commit: 6316164462e73792bd9b17324e992aa03c8f1f86

**Comment by PINTO0309** [comment]
I renamed **`download_new.sh`** to **`download.sh`**, merged the old ONNX file with the new resource, and recommitted.
