### ISSUE TITLE
How to solve Segmentation fault: 11 error while using tflite  

### ISSUE THREAD

**Issue by HimanshuMoliya** [PINTO0309/PINTO_model_zoo#173]

**Comment by HimanshuMoliya** [comment]
I convert onnx model to tflite...  .ONNX -> .pb -> .tflite
and use "from tflite_runtime.interpreter import Interpreter"
but getting error in "interpreter = Interpreter(model_path = args.model)"
Segmentation fault: 11

**Comment by PINTO0309** [comment]
Close it because it does not follow the issue template.
