### ISSUE TITLE
Request for weights of front tflite model in 07_new_blazeface_front_tflite2h5_weight_int_fullint_float16_quant.py 

### ISSUE THREAD

**Issue by mohamedgamal7** [PINTO0309/PINTO_model_zoo#174]
### Issue Type

Feature Request

### OS

Windows

### OS architecture

x86_64

### Programming Language

Python

### Framework

TensorFlow

### Description

Hello sir, first of all thank you for your  great work !

I'm trying to refine the blazeface detector so I need to build the model like you did in this file -> 07_new_blazeface_front_tflite2h5_weight_int_fullint_float16_quant.py 

but I need the "weights_front" folder to intialize the kernel and bias .

can you please provide it ? many thanks in advance.

**Comment by PINTO0309** [comment]
This model was converted more than a year and a half ago, so the procedure is not highly recommended.
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/030_BlazeFace

If you are willing to do the exhausting work, you can simply click on the floppy disk symbol in Netron to extract it.
![Screenshot 2022-01-07 08:57:49](https://user-images.githubusercontent.com/33194443/148469150-56849612-ee2b-4142-a726-38260f729bf9.png)

**Comment by mohamedgamal7** [comment]
Thanks a lot sir .. will they be extracted as .npy files ?

**Comment by PINTO0309** [comment]
Yes. A file in npy format with no extension.

**Comment by mohamedgamal7** [comment]
Thanks a lot sir you are the best ☺️
