### ISSUE TITLE
LSTR different input sizes

### ISSUE THREAD

**Issue by wsxwsx543** [PINTO0309/PINTO_model_zoo#176]
### Issue Type

Performance

### OS

Windows

### OS architecture

x86_64

### Programming Language

Python

### Framework

TensorFlowLite

### Description

Hi, I am working on LSTR model. I am curious how did you get the model with different input sizes? The original repo only provided the input size 360x640x3, but you provide other models with input size 180x320x3. I tried both of them and found 360x640x3's performance is acceptable on highway images while the ones with 180x320x3 have poor performance.

Thanks

**Comment by PINTO0309** [comment]
- export
https://github.com/PINTO0309/PINTO_model_zoo/issues/172

- optimization
  1. Remove Split
  2. Change indices Gather -1 to 1
  https://github.com/PINTO0309/PINTO_model_zoo/blob/main/167_LSTR/convert_script.txt
