### ISSUE TITLE
Lama Port

### ISSUE THREAD

**Issue by ozgurshn** [PINTO0309/PINTO_model_zoo#177]
### Issue Type

Feature Request

### OS

Other

### OS architecture

aarch64

### Programming Language

Other

### Framework

CoreML

### Description

Is this Lama model can be ported to Core ML? https://github.com/saic-mdal/lama
Model file is here: https://disk.yandex.ru/d/ouP6l8VJ0HpMZg
License is here: https://github.com/saic-mdal/lama/blob/main/LICENSE
Thanks.

**Comment by PINTO0309** [comment]
Unfortunately, it is impossible.
https://github.com/saic-mdal/lama/issues/84
```
RuntimeError: Exporting the operator fft_rfftn to ONNX opset version 13 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
```

**Comment by ozgurshn** [comment]
Thanks for the trial. Forgot to send reply, just realized when I stumble again :)
