### ISSUE TITLE
Nanodet TFLite model is giving wrong outputs

### ISSUE THREAD

**Issue by Christy-V** [PINTO0309/PINTO_model_zoo#179]
### Issue Type

Performance

### OS

Ubuntu

### OS architecture

aarch64

### Programming Language

Python

### Framework

TensorFlow, TensorFlowLite

### Description

The scores from the the model is such a  low that the NMSBox is returning a null value resulting in empty outputs

**Comment by Kazuhito00** [comment]
Please add the information.
* What hardware did aarch64 use? Raspberry pi? Jetson?
* What is the file name of the loaded model?
* What is the version of TensorFlow?
* What is the version of Numpy?
* What is the version of OpenCV?

**Comment by PINTO0309** [comment]
NanoDet-m seems to have a problem with it, so I removed it. Please convert it by yourself.
