### ISSUE TITLE
mobilenetv3-ssd quantization

### ISSUE THREAD

**Issue by happyjohn360** [PINTO0309/PINTO_model_zoo#18]
can you provide the float32 version of tflite file?
I found tflite_graph.pb and tflite_graph.pbtxt files, but I failed to convert it into tflite float32 or int8.
Or you can give me some advice or code how to do that?
Thanks !

**Comment by PINTO0309** [comment]
I can't clearly point out the problem because I don't have enough explanation of what script you ran. The only thing I can say is that I ran the scripts below in order.
**https://github.com/PINTO0309/PINTO_model_zoo/tree/master/02_mobilenetv3-ssd/02_mobilenetv3_large/01_coco/01_float**

**Comment by happyjohn360** [comment]
I'll try them.
Thanks.
