### ISSUE TITLE
demo_tflite.py poor detection

### ISSUE THREAD

**Issue by IAM-P-LP** [PINTO0309/PINTO_model_zoo#181]
Hi,
I ran the demo_tflite.py script by using the same model from your repo.The results are poor.Can you please look into the same?

indexes is nil.Hence bboxes returns null value.

This is how it looks in the terminal :

indexes ()
bboxes, scores, class_ids after post process [] [] []

**Comment by PINTO0309** [comment]
Close the issue template because it is not being used.

**Comment by IAM-P-LP** [comment]
> Close the issue template because it is not being used.

I am sorry.May I ask why this is closed without resolving the issue?

**Comment by PINTO0309** [comment]
There was a mistake in the English text. I'm sorry for the misunderstanding. Please issue the issue again.
