### ISSUE TITLE
Poor detections after running demo_tflite.py  script

### ISSUE THREAD

**Issue by IAM-P-LP** [PINTO0309/PINTO_model_zoo#182]
### Issue Type

Performance

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

TensorFlowLite

### Model name and Weights/Checkpoints URL

Model --> resources_nanodet_m/saved_model_nanodet_m_320x320/model_float16_quant.tflite'

(taken from this repo itself)

### Description

Hi,
I ran the demo_tflite.py script by using the same model from your repo.The results are poor.Can you please look into the same?

indexes is nil.Hence bboxes returns null value.

### Relevant Log Output

```shell
This is how it looks in the terminal :

indexes ()
bboxes, scores, class_ids after post process [] [] []
```

**Comment by Kazuhito00** [comment]
I don't know the cause at this point, but the NanoDet-m model doesn't seem to work properly with TensorFlow Lite.
<resources/saved_model_nanodet_320x320/model_float16_quant.tflite> seems to work correctly, so can I substitute this?

**Comment by IAM-P-LP** [comment]
> I don't know the cause at this point, but the NanoDet-m model doesn't seem to work properly with TensorFlow Lite. <resources/saved_model_nanodet_320x320/model_float16_quant.tflite> seems to work correctly, so can I substitute this?

The script will run.But the results arent poor with that model.Even if I decrease the class_score_threshold and NMS threshold,the output of cv2.dnn.NMS will return null.

I was wondering whether its an issue of the script provided in this repo (may be someother preprocessing needs to be done other than the standardisation) or the model.

**Comment by IAM-P-LP** [comment]
> I don't know the cause at this point, but the NanoDet-m model doesn't seem to work properly with TensorFlow Lite. <resources/saved_model_nanodet_320x320/model_float16_quant.tflite> seems to work correctly, so can I substitute this?

**Comment by IAM-P-LP** [comment]
Hi @Kazuhito00 ,

I took the model you mentioned and I got this error.

scores = scores[indexes[:, 0]]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

which I solved.
so even though multiple BB are there,I am getting some output atleast(Which I have attached below)

So I guess like you said , NanoDet-m model doesn't work properly with TensorFlow Lite.I wish it was somehow mentioned in this repo.Might have saved me lots of hours.
Thankyou @Kazuhito00 !

**Comment by PINTO0309** [comment]
You're right, I'll remove NanoDet-m.

**Comment by PINTO0309** [comment]
commited: 08fff64cae7479cc44171e23394060a6e5b6ec76

**Comment by PINTO0309** [comment]
NanoDet-m seems to have a problem with it, so I removed it. Please convert it by yourself.

**Comment by IAM-P-LP** [comment]
Hi @PINTO0309 
Thankyou for your reply.Can you please tell me what do you mean by converting.Should I convert the tensorflow model from this repo to tflite again?

**Comment by PINTO0309** [comment]
That's right.
