### ISSUE TITLE
What's the version of tensorflow PINTO_model_zoo/180_YOLOv5-Lite models.

### ISSUE THREAD

**Issue by busyyang** [PINTO0309/PINTO_model_zoo#185]
### Issue Type

Support

### OS

Windows

### OS architecture

x86_64

### Programming Language

Python

### Framework

TensorFlowLite

### Model name and Weights/Checkpoints URL

https://github.com/PINTO0309/PINTO_model_zoo/tree/main/180_YOLOv5-Lite

### Description

I'm trying to run the tflite model from `PINTO_model_zoo/180_YOLOv5-Lite`, But there are some version-mixed problems. Here is code :
~~~py
import tensorflow as tf
import time
import numpy as np
from pprint import pprint


interpreter = tf.lite.Interpreter(model_path=f'model_integer_quant.tflite')
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

roop = 1
e = 0.0
result = None
inp = np.ones((1,H,W,3), dtype=np.float32)
for _ in range(roop):
    s = time.time()
    interpreter.set_tensor(input_details[0]['index'], inp)
    interpreter.invoke()
    result = interpreter.get_tensor(output_details[0]['index'])
    e += (time.time() - s)
print('tflite output @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@')
print(f'elapsed time: {e/roop*1000}ms')
print(f'shape: {result.shape}')
pprint(result)
~~~
When I use `tensorflow==2.4.1`, the output msg is:
~~~
ValueError: Didn't find op for builtin opcode 'SLICE' version '5'
~~~ 

I also try to use `tensorflow==1.x`,
~~~
ValueError: Didn't find op for builtin opcode 'TRANSPOSE' version '4'
~~~

Could any one sign the matched version of tensorflow for use?

**Comment by PINTO0309** [comment]
v2.4.1 is too old. Please use TensorFlow Lite v2.8.0.
https://github.com/PINTO0309/TensorflowLite-bin

**Comment by busyyang** [comment]
Thanks, it works well on tf2.8.
