### ISSUE TITLE
model conversion failed

### ISSUE THREAD

**Issue by happyjohn360** [PINTO0309/PINTO_model_zoo#19]
I tried to convert .pb file to .tflite file.
I run "06_mobilenetv2-ssdlite/01_coco/01_float32/03_integer_quantization_with_postprocess.py" files and get this error
### ValueError: Invalid tensors 'TFLite_Detection_PostProcess,TFLite_Detection_PostProcess:1,TFLite_Detection_PostProcess:2,TFLite_Detection_PostProcess:3' were found.

I've run the script to download tflite_graph.pb.
could you please check out the problem for me?
Also can you tell me where you get tflite_graph.pb?
can I convert [model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md) ssdlite_mobilenet_v2_coco by your code?
Thanks!

**Comment by PINTO0309** [comment]
First do the following:
**https://github.com/tensorflow/models/blob/master/research/object_detection/export_tflite_ssd_graph.py**
