### ISSUE TITLE
Converting vehicle-detection-0200 output error

### ISSUE THREAD

**Issue by zhongwenkun886** [PINTO0309/PINTO_model_zoo#190]
### Issue Type

Bug

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

TensorFlow

### Model name and Weights/Checkpoints URL

https://github.com/openvinotoolkit/open_model_zoo/tree/2021.4.2/models/intel/vehicle-detection-0200

### Description

When I convert the openVINO model vehicle-detection-0200 as your description in PINTO_model_zoo/178_vehicle-detection-0200/convert_script.txt， it output error as below. I execute it by Docker using the latest version of openvino2tensorflow. Thank you very much!

```
====================================================================================
layer_type: Const
layer_id: 215
tf_layers_dict_shape: (1,)
tf_layers_dict_value: [-1]

ERROR: ConcatOp : Ranks of all input tensors should match: shape[0] = [1,1] vs. shape[1] = [1] [Op:ConcatV2] name: concat
ERROR: model_path  : vehicle-detection-0200.xml
ERROR: weights_path: vehicle-detection-0200.bin
ERROR: layer_id    : 216
ERROR: input_layer0 layer_id=214: tf.Tensor([[1]], shape=(1, 1), dtype=int64)
ERROR: input_layer1 layer_id=215: Const(ndarray).shape  (1,)
array([-1])
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/usr/local/bin/openvino2tensorflow", line 2154, in convert
    inp = tf.concat(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 7186, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Ranks of all input tensors should match: shape[0] = [1,1] vs. shape[1] = [1] [Op:ConcatV2] name: concat
```

**Comment by PINTO0309** [comment]
Support for the latest version of openvino2tensorflow v1.28.8.
Commit: 3346b3c1bb8a04d2634049da842b7c3ac85eb718
https://github.com/PINTO0309/PINTO_model_zoo/blob/main/178_vehicle-detection-0200/replace.json

I don't know why you would want to convert it yourself, but you can remove the **`DetectionOutput`** from the XML yourself.

**Comment by zhongwenkun886** [comment]
Thanks. Because I want to  I convert the model vehicle-detection-0201, so I test vehicle-detection-0200 first.

**Comment by zhongwenkun886** [comment]
thanks very much.
 I have convert the model vehicle-detection-0201 successfully.
