### ISSUE TITLE
Bytetrack documentation (how to run)

### ISSUE THREAD

**Issue by callmesora** [PINTO0309/PINTO_model_zoo#192]
### Issue Type

Documentation Feature Request

### OS

Ubuntu

### OS architecture

aarch64

### Programming Language

Python

### Framework

TensorRT

### Model name and Weights/Checkpoints URL

NA

### Description

I've wanted to test Bytetrack and I'm having  a rough time from their original repo.
Does your version offer any documentation on how to run it or any help?

**Comment by PINTO0309** [comment]
I just converted the models from the repository cited here for various frameworks. Therefore, all documents are listed in the citation repository. We welcome your pull requests for demo codes.
https://github.com/ifzhang/ByteTrack
