### ISSUE TITLE
Is gated convolution possible to convert to onnx?

### ISSUE THREAD

**Issue by napohou** [PINTO0309/PINTO_model_zoo#193]
### Issue Type

Support

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

C++

### Framework

ONNX

### Model name and Weights/Checkpoints URL

Deepfill, opn, etc.

### Description

I need some help on converting deepfill model to onnx.

**Comment by PINTO0309** [comment]
If the URL of the citation is not provided, it will be closed immediately.
