### ISSUE TITLE
Is gated convolution possible to convert to onnx?

### ISSUE THREAD

**Issue by napohou** [PINTO0309/PINTO_model_zoo#194]
### Issue Type

Support

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

C++

### Framework

ONNX

### Model name and Weights/Checkpoints URL

OPN: https://github.com/seoungwugoh/opn-demo
Deepfill: https://github.com/JiahuiYu/generative_inpainting

### Description

I need some help on convert deepfill and opn to onnx models.

**Comment by PINTO0309** [comment]
Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International Public License
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/273_OPN

**Comment by PINTO0309** [comment]
Creative Commons Attribution-**`NonCommercial`** 4.0 International Public License
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/274_DeepFillv2

**Comment by napohou** [comment]
Thanks for the quick response.

**Comment by napohou** [comment]
Hi @PINTO0309 
I am trying to infer the onnx file of opn model you converted. I have a question. From line #95 and line #111 of https://github.com/seoungwugoh/opn-demo/blob/master/demo_video.py, we can see that OPN model accepts 3 and 6 parameters respectively. How can we handle this situation when infer the onnx file? Thanks!

**Comment by napohou** [comment]
From https://github.com/seoungwugoh/opn-demo/blob/master/models/OPN.py, please see:
    def forward(self, *args, **kwargs):
        # print(len(args), len(kwargs))
        if len(args) == 3:
            return self.memorize(*args)
        else:
            return self.read(*args, **kwargs)
Seem you exported self.memorize(*args)? If so, would you mind export self.read(*args, **kwargs) again? Thanks. :-)
