### ISSUE TITLE
Please help to convert LaMa to onnx model

### ISSUE THREAD

**Issue by napohou** [PINTO0309/PINTO_model_zoo#195]
### Issue Type

Support

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

C++

### Framework

ONNX

### Model name and Weights/Checkpoints URL

LaMa: https://github.com/saic-mdal/lama

### Description

This is a good inpainting model.

**Comment by PINTO0309** [comment]
- Duplicate Issue
https://github.com/PINTO0309/PINTO_model_zoo/issues/177

Please do an issue search and then submit your issue.
https://github.com/PINTO0309/PINTO_model_zoo/issues?q=Lama

**Comment by napohou** [comment]
I see. Thanks, brother.
