### ISSUE TITLE
Question: how to connvert mediapipe tflite model to onnx

### ISSUE THREAD

**Issue by wwdok** [PINTO0309/PINTO_model_zoo#197]
### Issue Type

Support

### OS

Windows

### OS architecture

x86_64

### Programming Language

Python

### Framework

NCNN

### Model name and Weights/Checkpoints URL

https://github.com/google/mediapipe/tree/master/mediapipe/modules/face_landmark/face_landmark.tflite

### Description

Hello, @PINTO0309 , sorry for bothering you, I want to convert [face_landmark_with_attention.tflite](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_landmark/face_landmark_with_attention.tflite) to NCNN format, then firstly I try to convert it to onnx format, but I encounter some errors, I posted it at StackOverFlow : [stackoverflow.com/questions/71612332/how-to-connvert-mediapipe-tflite-model-to-onnx](https://stackoverflow.com/questions/71612332/how-to-connvert-mediapipe-tflite-model-to-onnx) , do you have time to look at it ? Thanks in advance !

**Comment by PINTO0309** [comment]
This is a duplicate issue and will be closed immediately.
[Request: FaceMesh-with-Attention model conversion (unsupported custom ops) #143](https://github.com/PINTO0309/PINTO_model_zoo/issues/143)

You should search the issue before asking a question.
https://github.com/PINTO0309/PINTO_model_zoo/issues?q=attention
