### ISSUE TITLE
./download not working for 053_BlazePose files and some others

### ISSUE THREAD

**Issue by torossianld** [PINTO0309/PINTO_model_zoo#198]
### Issue Type

Bug

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Other

### Framework

Other

### Model name and Weights/Checkpoints URL

053_BlazePose

### Description

Hi!
First of all thank you very much for your amazing work.

I have an issue when I try to download the models in 053_BlazePose. 
Here are my commands:

$ cd 053_BlazePose/03_pose_landmark_full_body/
$ ./download.sh

and I got the following issue :

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Download finished.

I precise that I can download some models, for example the following commands work :

$ cd 006_mobilenetv2-ssdlite/02_voc/03_integer_quantization
$ ./download.sh && cd ..

**Comment by PINTO0309** [comment]
Due to a change in Google Drive specifications, it appears that all scripts that download files of large size are now failing. We are waiting for your pull request.
Fix: https://github.com/PINTO0309/PINTO_model_zoo/commit/4216cdb3d8adbb7353c75a3831b5e27f40de1623
