### ISSUE TITLE
EfficientDet INT8 Quantization

### ISSUE THREAD

**Issue by dreamibor** [PINTO0309/PINTO_model_zoo#20]
Hi @PINTO0309,

Did you manage to fully quantize the EfficientDet models? I saw there are some quantized models in your zoo: https://github.com/PINTO0309/PINTO_model_zoo/tree/master/18_EfficientDet/03_integer_quantization, but they look more like only weight quantized, right?
I think you didn't add:
` converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]`
to limit the operators to be INT8?

I tried myself to fully quantize EfficientDet, and I failed with TF1.15.0, TF2.2.0 and TF2.3.0.

If you've managed to quantize the model, could you give me some enlightenment on this?

Thank you!

**Comment by PINTO0309** [comment]
>If you've managed to quantize the model, could you give me some enlightenment on this?

I have already successfully quantized it. However, there appears to be a problem with TFLiteConverter. The Dequantize OP does not appear to generate correctly, so using the generative model causes an error when inferring. I have published an issue in the official Tensorflow repository.
**[[TFLite] Two consecutive Dequantize OPs are generated in the structure of the model after integer quantization #41308](https://github.com/tensorflow/tensorflow/issues/41308)**

**Comment by dreamibor** [comment]
Thank you for your reply, it seems you didn't constraint all the operators to be INT8, so it's not a fully quantized model?
I got problems when I add the line:
`converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]`
this limit the converter to only use INT8 operators. 
But due to unsupported INT8 operators such as DIV, ReduceMax, NonMaxSuppression V5, I failed to convert a fully quantized INT8 mode.

**Comment by PINTO0309** [comment]
I tried to convert PyToch's model to saved_model. Can I try it?
https://twitter.com/PINTO03091/status/1322867230103597056?s=20

**Comment by fogelton** [comment]
I noticed the issue of the tflite converter has been solved. The quantized model is still not present and not stated in readme table to support tpu. Is there another issue? have you tried to fully quantized efficientdet to run it on coral?

**Comment by PINTO0309** [comment]
The full INT8 quantization was successful, but it seems to abort when compiled with edgetpu_compiler. This model intentionally removes the Post-Process. I'll have to ask support to find out the cause.

- Repository of citations
**https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch.git**

- EfficientDet D0 Full Integer Quantization .tflite
**https://drive.google.com/file/d/1blXmW5FMuKJCbv7h6g5uzS-628FAfZ40/view?usp=sharing**

- edgetpu_compiler Abort
![Screenshot 2020-12-11 00:49:40](https://user-images.githubusercontent.com/33194443/101795025-cf82b300-3b4a-11eb-8c83-755e0a2891e4.png)

- Graph
![efficientdet_d0_512x512_full_integer_quant tflite_](https://user-images.githubusercontent.com/33194443/101794742-86cafa00-3b4a-11eb-8f94-f6b643d68a1c.png)

**Comment by PINTO0309** [comment]
I have posted an issue. https://github.com/google-coral/edgetpu/issues/279

**Comment by yosefyehoshua** [comment]
Hi @PINTO0309 , I've noticed you've added an [edgetpu optimized efficientDet-d0]([https://github.com/PINTO0309/PINTO_model_zoo/tree/master/018_EfficientDet/10_official_efficientdet_d0/03_edgetpu_optimized](url)). Did you managed to compile with edgetpu_compiler?

**Comment by PINTO0309** [comment]
I think it can be compiled by lowering the resolution. For example, 512x512 -> 256x256 or 128x128

**Comment by yosefyehoshua** [comment]
Hi thanks for the reply :1st_place_medal:. I acctually need a higher resolution, do you know something about an input limitation on edgetpu?

**Comment by PINTO0309** [comment]
@yosefyehoshua 

> do you know something about an input limitation on edgetpu?

I don't know the compiler specifications because they are not publicly available.

> how would you convert the tflite model ops to int8?

I'm not sure how to answer this, but just use TFLiteConverter.
Alternatively, you can use a tool I created to make the conversion somewhat easier without any technical knowledge.
**https://github.com/PINTO0309/openvino2tensorflow**

![Screenshot 2020-12-30 00:08:58](https://user-images.githubusercontent.com/33194443/103293422-423ccb00-4a33-11eb-9870-12e6bd1c65db.png)

https://user-images.githubusercontent.com/33194443/103293964-38679780-4a34-11eb-8eaa-0cb2bf88a179.mp4
