### ISSUE TITLE
DeepLabv3+ and OpenVINO

### ISSUE THREAD

**Issue by pjramg** [PINTO0309/PINTO_model_zoo#21]
Hi @PINTO0309 ! Thanks for this amazing repo. Congrats!. 

I'm looking for a way to run DeepLabv3+ with OpenVINO. I see that in your repository you have several folders related to this model. It seems that the one that best fits my needs is Sample.4 - Semantic Segmentation, DeeplabV3-plus 256x256. But I would like to do the development simply by calling the executable files and the XML, as in the typical OpenVINO examples. This example requires TensorFlow installation. What about OpenVINO-bin? I did not find a lot of documentation about this latter one. 
I am using RPi4 and a OAK-D camera.

Thanks for your help.

**Comment by PINTO0309** [comment]
Please wait a little because I will be home in 16 hours.

**Comment by PINTO0309** [comment]
Sorry. I guess I'm too busy today to get any sleep. I'll be releasing it later, so please be patient for a bit.

**Comment by PINTO0309** [comment]
@pjramg 
I have committed a sample program. Please feel free to use it.
**https://github.com/PINTO0309/PINTO_model_zoo/tree/master/26_mobile-deeplabv3-plus/07_openvino**

**FP16 + CPU 30 FPS**
![ezgif com-optimize (1)](https://user-images.githubusercontent.com/33194443/89712601-ee224300-d9cc-11ea-9813-edac2ca093f3.gif)

**FP16 + USB3.0 + MYRIAD 15 FPS**
![ezgif com-optimize (2)](https://user-images.githubusercontent.com/33194443/89712656-35a8cf00-d9cd-11ea-81d6-f8acf161f924.gif)

**Comment by pjramg** [comment]
That sounds great. I'll be home in a day. I'll let you know how it went with your model. Thank you very much.

**Comment by pjramg** [comment]
Hi @PINTO0309. I am trying to run your code, I am not sure what is the issue is about. So I share my screenshot.  Please let me some lights to continue. Thanks.

![2020-08-10-150256_1920x1080_scrot](https://user-images.githubusercontent.com/10940214/89820412-f8eaee00-db1a-11ea-9bc6-2b70d6f00067.png)

**Comment by PINTO0309** [comment]
Follow the official tutorial to update to the latest **`OpenVINO 2020.4`**.
**https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_raspbian.html**

**Comment by pjramg** [comment]
Thanks, @PINTO0309. It was the version I installed on RPi.

**Comment by pjramg** [comment]
Some updates on my side. I am trying to fix this issue, and follow a the error that terminal shows me. So, it seems that it is because of I only have the OAK-D camera plug to RPi, and it is not recognize directly, the RPi recognizes the VPU. Also I select this device with `--device MYRIAD` using `python3 deeplabv3plus_usbcam.py --device MYRIAD` and I got this warning. `[ WARN:0] global ../opencv/modules/videoio/src/cap_v4l.cpp (893) open VIDEOIO(V4L2:/dev/video0): can't open camera by index`. Let me know if you have some ideas I could use. Thanks for your valuable help.

**Comment by PINTO0309** [comment]
Check what port the USB camera or the built-in camera is recognized on. You just need to specify the recognized port number as the program argument. **`--usbcamno`** The default is **`0`**.

```
$ ls -l /dev/video*
```
![Screenshot 2020-08-12 06:45:40](https://user-images.githubusercontent.com/33194443/89952038-76bc1000-dc67-11ea-9f0f-b19f6a7d3f18.png)

**Comment by pjramg** [comment]
Maybe I have a problem with the cameras (BW1098FFC).
![2020-08-11-180807_1920x1080_scrot](https://user-images.githubusercontent.com/10940214/89953758-b4844e80-dbfd-11ea-8486-9d0aad975b4d.png)

**Comment by PINTO0309** [comment]
I don't own an OAK-D so I can't try it. Follow the official tutorial below and give it a try.
**https://github.com/luxonis/depthai-tutorials.git**

**Comment by pjramg** [comment]
The OAk-D camera is running well Object detection models, but not Semantic Segmentation models. The examples from thy webpage are running well, I am trying to run deeplav3+ on the camera as a NCS2 (OpenVINO) and follow your examples.

**Comment by PINTO0309** [comment]
Please modify my sample program to access the camera in a different way.
https://github.com/luxonis/depthai-tutorials/blob/0f4e3feadad4003dc153eac06a2e80d3009b2de8/2-face-detection-retail/face-detection-retail-0004.py#L5-L32

**Comment by PINTO0309** [comment]
There is no progress, so I'll close it.
