### ISSUE TITLE
schema.fbs error: illegal character: <

### ISSUE THREAD

**Issue by ttducqt** [PINTO0309/PINTO_model_zoo#23]
I am trying to convert blazeface_front.tflite to .pb and getting stack at there

`output json command = flatc -t --strict-json --defaults-json -o . schema.fbs -- face_detection_front.tflite
error: /home/duc/Desktop/FServing/flatbuffers/schema.fbs:6: 1: error: illegal character: <
Traceback (most recent call last):
  File "/home/duc/Desktop/FServing/flatbuffers/blazeface_tflite_to_pb.py", line 210, in <module>
    main()
  File "/home/duc/Desktop/FServing/flatbuffers/blazeface_tflite_to_pb.py", line 168, in main
    ops, op_types = parse_json()
  File "/home/duc/Desktop/FServing/flatbuffers/blazeface_tflite_to_pb.py", line 30, in parse_json
    j = json.load(open(model_json_path))
FileNotFoundError: [Errno 2] No such file or directory: 'face_detection_front.json'`

**Comment by PINTO0309** [comment]
The faltc I generated is for x86 architectures. Do you have an x86 CPU? If not, you'll have to build it yourself. Also, if the flatc path is not correct, you can fix it yourself.

https://github.com/PINTO0309/PINTO_model_zoo/blob/4edf88efd0be89d7e83164e28f8c8fa033bed272/30_BlazeFace/01_float32/01_blazeface_tflite_to_pb.py#L16

**Comment by ttducqt** [comment]
I run on Ubuntu 18.04 64bit - Intel Core i5-6400U. The faltc path is correct, i  run inside the flatbuffers folder, where i built the flatc

**Comment by PINTO0309** [comment]
Where did you try to download the tflite file and convert it with flatc? The latest repository has only the Float16 quantized .tflite available, so you can download the Float32 file from the commit below and try it out.

**https://github.com/google/mediapipe/blob/294687295d502f1bec3fe140c25538adefa11a14/mediapipe/models/face_detection_front.tflite**

**Comment by ttducqt** [comment]
Btw, does your script work with "face_detection_back.tflite" version ?

[https://github.com/google/mediapipe/blob/master/mediapipe/models/face_detection_back.tflite](url)

**Comment by PINTO0309** [comment]
It also doesn't work because it's Float16 quantized.

**Comment by PINTO0309** [comment]
I have committed face_detection_back.tflite.
https://github.com/PINTO0309/PINTO_model_zoo/tree/master/30_BlazeFace

**Comment by PINTO0309** [comment]
There is no progress, so I'll close it.
