### ISSUE TITLE
Model miss

### ISSUE THREAD

**Issue by Crusoekid** [PINTO0309/PINTO_model_zoo#24]
Google has released a Hair Segmentation model, but you don't seem to have this project at present.

**Comment by PINTO0309** [comment]
Unfortunately, the hair segmentation model contains custom OPs for "MaxPoolingWithArgmax2D", "MaxUnpooling2D" and "Convolution2DTransposeBias", so there are no plans to convert them at this time.

**Comment by Crusoekid** [comment]
ohhh,thx a lot
