### ISSUE TITLE
Please convert another part of OPN model to onnx

### ISSUE THREAD

**Issue by napohou** [PINTO0309/PINTO_model_zoo#244]
### Issue Type

Bug

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

ONNX

### Model name and Weights/Checkpoints URL

OPN: https://github.com/seoungwugoh/opn-demo/

### Description

From https://github.com/seoungwugoh/opn-demo/blob/master/models/OPN.py, please see:
def forward(self, *args, **kwargs):
# print(len(args), len(kwargs))
if len(args) == 3:
return self.memorize(*args)
else:
return self.read(*args, **kwargs)
Seem you only exported self.memorize(*args)? If so, would you mind export self.read(*args, **kwargs) as well? Thanks. :-)

**Comment by napohou** [comment]
You can also show me the converting script so I can do it myself.

**Comment by PINTO0309** [comment]
Just write an export statement here. I'm not really interested in this model at the moment, so please try it yourself first.

https://github.com/seoungwugoh/opn-demo/blob/5c7229c518851a3e6b6944ae09fc42368f32b262/demo_group_image.py#L84-L94
