### ISSUE TITLE
SwinIR super resolution coreml, tflite conversion

### ISSUE THREAD

**Issue by Vozf** [PINTO0309/PINTO_model_zoo#247]
### Issue Type

Feature Request

### OS

Other

### OS architecture

Other

### Programming Language

Python

### Framework

PyTorch

### Model name and Weights/Checkpoints URL

https://github.com/JingyunLiang/SwinIR

### Description

It would be nice to add the current sota for image super resolution and denoising

**Comment by PINTO0309** [comment]
https://github.com/fenglinglwb/EDT

**Comment by PINTO0309** [comment]
Six months ago, a tool was completed to convert from onnx to various model formats. I don't think you are interested anymore, but if you need to, you can convert it on your own.

https://github.com/PINTO0309/onnx2tf

![image](https://github.com/PINTO0309/PINTO_model_zoo/assets/33194443/d33b83ae-eaa1-400c-bfa8-d08c56f3543b)
