### ISSUE TITLE
Posenet Edge TPU

### ISSUE THREAD

**Issue by thibault390** [PINTO0309/PINTO_model_zoo#25]
Hi,

I'm a little bit beginner and I'm looking for official posenet model (257) based on mobilenet for edgetpu (google dev board). Do you have such model please because I didn't find or I missed it in your repositories ?  :)

Thanks for help

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/PINTO_model_zoo/blob/master/03_posenet/url.txt

**Comment by thibault390** [comment]
No problem

I  used posenet with model from https://github.com/PINTO0309/PINTO_model_zoo/tree/master/03_posenet/03_posenet/03_integer_quantization 
and compiled for edgeTPU

Thanks for the reply

**Comment by PINTO0309** [comment]
committed
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/003_posenet
