### ISSUE TITLE
BlazePose frozen model

### ISSUE THREAD

**Issue by vpenades** [PINTO0309/PINTO_model_zoo#26]
Sorry to bother you again with this... I guess you're already working on converting the BlazePose TFLite models to Frozen model as long as saved model?

I've successfully ran the TfLite models, and even in desktop and using only CPU the models are very fast and responsive, it's definitely a much better solution than the PoseNet models.

My understanding is that PoseNet models are better suited for one shot detection, whereas BlazePose is better for continuous tracking, which makes it very good for realtime applications.

**Comment by PINTO0309** [comment]
It's not a huge amount of work, so I generated a .pb and committed it. Use download.sh to download the materials again.
**https://github.com/PINTO0309/PINTO_model_zoo/tree/master/53_BlazePose/01_float32**
![Screenshot 2020-08-21 08:03:56](https://user-images.githubusercontent.com/33194443/90834309-f4c59880-e384-11ea-8f25-382f2439303e.png)

**Comment by vpenades** [comment]
Thanks a lot!

**Comment by vpenades** [comment]
@PINTO0309 It seems someone extracted the FULL BODY models from MLKIT: https://github.com/asus4/tf-lite-unity-sample/tree/master/Assets/StreamingAssets/mlkit

You might one to take a look and include these into your repository?

**Comment by PINTO0309** [comment]
Thanks for sharing. I think I'll try to convert sooner or later. I've checked the structure of the model and it looks like it's only a little more OP's diagram below than the upper body only model. The structure of the model is almost identical.

What I'm wondering is what the license is for the tflite model of Blaze Pose Full.

**Comment by vpenades** [comment]
I have no idea about the license... my impression is that they're releasing the model straight away into MLKit to make it easy to use for developers and nothing else. What seems to be preventing them releasing the models for other platforms is that it would imply that they need to give maintenance and support for these platforms.

For example, developers have requested the full body to be available in MediaPipe for windows, and for TensorFlow.JS... but right now they're having serious issues trying to compile the windows version of MediaPipe.

**Comment by PINTO0309** [comment]
It looks like an Apache 2.0 license. I plan to do conversion work on weekends when I have time.
https://t.co/BU6b4cLHUu?amp=1

**Comment by PINTO0309** [comment]
@vpenades First, only the Accurate version of the model was committed.
**https://github.com/PINTO0309/PINTO_model_zoo/tree/master/058_BlazePose_Full_Keypoints**

**Comment by PINTO0309** [comment]
@vpenades 
An additional Lite version has been committed.
**https://github.com/PINTO0309/PINTO_model_zoo/tree/master/058_BlazePose_Full_Keypoints**

**Comment by bhavikapanara** [comment]
> Sorry to bother you again with this... I guess you're already working on converting the BlazePose TFLite models to Frozen model as long as saved model?
> 
> I've successfully ran the TfLite models, and even in desktop and using only CPU the models are very fast and responsive, it's definitely a much better solution than the PoseNet models.
> 
> My understanding is that PoseNet models are better suited for one shot detection, whereas BlazePose is better for continuous tracking, which makes it very good for realtime applications.

Hi @vpenades 

How could you run BlazePose TFlite model on cpu? Can you please share the python script and TFLite model file for pose estimation?

Thanks a lot

**Comment by vpenades** [comment]
@bhavikapanara I'm not using python, my project is in c# with Emgu.TF.Lite , which can run tflite models on the CPU.

**Comment by bhavikapanara** [comment]
@vpenades Thanks for the quick reply.

Actually, I am able to run the TFLite model on the CPU. But I am facing issues to decode output.

This is the output format:

```
[{'name': 'Identity',
  'index': 285,
  'shape': array([  1, 128, 128,   1], dtype=int32),
  'shape_signature': array([ -1, 128, 128,   1], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}},
 {'name': 'Identity_1',
  'index': 379,
  'shape': array([1, 1, 1, 1], dtype=int32),
  'shape_signature': array([-1,  1,  1,  1], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}},
 {'name': 'Identity_2',
  'index': 381,
  'shape': array([  1, 156], dtype=int32),
  'shape_signature': array([  1, 156], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}}]
```

Form this how to get all detected ket-points coordinates

@PINTO0309 Can you please help me with this?

Thanks,
Bhavika

**Comment by vpenades** [comment]
I'm not an expert on python, I understand the official solution to use these models with python is this one: https://google.github.io/mediapipe/solutions/pose.html#python-solution-api
