### ISSUE TITLE
Docs Request abt Converting Models

### ISSUE THREAD

**Issue by zogojogo** [PINTO0309/PINTO_model_zoo#264]
### Issue Type

Documentation Feature Request

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

ONNX

### Model name and Weights/Checkpoints URL

https://drive.google.com/file/d/1O2k5k4BZ_6lIm-5MZEAe2JGB6v73FYM1/view?usp=sharing

### Description

Do you have any tutorial on how to convert my model from onnx/pytorch/openvino model to tflite/edgetpu?? because I just found the convertscript but don't know how to use it

**Comment by PINTO0309** [comment]
Let me reiterate. The type and name of the model in question is not stated, so there is no way to address it.

**Comment by zogojogo** [comment]
Oh sorry, it's YOLOX-tiny

**Comment by PINTO0309** [comment]
Please correct the Description first. The people who submit issues to this repository all have too little information as well.

**Comment by PINTO0309** [comment]
- convert script
https://github.com/PINTO0309/PINTO_model_zoo/blob/main/132_YOLOX/convert_script.txt

- reference
  - https://github.com/PINTO0309/openvino2tensorflow#4-setup
  - https://github.com/PINTO0309/openvino2tensorflow#5-usage
  - https://github.com/PINTO0309/openvino2tensorflow#6-execution-sample
  - https://github.com/PINTO0309/openvino2tensorflow#6-7-replace-weights-or-constant-values-in-const-op-and-add-transpose-or-reshape-or-cast-or-squeeze-or-unsqueeze-or-add-or-multiply-just-beforeafter-the-operation-specified-by-layer_id
