### ISSUE TITLE
Docs Request for Converting RAFT Models

### ISSUE THREAD

**Issue by Shidqiet** [PINTO0309/PINTO_model_zoo#265]
### Issue Type

Documentation Feature Request

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

ONNX

### Model name and Weights/Checkpoints URL

RAFT: https://drive.google.com/uc?export=download&id=1-MEqAKfFgqVjyzbdf74qcVIuD2KIQXrE

### Description

Thank you for the great work. Do you have any documentation on how to convert RAFT model from pytorch into onnx? I already tried to convert it from https://github.com/princeton-vl/RAFT but I get error on the gridsample operation. Thank you

**Comment by PINTO0309** [comment]
All you have to do is install PyTorch v1.12.0 and export to ONNX with opset=16.

The converted model committed to my repository is very old and very verbose due to special modifications to the model prior to PyTorch v1.10.0. 

- utils.py: From
```python
img = F.grid_sample(img, grid, align_corners=True)
```
- utils.py: To
```python
def bilinear_grid_sample(im, grid, align_corners=False):
    """Given an input and a flow-field grid, computes the output using input
    values and pixel locations from grid. Supported only bilinear interpolation
    method to sample the input pixels.

    Args:
        im (torch.Tensor): Input feature map, shape (N, C, H, W)
        grid (torch.Tensor): Point coordinates, shape (N, Hg, Wg, 2)
        align_corners {bool}: If set to True, the extrema (-1 and 1) are
            considered as referring to the center points of the input’s
            corner pixels. If set to False, they are instead considered as
            referring to the corner points of the input’s corner pixels,
            making the sampling more resolution agnostic.

    Returns:
        torch.Tensor: A tensor with sampled points, shape (N, C, Hg, Wg)
    """
    n, c, h, w = im.shape
    gn, gh, gw, _ = grid.shape
    assert n == gn
    x = grid[:, :, :, 0]
    y = grid[:, :, :, 1]
    if align_corners:
        x = ((x + 1) / 2) * (w - 1)
        y = ((y + 1) / 2) * (h - 1)
    else:
        x = ((x + 1) * w - 1) / 2
        y = ((y + 1) * h - 1) / 2
    x = x.view(n, -1)
    y = y.view(n, -1)
    x0 = torch.floor(x).long()
    y0 = torch.floor(y).long()
    x1 = x0 + 1
    y1 = y0 + 1
    wa = ((x1 - x) * (y1 - y)).unsqueeze(1)
    wb = ((x1 - x) * (y - y0)).unsqueeze(1)
    wc = ((x - x0) * (y1 - y)).unsqueeze(1)
    wd = ((x - x0) * (y - y0)).unsqueeze(1)
    # Apply default for grid_sample function zero padding
    im_padded = F.pad(im, pad=[1, 1, 1, 1], mode='constant', value=0)
    padded_h = h + 2
    padded_w = w + 2
    # save points positions after padding
    x0, x1, y0, y1 = x0 + 1, x1 + 1, y0 + 1, y1 + 1
    # Clip coordinates to padded image size
    x0 = torch.where(x0 < 0, torch.tensor(0), x0)
    x0 = torch.where(x0 > padded_w - 1, torch.tensor(padded_w - 1), x0)
    x1 = torch.where(x1 < 0, torch.tensor(0), x1)
    x1 = torch.where(x1 > padded_w - 1, torch.tensor(padded_w - 1), x1)
    y0 = torch.where(y0 < 0, torch.tensor(0), y0)
    y0 = torch.where(y0 > padded_h - 1, torch.tensor(padded_h - 1), y0)
    y1 = torch.where(y1 < 0, torch.tensor(0), y1)
    y1 = torch.where(y1 > padded_h - 1, torch.tensor(padded_h - 1), y1)
    im_padded = im_padded.view(n, c, -1)
    x0_y0 = (x0 + y0 * padded_w).unsqueeze(1).expand(-1, c, -1)
    x0_y1 = (x0 + y1 * padded_w).unsqueeze(1).expand(-1, c, -1)
    x1_y0 = (x1 + y0 * padded_w).unsqueeze(1).expand(-1, c, -1)
    x1_y1 = (x1 + y1 * padded_w).unsqueeze(1).expand(-1, c, -1)
    Ia = torch.gather(im_padded, 2, x0_y0)
    Ib = torch.gather(im_padded, 2, x0_y1)
    Ic = torch.gather(im_padded, 2, x1_y0)
    Id = torch.gather(im_padded, 2, x1_y1)
    return (Ia * wa + Ib * wb + Ic * wc + Id * wd).reshape(n, c, gh, gw)

img = bilinear_grid_sample(img, grid, align_corners=True)
```

**Comment by Shidqiet** [comment]
Thanks for your answer!

**Comment by ashank-art** [comment]
Hi, @Shidqiet , Have you done the conversion using the above pytorch model, how many output nodes are you getting in the converted onnx model?
Because i am seeing more than two output nodes.

**Comment by Shidqiet** [comment]
Hi @ashank-art . As far as I remember I just needed to set the default `test_mode` value to `True` in this [line](https://github.com/princeton-vl/RAFT/blob/aac9dd54726caf2cf81d8661b07663e220c5586d/core/raft.py#L86), and then removing the `coords1 - coords0` in the return so the model will just return the `flow_up` in this [line](https://github.com/princeton-vl/RAFT/blob/aac9dd54726caf2cf81d8661b07663e220c5586d/core/raft.py#L142), because `flow_up` is the optical flow we are looking for. I hope this helps!

**Comment by ashank-art** [comment]
Thank you. About inference time have you validated, the model @PINTO0309 has uploaded is taking less time than the converted one? Do you have the similar observation?
@PINTO0309 can you specify which version of torch being used while conversion?
Any specific points to be considered?

**Comment by PINTO0309** [comment]
![image](https://user-images.githubusercontent.com/33194443/204749439-029385a9-f886-49ac-883d-00b800264b61.png)

**Comment by ashank-art** [comment]
Thank you @PINTO0309 . I am using the same environment and the code script, still the inference time is more than the model you uploaded. And i am getting different model size(21mb) you uploaded is 97mb for the same 640*480 resolution. Any suggestion what might be missing?

**Comment by PINTO0309** [comment]
I can't comment on anything since you have not disclosed any source code or other information that you have processed.

**Comment by PINTO0309** [comment]
And please do not start a discussion with a closed issue.

**Comment by PINTO0309** [comment]
And it is good manners to present all reproducible resources.
