### ISSUE TITLE
 What is the conversion script of the yolov7_480_640.onnx model in yolov7? Are you using the official conversion script?thanks

### ISSUE THREAD

**Issue by wj1017090777** [PINTO0309/PINTO_model_zoo#269]
### Issue Type

Others

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

PyTorch

### Model name and Weights/Checkpoints URL

yolov7

### Description

 What is the conversion script of the yolov7_480_640.onnx model in yolov7? Are you using the official conversion script?thanks

**Comment by PINTO0309** [comment]
Yes.
