### ISSUE TITLE
Retraining capability

### ISSUE THREAD

**Issue by dannyway03** [PINTO0309/PINTO_model_zoo#270]
### Issue Type

Support

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

C++

### Framework

TensorFlowLite

### Model name and Weights/Checkpoints URL

FaceMesh-with-Attention

### Description

Hi,

given the saved_model folder, would it be possible to re-train or continue the training of the converted model?
In particular, I'm interested in FaceMesh-with-Attention, but I'm not really an expert on this topic.

many thanks.
D-

**Comment by PINTO0309** [comment]
>given the saved_model folder, would it be possible to re-train or continue the training of the converted model?

No. You will need to rebuild the model using TensorFlow or PyTorch.
https://google.github.io/mediapipe/solutions/face_mesh.html

**Comment by PINTO0309** [comment]
In any case, you should consider whether FaceMesh-with-Attention is really the best solution for you.
- Not FaceMesh-with-Attention
  https://github.com/PINTO0309/Face_Mask_Augmentation

  https://user-images.githubusercontent.com/33194443/180627419-596fc55b-9594-4c01-9ace-d56db66b90c4.mp4
