### ISSUE TITLE
Single-Image-Based HDR Reconstruction

### ISSUE THREAD

**Issue by MariasStory** [PINTO0309/PINTO_model_zoo#273]
### Issue Type

Feature Request

### OS

Windows, Ubuntu, Mac OS, Other

### OS architecture

x86_64, Other

### Programming Language

Python, Other

### Framework

ONNX, TensorFlow.js

### Model name and Weights/Checkpoints URL

https://github.com/wanghu178/KUNet

### Description

Hi @PINTO0309,
Your models are the best.
I have not seen Single-Image-Based HDR Reconstruction in your collection.
Maybe you could convert few of the top performance models?
I want to try them on dark webcam images.
For example, I recommend:
https://github.com/wanghu178/KUNet

### URL or source code for simple inference testing code

https://github.com/wanghu178/KUNet

**Comment by MariasStory** [comment]
Another one:
https://github.com/alex04072000/SingleHDR

**Comment by PINTO0309** [comment]
I have no idea what this model is trying to do.
![1483_medium](https://user-images.githubusercontent.com/33194443/182028860-47b7e04a-c358-4d94-86d6-beee4cc35daa.png)
![1483](https://user-images.githubusercontent.com/33194443/182028872-623912fb-2b17-4064-b8e0-659d02bcaa02.png)

**Comment by MariasStory** [comment]
Sorry, I did not try the model.
Maybe another one?
