### ISSUE TITLE
Feature request for Dynamic Axes for batches on MediaPipe FaceMesh Model

### ISSUE THREAD

**Issue by adityasihag1804** [PINTO0309/PINTO_model_zoo#275]
### Issue Type

Feature Request

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

ONNX, TensorFlowLite

### Model name and Weights/Checkpoints URL

MediaPipe FaceMesh ONNX/TFLITE

### Description

Hi, first of all thanks a lot for the tflite model for MediaPipe FaceMesh model.
I had one request, would it be possible for Dynamic Axes at 0th index for batches in the ONNX model?
I tried it but it doesn't seem it is dynamic at the moment.

I also tried `interpreter.resize_tensor_input` on the tflite model, but got an error there too.

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/facemesh_onnx_tensorrt

**Comment by adityasihag1804** [comment]
Hey, thanks for the Quick Reply. The link you posted, it has the FaceMesh model without Attention, right?
I'm looking for the one "With Attention". 
I got the tflite model from https://github.com/PINTO0309/PINTO_model_zoo/issues/143 , but the files there ar enot for batched input.
