### ISSUE TITLE
Feature request for Dynamic Axes for batches on MediaPipe FaceMesh-WITH-ATTENTION* Model

### ISSUE THREAD

**Issue by adityasihag1804** [PINTO0309/PINTO_model_zoo#276]
### Issue Type

Feature Request

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

ONNX, TensorFlowLite

### Model name and Weights/Checkpoints URL

MediaPipe FaceMesh-WITH-ATTENTION ONNX/TFLITE

### Description

Hi, first of all thanks a lot for the tflite model for MediaPipe-WITH-ATTENTION FaceMesh model.
I had one request, would it be possible for Dynamic Axes at 0th index for batches in the ONNX model?
I tried it but it doesn't seem it is dynamic at the moment.

I also tried interpreter.resize_tensor_input on the tflite model, but got an error there too.

I'm sorry for this duplicate issue, but in the earlier issue, the issue was closed before I could get full clarity, thanks!

**Comment by PINTO0309** [comment]
Unfortunately, this is not possible with the current model structure.
