### ISSUE TITLE
Cant find tflite model for 307_YOLOv7

### ISSUE THREAD

**Issue by lijianyu1985** [PINTO0309/PINTO_model_zoo#277]
### Issue Type

Support

### OS

Windows

### OS architecture

x86_64

### Programming Language

Python

### Framework

TensorFlowLite

### Model name and Weights/Checkpoints URL

https://github.com/PINTO0309/PINTO_model_zoo/tree/main/307_YOLOv7

### Description

I run all of the download scripts, but I didn't find tflite model for 307_YOLOv7

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/307_YOLOv7

![image](https://user-images.githubusercontent.com/33194443/182497934-da1f14f0-4929-4f61-a57c-cc6edf183868.png)

![image](https://user-images.githubusercontent.com/33194443/182498053-db29f68e-1bbc-41b0-a5aa-5a58c09edeec.png)

![image](https://user-images.githubusercontent.com/33194443/182498771-648b3909-542d-4954-9359-36be9ad8fa95.png)

![image](https://user-images.githubusercontent.com/33194443/182498822-e45fb628-1004-4609-97df-03c64a14b9ac.png)

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/PINTO_model_zoo/issues/248
