### ISSUE TITLE
RealtimeStereo - new improvement

### ISSUE THREAD

**Issue by michaelnguyen11** [PINTO0309/PINTO_model_zoo#279]
### Issue Type

Support

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

TensorFlowLite

### Model name and Weights/Checkpoints URL

https://github.com/PINTO0309/PINTO_model_zoo/tree/main/165_RealtimeStereo

### Description

Hi author,

As I know so far, you had some improvement about RealtimeStereo, which are ONNX and Blob models. (https://github.com/luxonis/depthai/issues/173#issuecomment-1134806408)

Could you please share the convert script or public the Tensorflow Lite model ? Many thanks in advance !

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/PINTO_model_zoo/blob/main/165_RealtimeStereo/convert_script.txt
