### ISSUE TITLE
For https://github.com/PINTO0309/PINTO_model_zoo/tree/master/036_Objectron/08_coreml when I use it in ios project I get this error 

### ISSUE THREAD

**Issue by Zulqurnain24** [PINTO0309/PINTO_model_zoo#28]
For https://github.com/PINTO0309/PINTO_model_zoo/tree/master/036_Objectron/08_coreml/sneakers.ml model an error came up when I tried to use it in ios project using this code https://github.com/makeml-app/Live-Object-Recognition-CoreML saying "The model does not have a valid input feature of type image" UserInfo={NSLocalizedDescription=The model does not have a valid input feature of type image}

In this model can you rename "input" in inputs column to "image__0" and give me updated model. It will be a great help. Thanks in advance."

**Comment by PINTO0309** [comment]
I will not be responding individually in the future. The scripts for the conversion are committed to this repository. Basically, you'll have to do it yourself.
**https://drive.google.com/file/d/1qfCze4YzK_FxtKtDpnm_7UwS9yeOwN6s/view?usp=sharing**
![Screenshot 2020-08-31 21:48:57](https://user-images.githubusercontent.com/33194443/91721488-d016bf80-ebd3-11ea-8e6c-8dfa278ef685.png)

**Comment by Zulqurnain24** [comment]
> I will not be responding individually in the future. The scripts for the conversion are committed to this repository. Basically, you'll have to do it yourself.
> **https://drive.google.com/file/d/1qfCze4YzK_FxtKtDpnm_7UwS9yeOwN6s/view?usp=sharing**
> ![Screenshot 2020-08-31 21:48:57](https://user-images.githubusercontent.com/33194443/91721488-d016bf80-ebd3-11ea-8e6c-8dfa278ef685.png)

Ok, I understand. Thanks for the help. God bless you.

**Comment by Zulqurnain24** [comment]
<img width="1247" alt="reference" src="https://user-images.githubusercontent.com/6280238/91724442-c03cb280-ebb6-11ea-94dc-9d641e0e294e.png">
Normally for the usual coreML models that I use I just pass Image (Color 192 x 192) but in this model the input is of 3 dimensional array as can be seen from the above image.
