### ISSUE TITLE
Unable to locate the download script for the model

### ISSUE THREAD

**Issue by anustupc** [PINTO0309/PINTO_model_zoo#280]
### Issue Type

Bug

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

ONNX

### Model name and Weights/Checkpoints URL

150_MobileStereoNet

### Description

The download script is not available at https://github.com/PINTO0309/PINTO_model_zoo/tree/main/150_MobileStereoNet for the MobileStereoNet available. Can you kindly provide the script for that?

Thanks

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/PINTO_model_zoo/issues?q=download+error+
