### ISSUE TITLE
Revisit #280 (Download.sh script not present in 150_MobileStereoNet)

### ISSUE THREAD

**Issue by anustupc** [PINTO0309/PINTO_model_zoo#281]
### Issue Type

Feature Request

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

ONNX

### Model name and Weights/Checkpoints URL

150_MobileStereoNet
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/150_MobileStereoNet

### Description

Hi, 
Thanks for pointing me to the list of issues in #280. However, the list does not seem to address the issue that I am facing. I found one link but that seems to change the format of an existing download_sh script. In this case, for 150_MobileStereoNet (https://github.com/PINTO0309/PINTO_model_zoo/tree/main/150_MobileStereoNet), the download.sh script does not seem to exist. 
I tried running the code (https://gist.github.com/ibaiGorordo/69988fbf83a045e6c58701aa03eb423f) but that does not seem to help. May be I am missing something. It will be great if you can help with providing the download.sh script for the 150_MobileStereoNet folder. 

Thanks

**Comment by PINTO0309** [comment]
Convert it yourself.
https://github.com/cogsys-tuebingen/mobilestereonet
