### ISSUE TITLE
Replace tflite model in mediapipe.

### ISSUE THREAD

**Issue by mch0dmin** [PINTO0309/PINTO_model_zoo#288]
### Issue Type

Support

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

C++

### Framework

Other

### Model name and Weights/Checkpoints URL

https://github.com/PINTO0309/PINTO_model_zoo/tree/main/053_BlazePose/10_lite_full_heavy_version_May6_2021

### Description

hi @PINTO0309 , when I saw this repo, I seemed to have found a treasure. Thank you very much for your contributions and share them.

I want to use 
PINTO_model_zoo/053_BlazePose/10_lite_full_heavy_version_May6_2021/saved_model_lite/model_float32.tflite
to replace pose_landmarks_lite.tflite in mediapipe, but the issue was encountered:
`
I20220902 01:44:00.938908 71426 thread_pool_executor.cc:93] Terminating thread pool.
E20220902 01:44:00.942251 71426 demo_run_graph_main.cc:162] Failed to run the graph: CalculatorGraph::Run() failed in Run: 
Calculator::Process() for node "poselandmarkcpu__poselandmarkbyroicpu__tensorstoposelandmarksandsegmentation__TensorsToFloatsCalculator" failed: ; RET_CHECK failure (mediapipe/calculators/tensor/tensors_to_floats_calculator.cc:98) (num_values)==(1)
`

Can you give me some advice ? Thank you again for sharing !

### Relevant Log Output

```shell
I20220902 01:44:00.938908 71426 thread_pool_executor.cc:93] Terminating thread pool.
E20220902 01:44:00.942251 71426 demo_run_graph_main.cc:162] Failed to run the graph: CalculatorGraph::Run() failed in Run: 
Calculator::Process() for node "poselandmarkcpu__poselandmarkbyroicpu__tensorstoposelandmarksandsegmentation__TensorsToFloatsCalculator" failed: ; RET_CHECK failure (mediapipe/calculators/tensor/tensors_to_floats_calculator.cc:98) (num_values)==(1)
```

### URL or source code for simple inference testing code

https://github.com/google/mediapipe

**Comment by PINTO0309** [comment]
All models committed to my repository have been changed to the standard specification, replacing MediaPipe's custom OP.

Therefore, instead of using MediaPipe, inference should be done using regular TensorFlow Lite. If you want to infer using MediaPipe, you should use the tflite files published by MediaPipe as is.

**Comment by mch0dmin** [comment]
hi @PINTO0309 , i am glad to receive your reply.

If I want to replace the model in mediapipe with my own model instead of directly using the model in mediapipe, do you have any experience in this field? Or can you give me some suggestions and ideas?

**Comment by PINTO0309** [comment]
That question is a topic unrelated to this repository; please inquire in a MediaPipe issue.

I only converted the model because I did not want to use MediaPipe.

**Comment by ovshake** [comment]
Hi @mch0dmin , were you able to solve this issue? I have similar requirements.
