### ISSUE TITLE
322 - YoloV7 - model with dynamic size only accepts 480x640 dimension

### ISSUE THREAD

**Issue by vpenades** [PINTO0309/PINTO_model_zoo#289]
### Issue Type

Support

### OS

Windows

### OS architecture

x86_64

### Programming Language

Other

### Framework

ONNX

### Model name and Weights/Checkpoints URL

yolov7_head_0.752_Nx3xHxW.onnx

### Description

Using C# and Microsoft.OnnxRuntime (maybe you could include these in Programming Lang and Framework.

I am trying to use that model which is supposed to accept dynamic dimensions, so I can create a the input tensor with the same size of the image, so it doesn't require resizing the source image.

When I try to run that model with sizes other than 480x640, my provider throws an exception.

So, I am doing something wrong?

It's this model fixed to 480x640 regardless of the input dimensions?

**Comment by PINTO0309** [comment]
I generated the model a few days after YOLOv7 was released. Thus, it appears that YOLOv7 at the time it was released did not support variable size for the last `Add` of the model. The Nx3xHxW model is only generated and committed on a trial basis.
![image](https://user-images.githubusercontent.com/33194443/188092611-ab2e958a-62f5-42a8-9e75-ad1cc476f6aa.png)

It would work if you used sam4onnx and rewrote the Add OP constants yourself.
e.g.1
`480 // 32 = 15`
`640 // 32 = 20`
e.g.2
`736 // 32 = 23`
`1280 // 32 = 40`
https://github.com/PINTO0309/sam4onnx
![image](https://user-images.githubusercontent.com/33194443/188093999-0cf4cab5-1651-4a75-9a08-5e3538b77be3.png)

**Comment by vpenades** [comment]
I undertand you can reshape the model to change the size of the input window, but the input window will still remain fixed afterwards?

Anyway, I'm not in a hurry, resizing to 480x640 is giving me good results already, I just wanted to give a try to the dynamic model and see if I was doing something wrong.

Thanks!
