### ISSUE TITLE
keras-retinanet Tensorflow 2 SavedModel

### ISSUE THREAD

**Issue by metanav** [PINTO0309/PINTO_model_zoo#29]
I could not find keras-retinanet (https://github.com/fizyr/keras-retinanet)    *.pb (TF2 SavedModel) in your repository. 
Here is a trained model if you would like to try: 
https://github.com/fizyr/keras-retinanet/releases/download/0.5.1/resnet50_coco_best_v2.1.0.h5

**Comment by PINTO0309** [comment]
Thank you very much for your patience. I've converted it and committed it.
**https://github.com/PINTO0309/PINTO_model_zoo/tree/main/058_keras-retinanet**
