### ISSUE TITLE
download.sh not Working 

### ISSUE THREAD

**Issue by Deepakpy** [PINTO0309/PINTO_model_zoo#290]
### Issue Type

Bug

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

TensorFlowLite

### Model name and Weights/Checkpoints URL

https://github.com/PINTO0309/PINTO_model_zoo/tree/main/033_Hand_Detection_and_Tracking

### Description

![IMG_20220905_230444](https://user-images.githubusercontent.com/18442791/188512491-c75bd1b4-b221-43d3-8184-f30466f4a397.jpg)

download.sh returns a html file instead of tat file.

### Relevant Log Output

```shell
resources.tar.gz: HTML document, ASCII text, with very long lines
```

**Comment by PINTO0309** [comment]
Also, it appears that Google Drive's specifications have changed and it is no longer possible to download files via curl. The specifications of Google Drive change about once every three months, and it is becoming more and more tedious.

I may close the Google Drive of this repository model in the near future as the same issues are posted over and over again. 
![image](https://user-images.githubusercontent.com/33194443/188521010-e2037279-fb1e-473d-978d-4ca1742f5cb9.png)

- Workaround
  1. gdown
    ```bash
    ### e.g.
    gdown --id 1ve-bkElmfNra_-EYGUWrQStSQBoXWfWD
    ```
  2. Type the URL directly into the browser
    ```
    https://drive.google.com/uc?export=download&id=1ve-bkElmfNra_-EYGUWrQStSQBoXWfWD
    ```
