### ISSUE TITLE
palm detection using model_full_integer_quant.tflite model from 21_new_full_lite

### ISSUE THREAD

**Issue by nyadla-sys** [PINTO0309/PINTO_model_zoo#292]
### Issue Type

Support

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

TensorFlowLite

### Model name and Weights/Checkpoints URL

https://colab.research.google.com/github/usefulsensors/gesture_recognition/blob/main/Palm_Detection_int8_model_and_Tracking.ipynb

### Description

Please help me how to do post process on this int8 quantized palm detection model

### URL or source code for simple inference testing code

https://colab.research.google.com/github/usefulsensors/gesture_recognition/blob/main/Palm_Detection_int8_model_and_Tracking.ipynb

**Comment by nyadla-sys** [comment]
I used below int8 tflite model to run inference and please help me to perform post process to detect rectangle on hand pose
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/033_Hand_Detection_and_Tracking/21_new_full_lite

**Comment by PINTO0309** [comment]
It is explicitly stated here.
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/033_Hand_Detection_and_Tracking#note

- code sample.1
https://github.com/Kazuhito00/hand-gesture-recognition-using-mediapipe
- code sample.2
https://github.com/PINTO0309/hand-gesture-recognition-using-onnx
