### ISSUE TITLE
Can't not download content when run download.sh

### ISSUE THREAD

**Issue by Hiuming** [PINTO0309/PINTO_model_zoo#293]
### Issue Type

Bug

### OS

Mac OS

### OS architecture

x86_64

### Programming Language

Python

### Framework

TensorFlowLite

### Model name and Weights/Checkpoints URL

https://github.com/PINTO0309/PINTO_model_zoo/tree/main/276_HybridNets

### Description

Cant not download content from download.sh

### Relevant Log Output

```shell
❯ bash download.sh
grep: invalid option -- P
usage: grep [-abcdDEFGHhIiJLlMmnOopqRSsUVvwXxZz] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2272    0  2272    0     0   4546      0 --:--:-- --:--:-- --:--:--  4646
tar: Error opening archive: Unrecognized archive format
Download finished.
```

### URL or source code for simple inference testing code

bash download.sh

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/PINTO_model_zoo/issues?q=label%3Adownload+is%3Aclosed
