### ISSUE TITLE
Download 269_Higher-HRNet  and unzip failed.

### ISSUE THREAD

**Issue by mch0dmin** [PINTO0309/PINTO_model_zoo#294]
### Issue Type

Bug

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Other

### Framework

Other

### Model name and Weights/Checkpoints URL

269_Higher-HRNet

### Description

Download model failed.

### Relevant Log Output

```shell
-> bash download.sh 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1993    0  1993    0     0   1728      0 --:--:--  0:00:01 --:--:--  1728

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Download finished.

Can download but can not unzip.
```

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/PINTO_model_zoo/issues?q=label%3Adownload+is%3Aclosed

![image](https://user-images.githubusercontent.com/33194443/191697005-4abd7aa3-39f1-4f62-9e8e-5969dfa66ee5.png)
