### ISSUE TITLE
Mobilenet V3 + SSD

### ISSUE THREAD

**Issue by m-parchami** [PINTO0309/PINTO_model_zoo#30]
Hey there,
First of all, thank you for sharing your work.

I'm trying to train MobilenetV3_SSD on my own dataset and then get the tflite.
However, I cannot use TF Object Detection API for quantization aware training.
Seems like there are some issues with their published checkpoints.
I found people having the same problem on Github. [here](https://github.com/tensorflow/models/issues/8331) and [here](https://github.com/tensorflow/models/issues/7720).

However, it looks like you were able to fix it. May I ask what method or modification did you use?

Thank you in advance.

**Comment by PINTO0309** [comment]
I did not do "quantization-aware training". I just did a "Post-Training Quantization".
