### ISSUE TITLE
GLPdepth conversion code.

### ISSUE THREAD

**Issue by ashank-art** [PINTO0309/PINTO_model_zoo#300]
### Issue Type

Support, Feature Request

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

PyTorch, ONNX

### Model name and Weights/Checkpoints URL

https://github.com/PINTO0309/PINTO_model_zoo/tree/main/245_GLPDepth

### Description

Hi thank you for the great work.
The GLP depth model given in the repository is working fine but when i converted the GLP depth pytorch model to onnx using my code, the Onnx inference is not possible in cpp.
below is the script i used for conversting Pytorch glpdepth to onnx model.

    model = GLPDepth(max_depth=max_depth, is_train=False).to(device)

    model_weight = torch.load(ckpt_dir)
    if 'module' in next(iter(model_weight.items()))[0]:
        model_weight = OrderedDict((k[7:], v) for k, v in model_weight.items())
    model.load_state_dict(model_weight)

    model.eval() 

    dummy_input = torch.randn(1, 3, 736 ,1280).to(device) 

    # Export the model   
    torch.onnx.export(model,         # model being run 
         dummy_input,       # model input (or a tuple for multiple inputs) 
         "Depth_estimation_glp_736_1280_max_depth_200.onnx",       # where to save the model  
         export_params=True,  # store the trained parameter weights inside the model file 
         opset_version=11,    # the ONNX version to export the model to 
         do_constant_folding=True,  # whether to execute constant folding for optimization 
         input_names = ['encoder.patch_embed1.proj.weight'],   # the model's input names 
         output_names = ['last_layer_depth.2.bias'], # the model's output names 
         dynamic_axes={'encoder.patch_embed1.proj.weight' : {0 : 'batch_size'},    # variable length axes 
                                'last_layer_depth.2.bias' : {0 : 'batch_size'}}) 

Can u check the code is it okay. or else can u share the code which u have used to convert from pytorch to onnx?

**Comment by PINTO0309** [comment]
Unfortunately, models converted nearly a year ago have lost all conversion codes from that time. I am deleting them within a few months because the resources are straining storage.

Good luck.

**Comment by ashank-art** [comment]
Thank you. Is it possible to share any sample conversion code you have?
