### ISSUE TITLE
115 MoveNet keypoints bug

### ISSUE THREAD

**Issue by vpenades** [PINTO0309/PINTO_model_zoo#303]
### Issue Type

Bug

### OS

Windows

### OS architecture

x86_64

### Programming Language

Other

### Framework

ONNX

### Model name and Weights/Checkpoints URL

115 MoveNet Thunder single person

### Description

I've been trying to use the MoveNet models and I've been getting some odd results when using the models.

At first I thought it was a misconfiguration in my code, but then I tried with MoveNet from another source and it worked correctly.

The problem is that keypoints are off by a few pixels.

I have also tried yout movenet lightning and it seems it's working fine. I haven't tried the multipose model yet.

These are the keypoints delivered by movenet thunder downloaded from your repo:

![result_Pinto](https://user-images.githubusercontent.com/5433822/196349450-9320701f-e805-4fb4-b2c1-7343cfd83045.jpg)

And these are the keypoints from another movenet thunder onnx (using exact same code)

![result_AIlia](https://user-images.githubusercontent.com/5433822/196349546-969d2237-7b4c-4583-b42b-c913ef5712c9.jpg)

I downloaded the alternate model from here:

https://github.com/axinc-ai/ailia-models

[thunder](https://storage.googleapis.com/ailia-models/movenet/movenet_thunder.onnx)
[lightning](https://storage.googleapis.com/ailia-models/movenet/movenet_lightning.onnx)

**Comment by PINTO0309** [comment]
[model.onnx.zip](https://github.com/PINTO0309/PINTO_model_zoo/files/9807699/model.onnx.zip)
![image](https://user-images.githubusercontent.com/33194443/196367570-bd2174a3-c62e-4557-9048-bc32015c86dc.png)
