### ISSUE TITLE
where is the anchor file or generated code?

### ISSUE THREAD

**Issue by lvZic** [PINTO0309/PINTO_model_zoo#304]
### Issue Type

Support

### OS

Windows, Mac OS

### OS architecture

aarch64

### Programming Language

C++

### Framework

ONNX

### Model name and Weights/Checkpoints URL

palm_detection_inf_post_128x128.onnx

### Description

i test your palm_detect_top2_post.onnx model, and found that result seems worse on mobile device than PC platform. so i want to test the palm_detect_inf.onnx, and do prostprocessing myself. However i cant find the anchor file (1 x 2016 size).

**Comment by PINTO0309** [comment]
1. I don't know exactly which file you are referring to since the file `palm_detect_inf.onnx` does not exist.
2. I am not sure what `anchor` refers to.
3. What does prostprocessing refer to?
4. I don't know what you want to do. If you simply want to adjust the parameters of the NMS, you can do so by following the steps below.
  https://github.com/PINTO0309/PINTO_model_zoo/tree/main/307_YOLOv7/post_process_gen_tools#how-to-change-nms-parameters
5. If you want to change all the processes after Sigmoid, you can use the following tools to break up the model and generate it again by combining the OPs you want.
  https://github.com/PINTO0309/simple-onnx-processing-tools

**Comment by lvZic** [comment]
> 1. I don't know exactly which file you are referring to since the file `palm_detect_inf.onnx` does not exist.
> 2. I am not sure what `anchor` refers to.
> 3. What does `prostprocessing` refer to?
> 4. I don't know what you want to do. If you simply want to adjust the parameters of the NMS, you can do so by following the steps below.
>    https://github.com/PINTO0309/PINTO_model_zoo/tree/main/307_YOLOv7/post_process_gen_tools#how-to-change-nms-parameters
> 5. If you want to change all the processes after Sigmoid, you can use the following tools to break up the model and generate it again by combining the OPs you want.
>    https://github.com/PINTO0309/simple-onnx-processing-tools
> 
> I can only read what you are thinking from the information in the text. Therefore, there is too little information to read your written statement to understand exactly what you want to do.

sorry for my bad description. My problen is i use the palm_detection_lite_top2_post_192x192.mnn and convert it to MNN model in order to use on mobile device. Before that i test the MNN model on the PC platform, and the result seems correct. However, the result on mobile device seems worse than on PC. So i want tot debug where the problem is. I use the palm_detection_lite_192x192.onnx model and found that needs the anchors info to postprocess the output  with sizeof  1x2016x8. But I cannot find the anchor info in your project.

**Comment by lvZic** [comment]
> 1. I don't know exactly which file you are referring to since the file `palm_detect_inf.onnx` does not exist.
> 2. I am not sure what `anchor` refers to.
> 3. What does `prostprocessing` refer to?
> 4. I don't know what you want to do. If you simply want to adjust the parameters of the NMS, you can do so by following the steps below.
>    https://github.com/PINTO0309/PINTO_model_zoo/tree/main/307_YOLOv7/post_process_gen_tools#how-to-change-nms-parameters
> 5. If you want to change all the processes after Sigmoid, you can use the following tools to break up the model and generate it again by combining the OPs you want.
>    https://github.com/PINTO0309/simple-onnx-processing-tools
> 
> I can only read what you are thinking from the information in the text. Therefore, there is too little information to read your written statement to understand exactly what you want to do.

by the way, i test the model from https://github.com/zmurez/MediaPipePyTorch, which has 256x256 input size. the result  is correct on mobile phone. This model use anchor with  size of 2944.

**Comment by PINTO0309** [comment]
Frankly, as long as the same model is used, I don't see any difference in accuracy whether it is run on a mobile phone or a PC.
https://github.com/PINTO0309/hand-gesture-recognition-using-onnx

https://user-images.githubusercontent.com/33194443/196896969-a9bbc274-d963-487b-b590-090b15d5e0c2.mp4

https://github.com/PINTO0309/MoveNet-Python-Example
https://user-images.githubusercontent.com/33194443/196897429-051715b5-a33e-4ad9-8935-6db02080c6c9.mp4

And the anchors are embedded in the model pre-computed from the beginning, which I really dislike about PyTorch's implementation.

**Comment by lvZic** [comment]
> 1. I don't know exactly which file you are referring to since the file `palm_detect_inf.onnx` does not exist.
> 2. I am not sure what `anchor` refers to.
> 3. What does `prostprocessing` refer to?
> 4. I don't know what you want to do. If you simply want to adjust the parameters of the NMS, you can do so by following the steps below.
>    https://github.com/PINTO0309/PINTO_model_zoo/tree/main/307_YOLOv7/post_process_gen_tools#how-to-change-nms-parameters
> 5. If you want to change all the processes after Sigmoid, you can use the following tools to break up the model and generate it again by combining the OPs you want.
>    https://github.com/PINTO0309/simple-onnx-processing-tools
> 
> I can only read what you are thinking from the information in the text. Therefore, there is too little information to read your written statement to understand exactly what you want to do.

 i read the palm_detection_lite_top2_post_192x192.onnx  model structure, found these is no anchor info just NMS process. So the network regress the final image coordinate directly ? what i mean is the output box size and kp0-kp7 are in range[0, 192]? and so does palm_detection_lite_192x192.onnx ?

**Comment by PINTO0309** [comment]
>i read the palm_detection_lite_top2_post_192x192.onnx model structure, found these is no anchor info just NMS process. So the network regress the final image coordinate directly ? what i mean is the output box size and kp0-kp7 are in range[0, 192]? and so does palm_detection_lite_192x192.onnx ?

All cumbersome post-processing is already implemented in ONNX.

- Calc anchor
![image](https://user-images.githubusercontent.com/33194443/196899590-a2d8d138-4c3a-455a-84ef-6dccabd3ada0.png)

- cx, cy, w, h -> x1, y1, x2, y2
![image](https://user-images.githubusercontent.com/33194443/196899167-6ac0f3c8-586a-4385-a183-3f4621024146.png)

-

**Comment by lvZic** [comment]
> 



> Frankly, as long as the same model is used, I don't see any difference in accuracy whether it is run on a mobile phone or a PC. https://github.com/PINTO0309/hand-gesture-recognition-using-onnx
> 
>  189632510-1823cd54-bc36-4889-ac14-adc16deba9b8.1.mp4 
> https://github.com/PINTO0309/MoveNet-Python-Example
> 
>  192566926-30454082-70ed-4f75-8dfd-076f2038a16d.mp4 
> And the anchors are embedded in the model pre-computed from the beginning, which I really dislike about PyTorch's implementation.

thanks for you reply. so the  model output is image coordinate. 
as for my problem., the result on mobile device is not stable. What i mean is the result is correct or not both happens. I thought maybe because of the anchor process or NMS  process in ONNX model before. In fact, in my opinion, the result should be same on PC and mobile device, because both use the same processsing codel and converted MNN model.
by the way, hand_landmark_lite_1x3x224x224.onnx works well on mobile device.
