### ISSUE TITLE
242-robustVideoMatting sh file don't work Sivass

### ISSUE THREAD

**Issue by telestia** [PINTO0309/PINTO_model_zoo#311]
### Issue Type

Bug

### OS

Mac OS

### OS architecture

x86_64

### Programming Language

Other

### Framework

Other

### Model name and Weights/Checkpoints URL

242_RobustVideoMatting

### Description

242_RobustVideoMatting sh file is not working

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/PINTO_model_zoo/issues?q=is%3Aissue+is%3Aclosed+label%3Adownload
