### ISSUE TITLE
Movenet GPU not working on android

### ISSUE THREAD

**Issue by madhavarora2002** [PINTO0309/PINTO_model_zoo#313]
### Issue Type

Bug

### OS

Other

### OS architecture

x86_64

### Programming Language

Python

### Framework

TensorFlowLite

### Model name and Weights/Checkpoints URL

MoveNet Lightning. https://github.com/tensorflow/examples/tree/master/lite/examples/pose_estimation/android 

### Description

Movenet Gpu dosn't work on android.
Have been struggling with this for the past couple of days. 
It gives 20fps on phone instead of 50.
Do you have any info on this?

**Comment by PINTO0309** [comment]
I am not a handyman. Ask Google's super engineers.
Please do not post content that is not related to this repository.
