### ISSUE TITLE
206_Matting: update to PP-MattingV2

### ISSUE THREAD

**Issue by simonbunge** [PINTO0309/PINTO_model_zoo#321]
### Issue Type

Feature Request

### OS

Other

### OS architecture

Other

### Programming Language

Other

### Framework

Other

### Model name and Weights/Checkpoints URL

https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.7/Matting

### Description

Please update to PP-MattingV2[](https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.7/Matting) as part of the v2.7 PaddleSeg release since there have been significant improvements over MODNet. Thanks!

**Comment by PINTO0309** [comment]
config does not exist anywhere.https://github.com/PINTO0309/PINTO_model_zoo/tree/main/343_PP-MattingV2
