### ISSUE TITLE
228_Fast-SCNN/resources.tar.gz is not FastSCNN, but 229_DexiNed

### ISSUE THREAD

**Issue by naruai** [PINTO0309/PINTO_model_zoo#326]
### Issue Type

Bug

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Other

### Framework

Other

### Model name and Weights/Checkpoints URL

228_Fast-SCNN
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/228_Fast-SCNN
https://s3.ap-northeast-2.wasabisys.com/pinto-model-zoo/228_Fast-SCNN/resources.tar.gz

### Description

https://github.com/PINTO0309/PINTO_model_zoo/blob/main/228_Fast-SCNN/download.sh
in this file:
curl "https://s3.ap-northeast-2.wasabisys.com/pinto-model-zoo/228_Fast-SCNN/resources.tar.gz" -o resources.tar.gz
but
the 228_Fast-SCNN/resources.tar.gz is not for 228_Fast-SCNN
the file seems for 229_DexiNed

**Comment by PINTO0309** [comment]
https://s3.ap-northeast-2.wasabisys.com/pinto-model-zoo/228_Fast-SCNN/resources.tar.gz

**Comment by naruai** [comment]
thank you for quick fix!
