### ISSUE TITLE
Can't find Zero-DCE onnx models

### ISSUE THREAD

**Issue by MariasStory** [PINTO0309/PINTO_model_zoo#327]
### Issue Type

Bug

### OS

Other

### OS architecture

Other

### Programming Language

Other

### Framework

ONNX

### Model name and Weights/Checkpoints URL

243_Zero-DCE-improved

### Description

After download, I can't find the zero_dce_improved_480x640.onnx or another onnx file except of finnger_96x96.onnx
It seems that the data is uploaded to wasabisys server, but something is missing.

**Comment by PINTO0309** [comment]
https://s3.ap-northeast-2.wasabisys.com/pinto-model-zoo/243_Zero-DCE-improved/resources.tar.gz

**Comment by MariasStory** [comment]
Thank you, works as expected.
