### ISSUE TITLE
033_Hand_Detection_and_Tracking : handedness ?

### ISSUE THREAD

**Issue by geaxgx** [PINTO0309/PINTO_model_zoo#33]
Congratulations and thank you for the great job you are doing !

I have downloaded the Openvino models from your repository (https://github.com/PINTO0309/PINTO_model_zoo/blob/master/033_Hand_Detection_and_Tracking/07_openvino/download.sh), and  I am writing some python code to use them with Openvino.
Palm detection model is working fine. But for the hand landmarks model, I don't find the handedness output described in the google paper MediaPipe Hands: On-device Real-time Hand Tracking (https://arxiv.org/pdf/2006.10214.pdf). 
When I use Netron on the current model from mediapipe repo (https://github.com/google/mediapipe/blob/master/mediapipe/models/hand_landmark.tflite), I can see the output named 'output_handedness', which does not exist in the model from your repo.
Is it because google published several versions of this model and you are using an older version ?
If yes, do you know if the improvements in the last version are worth using it and if you plan to convert it ?

Thanks !

**Comment by PINTO0309** [comment]
My model was converted from a .tflite model that I got from the MediaPipe repository 4 months ago. It looks like the shape of the output is different from the latest model. Once I've finished implementing the Python sample program for BlazePose Full Body, I'll try out the conversion on the latest model. Please be patient.

## Modeled 4 months ago (no quantization)
https://github.com/google/mediapipe/blob/c27a7c1e1064e66427ad0656f776155ab456f90b/mediapipe/models/hand_landmark_3d.tflite
![Screenshot 2020-09-17 00:11:51](https://user-images.githubusercontent.com/33194443/93356783-9653e300-f87a-11ea-8acc-a5aa929c4315.png)
## Latest model (Float16 quantized)
https://github.com/google/mediapipe/blob/master/mediapipe/models/hand_landmark.tflite
![Screenshot 2020-09-17 00:12:24](https://user-images.githubusercontent.com/33194443/93356874-acfa3a00-f87a-11ea-9dd6-1ef4c04950db.png)

**Comment by geaxgx** [comment]
Thank you for your fast reply ! Sure, I will wait. 
By the way, I am also interested in your work on Blazepose in order to use it on OAKD ;-)

**Comment by PINTO0309** [comment]
I'm being monitored by the developers of OAK-D, so maybe it will be released soon. (Just a guess.)

**Comment by geaxgx** [comment]
It is the OAK-D developpers team who gave me your github link ! I think they are already using your work for pose estimation (007_mobilenetv2-poseestimation). But Blazepose seems more accurate, that's why I will probably try to use it ! Thx !

**Comment by PINTO0309** [comment]
I have added the latest model that can distinguish between right and left hands.
**https://github.com/PINTO0309/PINTO_model_zoo/tree/master/033_Hand_Detection_and_Tracking**

**Comment by geaxgx** [comment]
Thank you for your effort @PINTO0309 ! 
I have downloaded your latest model (openvino version) and adapted my script a bit to take into account that now the network have 3 outputs :
Output blob: StatefulPartitionedCall/functional_1/tf_op_layer_Sigmoid/Sigmoid - shape: [1, 1, 1, 1]
Output blob: StatefulPartitionedCall/functional_1/tf_op_layer_Sigmoid_1/Sigmoid_1 - shape: [1, 1, 1, 1]
Output blob: StatefulPartitionedCall/functional_1/tf_op_layer_ld_21_3d/ld_21_3d - shape: [1, 63]
I don't know yet which output is the score and which output is the handedness, but a least, it is clear that the 3rd output corresponds to the landmarks.
I suppose that the processing to display the landmarks is the same for the previous and new model (am I worong ?).
Unfortunately the landmarks don't seem correct :
![new_model](https://user-images.githubusercontent.com/28948232/93865644-e392e300-fcc6-11ea-90fe-003661d3d83f.png)

This what I get with the older model:
![old_model](https://user-images.githubusercontent.com/28948232/93865960-5734f000-fcc7-11ea-910d-554afaf04f6b.png)

Do you have an idea on what could be wrong ?

**Comment by PINTO0309** [comment]
I'll check the certainty of the model's construction once. Please wait.

**Comment by PINTO0309** [comment]
@geaxgx 
I'm sorry. I found a total of 4 mistakes. I'm going to re-convert and commit immediately after this.
1. remove the useless activation function given to Conv2D
2. wrongly set weights

**Comment by PINTO0309** [comment]
@geaxgx
Errors have been corrected and the model has been re-registered. The URL for download has not changed, please download it again and try again. If you'll allow me, I'd be very happy to share the results with you.

**Comment by geaxgx** [comment]
Thank you for you quick action @PINTO0309 ! I admire your job, I am totally unable to do the work you are doing !
The result is clearly better, not yet perfect : 
![new_model_2](https://user-images.githubusercontent.com/28948232/93877125-3a54e880-fcd8-11ea-8e40-3985b1302e61.png)
Note also the outputs for score and handedness (0.999 and 0.953) seems reasonable values.
I have to check the mediapipe github to see if the problem can is on my side and also to know how to interpret the handedness value. 

Yes, you can share the results, of course.

**Comment by geaxgx** [comment]
Instead of checking the mediapipe github to check if the interpretation of model outputs has changed between the old version and new version of the model, I have found it was easier to adapt my script to run directly with the tflite models (instead of openvino models).
So on one side, I use the latest tflite model from Mediapipe (this file: https://github.com/google/mediapipe/blob/master/mediapipe/models/hand_landmark.tflite). The result is correct : 
![mediapipe_tflite](https://user-images.githubusercontent.com/28948232/93898924-11425100-fcf4-11ea-9b0c-b17da814c702.png)

On the other side, I use the model hand_landmark_new_256x256_float32.tflite downloaded with https://github.com/PINTO0309/PINTO_model_zoo/blob/master/033_Hand_Detection_and_Tracking/01_float32/download_new.sh. I get a result very similar to what I got with the Openvino model:
![pinto_tflite](https://user-images.githubusercontent.com/28948232/93899596-c2e18200-fcf4-11ea-89b5-e27e1896ac59.png)

I guess some information is lost/corrupted during the conversion. What do you think @PINTO0309 ?

About the handedness output, according to the mediapipe github, the value given by the model is the probability for the hand to be a left hand. But according to my test, it seems to be the exact opposite (probability to be a right hand) :-) I am not the first one to notice this inversion : https://dev.classmethod.jp/articles/mediapipe-extract-handedness/

**Comment by PINTO0309** [comment]
Thank you for providing the information. It looks like there is still a problem with how to make the model. I am converting the original 16-bit float quantized model straight, but some intermediate processing may be required. It is correct to doubt the model that the test code used is the same but the results are quite different.

I will consider the cause and countermeasures for a while.

**Comment by geaxgx** [comment]
Converting the new model seems challenging ! 
The question is: is it worth to put much effort in that task ?

Well, I don't know. It is up to you. The older model you converted is already very good and satisfying for me.
But from the few tests I have done, the new model seems more accurate. For instance, on  the picture below (left image is with your older tflite model, right image is with original mediapipe last tflite model), we can see that the finger tips are more accurate :
![cmp](https://user-images.githubusercontent.com/28948232/93984332-f4555e80-fd83-11ea-8749-fee0a081b982.png)
About handedness, I imagine some applications where it can be useful, but I also have noticed it is not 100% accurate.

**Comment by PINTO0309** [comment]
What I'm a little worried about is whether there is a difference between the results of my float16 quantized model and the official float16 quantized model. I haven't come home yet so I haven't been able to confirm it in detail, but it's very strange because the weights of the first layer appear to be converted correctly.

https://github.com/PINTO0309/PINTO_model_zoo/tree/master/033_Hand_Detection_and_Tracking/04_float16_quantization

**Comment by PINTO0309** [comment]
What I'm a little worried about is whether there is a difference between the results of my float16 quantized model and the official float16 quantized model. I haven't come home yet so I haven't been able to confirm it in detail, but it's very strange because the weights of the first layer appear to be converted correctly.

https://github.com/PINTO0309/PINTO_model_zoo/tree/master/033_Hand_Detection_and_Tracking/04_float16_quantization

official
![Screenshot_20200923-211742](https://user-images.githubusercontent.com/33194443/94011696-bb98a200-fde2-11ea-827c-a58bac4804d6.png)

mine
![Screenshot_20200923-211820](https://user-images.githubusercontent.com/33194443/94011718-c5baa080-fde2-11ea-9196-3d9a51e3082b.png)

**Comment by PINTO0309** [comment]
I built a sample app for the MediaPipe desktop, imported my own Float16 model and ran it. It still appears to be an error in my model structure. The expectation is to get exactly the same result, but it didn't work out that way. It is difficult to find enough time to work on the model during the weekdays, so we will check the structure of the model again this weekend.
![Screenshot 2020-09-23 22:40:58](https://user-images.githubusercontent.com/33194443/94020504-f227ea00-fded-11ea-8cdf-a743f0f78a14.png)

**Comment by PINTO0309** [comment]
I have identified the problem areas. We'll run the conversion again and recommit.
![Screenshot 2020-09-23 23:21:34](https://user-images.githubusercontent.com/33194443/94025548-94969c00-fdf3-11ea-94f0-07ceb2acd6a0.png)

**Comment by PINTO0309** [comment]
I have updated all committed models again. As you can see in the picture above, I'm sure it will be detected correctly this time.
Try downloading the model again.

**Comment by geaxgx** [comment]
Fantastic job @PINTO0309 ! Ah ah you couldn't wait for the weekend, could you ?
Thank you very much !
