### ISSUE TITLE
Training a new model

### ISSUE THREAD

**Issue by t109368507** [PINTO0309/PINTO_model_zoo#331]
### Issue Type

Support

### OS

Ubuntu

### OS architecture

aarch64

### Programming Language

Python

### Framework

TensorFlowLite

### Model name and Weights/Checkpoints URL

New training:MobileNetV3+DeeplabV3+PascalVOC
Pretraining model: deeplabv3_mnv2_pascal_train_aug_2018_01_29.tar.gz

### Description

env: Tensorflow:1.15.3

Using the pre-trained model in the website "deeplabv3_mnv2_pascal_train_aug_2018_01_29.tar.gz", adding metadata can run on the android platform, but using the following command to train a new model can not be inferred to the object normally, it is always inferred to the background, is there any need to modify ?

```
$ python3 deeplab/train.py \
    --logtostderr \
    --training_number_of_steps=500000 \
    --train_split="train" \
    --model_variant="mobilenet_v3_small_seg" \
    --decoder_output_stride=16 \
    --train_crop_size="513,513" \
    --train_batch_size=8 \
    --dataset="pascal_voc_seg" \
    --save_interval_secs=300 \
    --save_summaries_secs=300 \
    --save_summaries_images=True \
    --log_steps=100 \
    --train_logdir=${PATH_TO_TRAIN_DIR} \
    --dataset_dir=${PATH_TO_DATASET}
```

Thanks!

**Comment by PINTO0309** [comment]
If you have questions that are not related to the content of this repository, you can ask them here in the community.
https://discuss.tensorflow.org/

**Comment by t109368507** [comment]
Okay! Thanks!
