### ISSUE TITLE
The files under "01_mobilenetv3_small/01_pascalvoc" are empty,

### ISSUE THREAD

**Issue by t109368507** [PINTO0309/PINTO_model_zoo#332]
### Issue Type

Documentation Feature Request

### OS

Ubuntu

### OS architecture

aarch64

### Programming Language

Python

### Framework

TensorFlowLite

### Model name and Weights/Checkpoints URL

01_mobilenetv3_small/01_pascalvoc

### Description

Hi,
Download the files via "https://github.com/PINTO0309/PINTO_model_zoo/blob/main/001_deeplabv3/download.sh".
The files under "01_mobilenetv3_small/01_pascalvoc" are empty except "01_float32" , could you please provider the files or how to generate the other?

01_mobilenetv3_small/01_pascalvoc/02_quantization-aware/
01_mobilenetv3_small/01_pascalvoc/03_export_model/
01_mobilenetv3_small/01_pascalvoc/04_tflite/

Thanks!
B&R.

**Comment by t109368507** [comment]
Is the export script command correct?
```
python deeplab/export_model.py \
--model_variant="mobilenet_v3_small_seg" \
--crop_size=257 \
--crop_size=257 \
--checkpoint_path=./01_float32/model.ckpt-500000 \
--export_path=./01_float32/frozen_inference_graph.pb
```

**Comment by PINTO0309** [comment]
I seem to have deleted a model I committed to 4 years ago in the process of a recent storage migration. At this point, it would be much faster to download the various processed models from TFHub.

https://tfhub.dev/s?q=deeplabv3
