### ISSUE TITLE
Documentation support for Crestereo Pytorch model conversion to onnx model

### ISSUE THREAD

**Issue by ashank-art** [PINTO0309/PINTO_model_zoo#335]
### Issue Type

Support

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

PyTorch, ONNX

### Model name and Weights/Checkpoints URL

https://github.com/PINTO0309/PINTO_model_zoo/tree/main/284_CREStereo

### Description

Hi, Thank you for your great work.

Can you guide me through the procedure for converting CreStereo PyTorch model to Onnx model.?
As per the documents, it says 
You need to convert the model twice, once without the init_flow and once with the init_flow. So the commented out part in your [script](https://github.com/ibaiGorordo/CREStereo-Pytorch/blob/main/convert_to_onnx.py) are not options, but two separate runs.
Then use the [merging tool](https://github.com/PINTO0309/PINTO_model_zoo/blob/main/284_CREStereo/onnx_merge.py) PINTO0309 developed to merge the two parts into one. Or, just use them separately in sequence.

But in the second step while using onnx_merge.py , 

i am facing the issue attached in the below error log

### Relevant Log Output

```shell
Traceback (most recent call last):
  File "onnx_merge.py", line 17, in <module>
    combined_model = onnx.compose.merge_models(
  File "/home/virtual_environments/cre_pytorch/lib/python3.8/site-packages/onnx/compose.py", line 363, in merge_models
    graph = merge_graphs(
  File "/home/virtual_environments/cre_pytorch/lib/python3.8/site-packages/onnx/compose.py", line 187, in merge_graphs
    raise ValueError(f"Input {g2_in_name} is not present in g2")
ValueError: Input next_flow_init is not present in g2
```

**Comment by PINTO0309** [comment]
No special knowledge is required.

https://github.com/PINTO0309/PINTO_model_zoo/blob/046e5f1627ab7f3aeb4a38ddde79699c1880670f/284_CREStereo/onnx_merge.py#L55-L58

Simply follow the process as described in the official ONNX documentation.

https://onnx.ai/onnx/api/compose.html
