### ISSUE TITLE
CreStereo onnx model conversion to tensorrt version

### ISSUE THREAD

**Issue by waveajay** [PINTO0309/PINTO_model_zoo#347]
### Issue Type

Support, Documentation Feature Request

### OS

Windows, Ubuntu

### OS architecture

x86_64

### Programming Language

C++, Python

### Framework

ONNX, TensorRT

### Model name and Weights/Checkpoints URL

https://github.com/PINTO0309/PINTO_model_zoo/tree/main/284_CREStereo

### Description

In the repository i could see two version of onnx i,e normal onnx and tensorrt version that is also onnx.
Can you provide the script/proceudre for converting normal onnx to tenssort.onnx

**Comment by PINTO0309** [comment]
TensorRT does not accept 3 inputs for `Einsum`, so add another `Einsum` before `Einsum` with 3 inputs. Unfortunately, I have not kept any past resources on hand for more than a year. Good luck.

https://github.com/ibaiGorordo/CREStereo-Pytorch

![image](https://github.com/PINTO0309/PINTO_model_zoo/assets/33194443/bb1ec90d-bb87-4022-9a13-5a76bc452cf2)

**Comment by ghylh** [comment]
In linear_attention.py, we can use
```
queries_mid_values = torch.einsum("nlhd,nhdv->nlhv", Q, KV)
queried_values = torch.einsum("nlhv,nlh->nlhv", queries_mid_values, Z) * v_length
```
instead of  
```
queried_values = torch.einsum("nlhd,nhdv,nlh->nlhv", Q, KV, Z) * v_length
```
Then convert model from pytorch to onnx, and you will get tensorrt version.
