### ISSUE TITLE
Demo code for BlendshapeV2 3D avatar

### ISSUE THREAD

**Issue by royshil** [PINTO0309/PINTO_model_zoo#348]
### Issue Type

Documentation Feature Request

### OS

Windows

### OS architecture

x86_64

### Programming Language

C++, Python

### Framework

ONNX

### Model name and Weights/Checkpoints URL

Model name: BlendshapeV2

### Description

Thanks for adding BlendshapeV2!

You have a demo of adding the 3D face using the landmarks from the model, I wonder if you can share that demo code? 🙏

**Comment by PINTO0309** [comment]
I only extracted and converted the models from this repository from which they were cited. Therefore, I have not written any code to render it, so I have nothing to share. Hopefully, you can parse MediaPipe's ultra-obscure source code, and I would love to see you issue a pull request to this repository.

https://developers.google.com/mediapipe/solutions/vision/face_landmarker
