### ISSUE TITLE
The TensorFlow models download by download_iter02_tensorrt.sh are actually ONNX models

### ISSUE THREAD

**Issue by daviszhu88** [PINTO0309/PINTO_model_zoo#351]
### Issue Type

Bug

### OS

Windows

### OS architecture

x86_64

### Programming Language

C++

### Framework

TensorFlow

### Model name and Weights/Checkpoints URL

https://github.com/PINTO0309/PINTO_model_zoo/tree/main/284_CREStereo

### Description

The model files are actually ONNX files. Could you have it fixed as soon as possible? Thanks and I really appreciate it.

**Comment by PINTO0309** [comment]
```
onnx2tf -i xxxx.onnx -osd -cotof
```

**Comment by daviszhu88** [comment]
Thanks for your quick response. I tried to use your tool to do the
conversion but had problems (see the below). Does the tool require Python
3.10? I have Python 3.11. I am retrying with the command you provided.


(CREStereo_ONNX) C:\Hongwei\DeepLearning\onnx2tf>onnx2tf -i
crestereo_init_iter20_720x1280.onnx


File
"C:\Users\davis\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\framework\importer.py",
line 515, in _import_graph_def_internal

    raise ValueError(str(e))

ValueError: Invalid GraphDef


Also, I noticed that the ONNX files have different names. Do you convert
the MegEgnine model to ONNX, or convert from the PyTorch model to ONNX?
How can I specify the iteration number and image size during the conversion?

Still, if you do have the TensorFlow models already converted, it might be
more convenient for me to just get the models from you, just like the ONNX
files.


Do you ever tried to use those models in C++?


Thanks and I really appreciate your time and kind help.


Hongwei


ESRI (www.esri.com), California, USA

**Comment by daviszhu88** [comment]
> onnx2tf -i xxxx.onnx -osd -cotof

Took very long time (>1 hour) and get an error:

(CREStereo_ONNX) C:\Hongwei\DeepLearning\onnx2tf>onnx2tf -i crestereo_init_iter20_720x1280.onnx -osd -cotof

  File "C:\Users\davis\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\framework\importer.py", line 515, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Invalid GraphDef
