### ISSUE TITLE
RoI Tanh-polar Transformer Network for Face Parsing ONNX conversion

### ISSUE THREAD

**Issue by harisreedhar** [PINTO0309/PINTO_model_zoo#353]
### Issue Type

Feature Request

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

ONNX

### Model name and Weights/Checkpoints URL

[rtnet50-fcn-11.torch](https://ibug.doc.ic.ac.uk/download/rtnet/rtnet50-fcn-11.torch)
[rtnet50-fcn-14.torch](https://ibug.doc.ic.ac.uk/download/rtnet/rtnet50-fcn-14.torch)
[rtnet101-fcn-14.torch](https://ibug.doc.ic.ac.uk/download/rtnet/rtnet101-fcn-14.torch)
[resnet50-fcn-14.torch](https://ibug.doc.ic.ac.uk/download/rtnet/resnet50-fcn-14.torch)
[deeplabv3plus-14.torch](https://ibug.doc.ic.ac.uk/download/rtnet/resnet50-deeplabv3plus-14.torch)

### Description

Would be nice to port this pytorch [Face-Parsing Model](https://github.com/hhj1897/face_parsing) to modelzoo as onnx.

### URL or source code for simple inference testing code

https://github.com/hhj1897/face_parsing/blob/master/ibug/face_parsing/parser.py

**Comment by PINTO0309** [comment]
WIP

https://github.com/PINTO0309/face_parsing
![image](https://github.com/PINTO0309/PINTO_model_zoo/assets/33194443/1ffbc7da-9c1b-4753-88a7-4598694aa50e)

**Comment by PINTO0309** [comment]
Tanh-polar is quite difficult to convert to ONNX; many operations cannot be exported to ONNX. It is very easy to convert the part except for tanh-polar.

**Comment by harisreedhar** [comment]
Ok. Thanks for trying

**Comment by ykk648** [comment]
Hi, are there any new possibilities to transform the tanh-polar op after one year?
