### ISSUE TITLE
different results for similar models

### ISSUE THREAD

**Issue by WISNI4** [PINTO0309/PINTO_model_zoo#354]
### Issue Type

Bug

### OS

Other

### OS architecture

Other

### Programming Language

Other

### Framework

Other

### Model name and Weights/Checkpoints URL

https://github.com/PINTO0309/PINTO_model_zoo/tree/main/256_SFace

### Description

inferences obtained for models:
 model_float32.onnx and face_recognition_sface_2021dec_org.onnx are different

**Comment by PINTO0309** [comment]
https://s3.ap-northeast-2.wasabisys.com/pinto-model-zoo/256_SFace/resources.tar.gz
