### ISSUE TITLE
[252_RAFT] What's the difference between iter10 and iter20?

### ISSUE THREAD

**Issue by ykk648** [PINTO0309/PINTO_model_zoo#359]
### Issue Type

Support

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

ONNX

### Model name and Weights/Checkpoints URL

https://github.com/PINTO0309/PINTO_model_zoo/tree/main/252_RAFT

### Description

[252_RAFT] What's the difference between iter10 and iter20?

**Comment by PINTO0309** [comment]
The number of iterations is different.
