### ISSUE TITLE
The face mesh v2 model download link used in face blendshape

### ISSUE THREAD

**Issue by jeremmoore** [PINTO0309/PINTO_model_zoo#361]
### Issue Type

Support

### OS

Ubuntu, Other

### OS architecture

aarch64

### Programming Language

C++

### Framework

TensorFlowLite

### Model name and Weights/Checkpoints URL

https://github.com/PINTO0309/facemesh_onnx_tensorrt/issues/4

### Description

A demo video is attached in readme. md.  I wonder if is it achieved by the model using blendshape.tflite  and corresponding face mesh v2 model in the repository or just recording using mediapipe web demo?  For now, I cannot download the corresponding face mesh v2 model mentioned in face blendshape model card which outputs 478 landmarks. Only face mesh with 468 landmarks is what I can find now.

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/410_FaceMeshV2
