### ISSUE TITLE
357 unimatch optical low result is not right

### ISSUE THREAD

**Issue by onlyinheaven** [PINTO0309/PINTO_model_zoo#364]
### Issue Type

Support

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

ONNX

### Model name and Weights/Checkpoints URL

https://drive.google.com/drive/folders/1SfdBnOQl51TIzjyg4zSpUejz8oX_0MGI

### Description

I ran the optical flow model gmflow-scale1-mixdata-train320x576-4c3a6e9a_1x3x480x640_sim.onnx but the kitti result seems not right 
![image](https://github.com/PINTO0309/PINTO_model_zoo/assets/29097403/f76cc738-d89d-43d6-9fb8-bc37991c9b50)

### URL or source code for simple inference testing code

I use the demo code in Fateshelled‘s repo. https://github.com/fateshelled/unimatch_onnx/blob/main/demo_flow_onnx.py
The test data is in https://github.com/fateshelled/unimatch_onnx/tree/main/data/flow.

**Comment by PINTO0309** [comment]
Please ask questions in the issue of the repository from which you are quoting.
