### ISSUE TITLE
maxim onnx export

### ISSUE THREAD

**Issue by simplew2011** [PINTO0309/PINTO_model_zoo#369]
### Issue Type

Others

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

ONNX

### Model name and Weights/Checkpoints URL

[maxim](https://github.com/vztu/maxim-pytorch)

### Description

how can you export maxim model in torch to onnx.
![image](https://github.com/PINTO0309/PINTO_model_zoo/assets/66729924/19f943be-e759-445c-8169-7e756d76b810)

**Comment by PINTO0309** [comment]
https://github.com/opencv/opencv_zoo
