### ISSUE TITLE
unauthorized

### ISSUE THREAD

**Issue by chenscottus** [PINTO0309/PINTO_model_zoo#370]
### Issue Type

Support

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

ONNX

### Model name and Weights/Checkpoints URL

Hello,

    https://github.com/PINTO0309/PINTO_model_zoo/blob/main/247_PoseC3D/convert_script.txt
    https://github.com/PINTO0309/mmaction2-onnx-export-env

     When I try to run 
         sudo docker pull ghcr.io/pinto0309/mmaction2onnxexpenv:latest

     I got the error message:
         Error response from daemon: Head "https://ghcr.io/v2/pinto0309/mmaction2onnxexpenv/manifests/latest": unauthorized

     Many thanks!

-Scott

### Description

    https://github.com/PINTO0309/PINTO_model_zoo/blob/main/247_PoseC3D/convert_script.txt
    https://github.com/PINTO0309/mmaction2-onnx-export-env

     When I try to run 
         sudo docker pull ghcr.io/pinto0309/mmaction2onnxexpenv:latest

     I got the error message:
         Error response from daemon: Head "https://ghcr.io/v2/pinto0309/mmaction2onnxexpenv/manifests/latest": unauthorized

### Relevant Log Output

```shell
Error response from daemon: Head "https://ghcr.io/v2/pinto0309/mmaction2onnxexpenv/manifests/latest": unauthorized
```

### URL or source code for simple inference testing code

https://github.com/PINTO0309/mmaction2-onnx-export-env
sudo docker pull ghcr.io/pinto0309/mmaction2onnxexpenv:latest

**Comment by PINTO0309** [comment]
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry
