### ISSUE TITLE
Link is not working for Hitnet

### ISSUE THREAD

**Issue by dhimiterq** [PINTO0309/PINTO_model_zoo#374]
### Issue Type

Documentation Bug

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Other

### Framework

PyTorch

### Model name and Weights/Checkpoints URL

NA

### Description

142_HITNET/download.sh is not working due to invalid link.

### URL or source code for simple inference testing code

https://s3.ap-northeast-2.wasabisys.com/pinto-model-zoo/142_HITNET/resources.tar.gz

**Comment by PINTO0309** [comment]
![image](https://github.com/PINTO0309/PINTO_model_zoo/assets/33194443/100a6eec-bcd2-45f4-9795-6d1075fee2de)
