### ISSUE TITLE
Rapid wrong initial onxx model 

### ISSUE THREAD

**Issue by deepsrm** [PINTO0309/PINTO_model_zoo#375]
### Issue Type

Bug

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

ONNX

### Model name and Weights/Checkpoints URL

Model is 143 RAPiD 

### Description

I was talking to the RAPiD owners ant there was a bug generating the initial onxx model, so all the conversion based on that are wrong. May you download the latest code and generate them again?

Thanks a lot for your effort

**Comment by PINTO0309** [comment]
It's the product of work done years ago. I have no interest in it now. Do it yourself.
