### ISSUE TITLE
Explaination on The YoloX Body-Head-Hand output dimension?

### ISSUE THREAD

**Issue by kho-bluefrogrobotics** [PINTO0309/PINTO_model_zoo#381]
### Issue Type

Documentation Feature Request

### OS

Other

### OS architecture

armv7

### Programming Language

Other

### Framework

TensorFlowLite

### Model name and Weights/Checkpoints URL

YoloX Body-Head-Hand
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/426_YOLOX-Body-Head-Hand

### Description

First of all thanks and congratulation for your excellent work, on YOLO.

I have a question regarding the output size, though.
@PINTO0309 You say you limit the output to 20 boxes : How come we obtain a float32[60,7] output then?
shouldn't we get something like 20x [class, score, x1, y1, x2, y2] = 20 x 5 floats?

**Comment by PINTO0309** [comment]
As detailed in the README.

max output boxes **`per`** class

`20 (Body) + 20 (Head) + 20 (Hand) = 60 boxes`

![image](https://github.com/PINTO0309/PINTO_model_zoo/assets/33194443/de59f338-2479-4348-b02a-c26c5512881d)
