### ISSUE TITLE
ONNX version for person-reidentification-retail-0277

### ISSUE THREAD

**Issue by hyperf0cus** [PINTO0309/PINTO_model_zoo#383]
### Issue Type

Others

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

ONNX

### Model name and Weights/Checkpoints URL

https://storage.openvinotoolkit.org/repositories/open_model_zoo/2023.0/models_bin/1/person-reidentification-retail-0277/

### Description

Inside 083 directory for person-reidentification-retail-0277 there is model_float32.onnx, but I'm not sure is this onnx model is the same as openvino models for 0277, furthermore model_float32.onnx is nwhc as tensorflow, and can't convert it through model_optimizer to compare with models from openvino model zoo for person-reidentification-retail-0277. Do you have onnx model for example person-reidentification-retail-0277.onnx?

**Comment by PINTO0309** [comment]
Not sure what you are talking about, but it is the same model. ONNX channel positions can be rewritten in miscellaneous ways.

![image](https://github.com/PINTO0309/PINTO_model_zoo/assets/33194443/9ac813d9-7214-41ee-af0d-07cc06b3b1b0)

[person-reidentification-retail-0265.onnx.zip](https://github.com/PINTO0309/PINTO_model_zoo/files/13840774/person-reidentification-retail-0265.onnx.zip)

**Comment by hyperf0cus** [comment]
so model_float_32.onnx inside your repo and person-reidentification-retail-0265.onnx supposed to be the same?

**Comment by PINTO0309** [comment]
Strictly speaking, there is no documentation of how Intel generated the ONNX files, so there is no way I can answer that question.

**Comment by hyperf0cus** [comment]
Thank you for answers, and last one, how you get your model_float32.onnx, .pb, tflite etc?
