### ISSUE TITLE
License of RAFT models

### ISSUE THREAD

**Issue by phuelsdunk** [PINTO0309/PINTO_model_zoo#386]
### Issue Type

Support

### OS

Other

### OS architecture

Other

### Programming Language

Other

### Framework

Other

### Model name and Weights/Checkpoints URL

https://github.com/PINTO0309/PINTO_model_zoo/tree/main/252_RAFT

### Description

Under what license are the RAFT models published? There is a LICENSE file, however, since the models are hosted externally it is not clear if this license also applies to them. Could you clarify this?

**Comment by PINTO0309** [comment]
With more than 400 different manual operations, file copying errors and work errors can happen often.
![image](https://github.com/PINTO0309/PINTO_model_zoo/assets/33194443/bc579b42-a411-41a9-b893-cd2e17c97fb6)

**Comment by phuelsdunk** [comment]
Thanks for updating the file. Can you clarify with a yes/no if the LICENSE also applies to the models stored on Wasabi?

**Comment by PINTO0309** [comment]
Yes
