### ISSUE TITLE
How to fold batch norm in Conv2D

### ISSUE THREAD

**Issue by tu1258** [PINTO0309/PINTO_model_zoo#39]
So I would like to fuse batch norm in Conv2D before doing full integer quantization. Is that doable? I've read the article on https://qiita.com/PINTO/items/865250ee23a15339d556 but didn't find the information. Maybe someone here could help me, thanks!

**Comment by PINTO0309** [comment]
It appears to be automatically merged at quantization time.

## Before
![Screenshot_20201012-094538](https://user-images.githubusercontent.com/33194443/95694996-e2265c00-0c6f-11eb-8ef0-5bfb0bd18154.png)

## After
![Screenshot_20201012-094620](https://user-images.githubusercontent.com/33194443/95694998-e5214c80-0c6f-11eb-923a-a430c24f936b.png)

**Comment by tu1258** [comment]
Much thanks to @PINTO0309 !
