### ISSUE TITLE
TOPK operator for RKNN export

### ISSUE THREAD

**Issue by ax-anoop** [PINTO0309/PINTO_model_zoo#390]
### Issue Type

Support

### OS

Ubuntu

### OS architecture

x86_64, aarch64

### Programming Language

Python

### Framework

ONNX

### Model name and Weights/Checkpoints URL

movenet multi

### Description

Is there anyway to swap out the topK operator ? 

![image](https://github.com/PINTO0309/PINTO_model_zoo/assets/95486801/6c7b26db-2836-48f6-906b-d16353d1e84b)

I am trying to export to RKNN; however, this operator doesn't seem to be supported.

**Comment by PINTO0309** [comment]
I am not interested in posts that have nothing to do with this repository.
