### ISSUE TITLE
064_Dense_Depth seems to have wrong dimensions

### ISSUE THREAD

**Issue by seph14** [PINTO0309/PINTO_model_zoo#393]
### Issue Type

Bug

### OS

Mac OS

### OS architecture

aarch64

### Programming Language

C++

### Framework

CoreML

### Model name and Weights/Checkpoints URL

[064_Dense_Depth](https://github.com/PINTO0309/PINTO_model_zoo/tree/main/064_Dense_Depth)

### Description

Original model has a dimension of 640x480, but converted models are 480x640

**Comment by PINTO0309** [comment]
Yes, it is.
