### ISSUE TITLE
Midas2 model on coral edge TPU

### ISSUE THREAD

**Issue by Meleko96** [PINTO0309/PINTO_model_zoo#394]
### Issue Type

Performance

### OS

Ubuntu

### OS architecture

aarch64

### Programming Language

Python

### Framework

TensorFlowLite

### Model name and Weights/Checkpoints URL

https://github.com/PINTO0309/PINTO_model_zoo/tree/main/081_MiDaS_v2

### Description

Hi,
thanks for the great work. 
I tried running the fully quantized integer model on coral edge tpu, however the model's output was inaccurate. 
I am not sure if post quantization training is needed for this model. 
![Screenshot from 2024-02-13 07-42-30](https://github.com/PINTO0309/PINTO_model_zoo/assets/64444088/3d468137-860e-401e-a77d-a4191d30f36a)
I would appreciate your help on this matter

**Comment by PINTO0309** [comment]
The work was done four years ago. I don't remember what the model was. You'll have to work on your own.
