### ISSUE TITLE
Difference on model outputs (tflite, openvino IR, and Onnx) in model 227_face-detection-adas-0001

### ISSUE THREAD

**Issue by saeidn95** [PINTO0309/PINTO_model_zoo#395]
### Issue Type

Feature Request

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

OpenVINO

### Model name and Weights/Checkpoints URL

227_face-detection-adas-0001
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/227_face-detection-adas-0001

### Description

I am looking at the outputs of the 3 versions of the model tflite, onnx and IR openvino. The openvino has 3 outputs and ftlite and onnx each have two outputs. How are they identical to each other?

openvino xlm : [<Output: names[mbox_loc] shape[1,40448] type: f32>, <Output: names[mbox_conf_flatten] shape[1,20224] type: f32>, <Output: names[mbox_priorbox] shape[1,2,40448] type: f32>]

tflite: [<Output: names[StatefulPartitionedCall:0] shape[1,40448] type: f32>, <Output: names[StatefulPartitionedCall:1] shape[1,20224] type: f32>]

onnx: [<Output: names[tf.identity] shape[1,40448] type: f32>, <Output: names[tf.identity_1] shape[1,20224] type: f32>]

### Relevant Log Output

```shell
-
```

### URL or source code for simple inference testing code

-

**Comment by PINTO0309** [comment]
I have answered in the past issue. Search for.
