### ISSUE TITLE
bad results for 342_ALIKE

### ISSUE THREAD

**Issue by mht1421** [PINTO0309/PINTO_model_zoo#397]
### Issue Type

Bug

### OS

Windows

### OS architecture

x86_64

### Programming Language

C++

### Framework

ONNX

### Model name and Weights/Checkpoints URL

alike_t_opset16_480x640.onnx

### Description

I tried to use the model alike_t_opset16_480x640 in C++ but I got bad results. I tried the code in the demo folder in python I got bad results too.

**Comment by PINTO0309** [comment]
I see. That is unfortunate.
