### ISSUE TITLE
Convert tflite with mask rcnn

### ISSUE THREAD

**Issue by hoangtubatu123** [PINTO0309/PINTO_model_zoo#4]
How can you convert to mask rcnn to tflite model. Thanks

**Comment by PINTO0309** [comment]
Here is the script I used for the conversion.
**https://github.com/PINTO0309/PINTO_model_zoo/blob/master/08_mask_rcnn_inceptionv2/01_float32/01_export_inference_graph.txt**

**Comment by hoangtubatu123** [comment]
Thanks. I will try. Have you use model which can be converted from this script =)

**Comment by PINTO0309** [comment]
No, I'm a weird, so I'm just enjoying the conversion for now.

**Comment by hoangtubatu123** [comment]
i see the error "Invalid tensors 'image_tensor' were found." Can you solve it ??

**Comment by hoangtubatu123** [comment]
Check failed: array.data_type == array.final_data_type Array "image_tensor" has mis-matching actual and final data types (data_type=uint8, final_data_type=float).
Can you solve it ??

**Comment by PINTO0309** [comment]
First, you need to change the placeholder in the Python code of the model from UInt8 to Float32. I'll share the code with you when I have time, but I'm pretty busy and I don't have enough time to work, so please wait a bit.

**Comment by hoangtubatu123** [comment]
yeah. i fixed it. But when i load the model tflite. i have a problem "Encountered unresolved custom op: Enter.Node number 0 (Enter) failed to prepare."

Can you solve it ?? Thanks

**Comment by PINTO0309** [comment]
Two days ago, it seems that the mask r-cnn correspondence was committed to the master branch. So, today I tried to regenerate the weight quantization model using the latest Tensorflow.
**https://github.com/PINTO0309/PINTO_model_zoo/blob/master/08_mask_rcnn_inceptionv2/02_weight_quantization/mask_rcnn_inception_v2_coco_256_weight_quant.tflite**

**Comment by PINTO0309** [comment]
@hoangtubatu123 hoangtubatu123
I was able to successfully convert without a custom OP with Tensorflow v2.2.0-rc3 (Tensorflow Lite). If you feel like it, give it a try.
**https://github.com/PINTO0309/PINTO_model_zoo/tree/master/08_mask_rcnn_inceptionv2**
