### ISSUE TITLE
BlazeFace - How to use?

### ISSUE THREAD

**Issue by vladmandic** [PINTO0309/PINTO_model_zoo#40]
Anyhow knows how to use [BlazeFace](https://github.com/PINTO0309/PINTO_model_zoo/tree/master/030_BlazeFace) ?

Models published here return an array of 4 tensors as output:
```text
  tf_op_layer_classificators_1: dtype: float32, shape: [1, 512, 1]
  tf_op_layer_classificators_2: dtype: float32, shape: [1, 384, 1]
  tf_op_layer_regressors_1: dtype: float32, shape: [1, 512, 16]
  tf_op_layer_regressors_2: dtype: float32, shape: [1, 384, 16]
```

While a model published on [TFHub](https://tfhub.dev/tensorflow/tfjs-model/blazeface/1/default/1)  
and used in their example app at <https://www.npmjs.com/package/@tensorflow-models/blazeface> returns a single tensor:
```text
  Identity: dtype: float32, shape: [1, 896, 17]
```

Why? I already have a working app using model from `TFHub`, but I'd like to use BlazeFace back-model as it's 4x resolution and much better with smaller faces and only model published on `TFHub` is front-model.

**Comment by PINTO0309** [comment]
Just concat each layer. My goal is to quantize it while maintaining accuracy, so I deliberately exclude the final layer of concat.

**Comment by vladmandic** [comment]
thanks, that (sort of) worked, just had to be careful with order of concat operations.

but...using same code for front and back model (just changing image inputsize) and it seems back model is far worse than front one - i expected that it would be able to handle smaller faces as advertised by mediapipe, but it only detects faces when it fills 50% of input frame - or i'm doing something wrong (could be issue with predefined anchors?).

do you have any experience with it?

**Comment by vladmandic** [comment]
nvm, it was a problem with my math on generating anchors - blazeface-back works just fine!
i'm closing this issue - thanks for your help!
