### ISSUE TITLE
091_gaze-estimation-adas-0002 network

### ISSUE THREAD

**Issue by saeidn95** [PINTO0309/PINTO_model_zoo#400]
### Issue Type

Bug

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

ONNX

### Model name and Weights/Checkpoints URL

091_gaze-estimation-adas-0002 network (https://github.com/PINTO0309/PINTO_model_zoo/tree/main/091_gaze-estimation-adas-0002)

### Description

In conversion from Openvino IR (.xml + .bin) to tflite /onnx the order of inputs to the last Concat where the rest of the network is concatenated with "head_pose_angle" is switched. It produces the wrong result. Is there a way to switch the order?

![image](https://github.com/PINTO0309/PINTO_model_zoo/assets/160291002/dcea2596-a1cd-44a9-96d9-9d8089ae4064)

### Relevant Log Output

```shell
https://github.com/openvinotoolkit/open_model_zoo/tree/2021.2/demos/gaze_estimation_demo
```

### URL or source code for simple inference testing code

https://github.com/openvinotoolkit/open_model_zoo/tree/2021.2/demos/gaze_estimation_demo

**Comment by PINTO0309** [comment]
Just rewrite the XML INPUT in the IDE.
