### ISSUE TITLE
Release new 303_FAN with heatmaps

### ISSUE THREAD

**Issue by henryruhs** [PINTO0309/PINTO_model_zoo#401]
### Issue Type

Feature Request

### Programming Language

Python

### Framework

ONNX

### Model name and Weights/Checkpoints URL

303_FAN

### Description

I assume the newer models have a higher accuracy but they lack of the heatmaps.

1. In case the models are the same in terms of accuracy - consider to clarify this in the README or rename the models like model_with_headmap and model_without_headmap rather than old and new.
2. In case the new models are indeed better, please release it with heatmaps.

**Comment by PINTO0309** [comment]
Then you do it.

**Comment by henryruhs** [comment]
Wait, before you close the issue... could you first clarify it?

**Comment by PINTO0309** [comment]
Have you looked at all the committed resources?
If you need to, you can convert it yourself as you wish.
What do you want from me?
Why should I work on it like you expect me to?
I don't make what I don't think I need. That's it.

https://github.com/PINTO0309/PINTO_model_zoo/blob/main/303_FAN/url.txt
