### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by tino926** [PINTO0309/PINTO_model_zoo#402]
### Issue Type

Others

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

PyTorch

### Model name and Weights/Checkpoints URL

https://github.com/PINTO0309/PINTO_model_zoo/tree/main/441_YOLOX-Body-Head-Hand-Face-Dist

### Description

Thanks for your works! Could you please share the tool you used for annotating the dataset? Additionally, have you considered selling the head and body annotations you created?

**Comment by PINTO0309** [comment]
> Thanks for your works! Could you please share the tool you used for annotating the dataset?

CVAT https://www.cvat.ai/

> Additionally, have you considered selling the head and body annotations you created?

No. 
![image](https://github.com/PINTO0309/PINTO_model_zoo/assets/33194443/912df824-96c1-4bd9-85ac-99e99b2e44fd)
