### ISSUE TITLE
410_FaceMeshV2 quantized tflite models are not functional

### ISSUE THREAD

**Issue by Miass5000** [PINTO0309/PINTO_model_zoo#403]
### Issue Type

Bug

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

TensorFlowLite

### Model name and Weights/Checkpoints URL

[410_FaceMeshV2](https://github.com/PINTO0309/PINTO_model_zoo/tree/main/410_FaceMeshV2)

### Description

I want to run the MediaPipe FaceMeshV2 model on the Coral EdgeTPU Accelerator. I found this repository while searching for quantized versions of the FaceMeshV2 tflite model. I downloaded the FaceMeshV2 folder via the provided sh script. The provided tflite float32 model works perfectly fine on the CPU using the tflite framework. However, the quantized versions of the model are not working and producing some weird output. I used the same code with [FaceMeshV1](https://github.com/PINTO0309/PINTO_model_zoo/tree/main/032_FaceMesh), trying all the quantized models from this repository on the CPU, which worked perfectly fine. So, I guess there is no problem with my code. Could you please check if the quantized versions of the FaceMeshV2 tflite model are functional?
Thanks in advance for your help!

**Comment by PINTO0309** [comment]
The model is probably not suited for quantization.
