### ISSUE TITLE
053_BlazePose / 058_BlazePose_Full_Keypoints  source

### ISSUE THREAD

**Issue by vpenades** [PINTO0309/PINTO_model_zoo#406]
### Issue Type

Documentation Feature Request

### OS

Windows

### OS architecture

x86_64

### Programming Language

Other

### Framework

ONNX

### Model name and Weights/Checkpoints URL

053_BlazePose / 058_BlazePose_Full_Keypoints / 10_new_256x256

### Description

I was reviewing 053_BlazePose for any change, and I've noticed there's a 058_BlazePose_Full_Keypoints section

And within it, there's a 10_new_256x256 model.

From where does this model come from?  I couldn't correlate it with any of the existing pose tracking models of google's mediapipe.

Recently here in the EU, regulations related to AI models are going to become more strict, and I want to keep track of the model source, specially considering that Google usually publishes a model card for every one of their models.

**Comment by PINTO0309** [comment]
058_BlazePose_Full_Keypoints

It's a misprint in the README. No such thing exists today.

**Comment by vpenades** [comment]
it's not a big deal, I was just surprised that executing   download_fullkey.sh  extracts a directory called 058_BlazePose_Full_Keypoints

**Comment by PINTO0309** [comment]
I see. The MediaPipe repository is updated frequently. Therefore, it is difficult to identify multiple versions of a model file without going back about four years in the commit history of the MediaPipe repository.
