### ISSUE TITLE
How to retrain simple MLP (palm_detection_full_inf_post_192x192.onnx) model with custom hand dataset ? 

### ISSUE THREAD

**Issue by Abhijeet241093** [PINTO0309/PINTO_model_zoo#407]
### Issue Type

Bug, Support

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

PyTorch, ONNX, TensorRT

### Model name and Weights/Checkpoints URL

Model Name : [palm_detection_full_inf_post_192x192.onnx](https://github.com/PINTO0309/hand-gesture-recognition-using-onnx/blob/main/model/palm_detection/palm_detection_full_inf_post_192x192.onnx)

URL : https://github.com/PINTO0309/hand-gesture-recognition-using-onnx/tree/main/model/palm_detection 

### Description

How to retrain a simple MLP (palm_detection_full_inf_post_192x192.onnx) model with a custom hand dataset? Do you suggest any guidance or procedure to follow? 

### Relevant Log Output

```shell
Thank you Sir
```

### URL or source code for simple inference testing code

https://github.com/PINTO0309/hand-gesture-recognition-using-onnx/tree/main/model/palm_detection

**Comment by PINTO0309** [comment]
Ask Google's super engineers.

**Comment by Abhijeet241093** [comment]
Sorry, brother. Thank you for your direction.

However, unable to find any explanation for the same. If you can share logic or references about how to train an image with simple MLP? then it will be a great help.
