### ISSUE TITLE
CREStereo "next" onnx models for tensorrt

### ISSUE THREAD

**Issue by llschloesser** [PINTO0309/PINTO_model_zoo#421]
### Issue Type

Support

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

C++, Python

### Framework

ONNX, TensorRT

### Model name and Weights/Checkpoints URL

crestereo_combined_iter20_480x640.onnx

### Description

I am testing the CREStereo models at different resolutions, iters, combined vs. init, fp16, etc. with TensorRT. It appears that you or [Ibai Gorordo](https://github.com/ibaiGorordo) created "next" models with a "flow" input. Can you make these available for download? Does that model imply that a traditional stereo algorithm such as SGBM can be used to seed the CREStereo network?

**Comment by PINTO0309** [comment]
All you do is isolate the model.
```
sne4onnx \
--input_onnx_file_path crestereo_combined_iter20_480x640.onnx \
--input_op_names next_left next_right init_output \
--output_op_names next_output \
--output_onnx_file_path crestereo_combined_iter20_480x640_next.onnx
```
![image](https://github.com/user-attachments/assets/a68f9592-e05f-49e6-9eb8-607c96ec05ff)

[crestereo_combined_iter20_480x640_next.onnx.zip](https://github.com/user-attachments/files/16384265/crestereo_combined_iter20_480x640_next.onnx.zip)
