### ISSUE TITLE
Midas 3.1 Conversion Script

### ISSUE THREAD

**Issue by MesaMitch** [PINTO0309/PINTO_model_zoo#422]
### Issue Type

Support

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

ONNX

### Model name and Weights/Checkpoints URL

https://github.com/isl-org/MiDaS

### Description

Hi, May we have the conversion script used for the conversion to ONNX model

**Comment by PINTO0309** [comment]
[MiDaS.zip](https://github.com/user-attachments/files/16410865/MiDaS.zip)

**Comment by MesaMitch** [comment]
Thank you!
