### ISSUE TITLE
yolov9_t_wholebody17 processing example

### ISSUE THREAD

**Issue by MariasStory** [PINTO0309/PINTO_model_zoo#429]
### Issue Type

Support

### OS

Other

### OS architecture

x86_64

### Programming Language

Other

### Framework

ONNX

### Model name and Weights/Checkpoints URL

https://github.com/PINTO0309/PINTO_model_zoo/tree/main/457_YOLOv9-Wholebody17

### Description

I am trying to run the YOLOv9-Wholebody17 in browser using https://cdn.jsdelivr.net/npm/onnxruntime-web/dist/ort.min.js
I have a .js that use to work with you previous models. Now, with yolov9_t_wholebody17_post_0100_1x3x736x1280.onnx the image is processed, but no output.
Can you give me a simple python example of the image processing for the model with some output?

### Relevant Log Output

```shell
process the results: {"batchno_classid_score_x1y1x2y2":{"cpuData":{},"dataLocation":"cpu","type":"float32","dims":[0,7],"size":0}}
```

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/PINTO_model_zoo/blob/main/457_YOLOv9-Wholebody17/demo/demo_yolov9_onnx_wholebody17.py

https://github.com/PINTO0309/PINTO_model_zoo/tree/main/457_YOLOv9-Wholebody17#yolov9-wholebody17
