### ISSUE TITLE
Please update the demo script for Gold-YOLO-Head

### ISSUE THREAD

**Issue by abysslover** [PINTO0309/PINTO_model_zoo#431]
### Issue Type

Support

### OS

Windows, Ubuntu, Mac OS, Other

### OS architecture

x86_64

### Programming Language

Python

### Framework

ONNX

### Model name and Weights/Checkpoints URL

[PINTO0309 Model Zoo: 421_Gold-YOLO-Head](https://github.com/PINTO0309/PINTO_model_zoo/tree/main/421_Gold-YOLO-Head) 

### Description

The demo script located at [PINTO0309 Model Zoo: 421_Gold-YOLO-Head](https://github.com/PINTO0309/PINTO_model_zoo/tree/main/421_Gold-YOLO-Head) currently contains the demo code for Gold-YOLO-Hand, making it difficult to reproduce the results for Gold-YOLO-Head. Additionally, the post-processing code is also for the HAND model, and even after modifying the parameters as instructed, the correct post-processing layer is not being added to the model.

Could you please update the demo script and post-processing code to reflect the correct setup for Gold-YOLO-Head?

### Relevant Log Output

```shell
FileNotFoundError: [Errno 2] No such file or directory: '01_boxes_scores_1638.onnx'
FileNotFoundError: [Errno 2] No such file or directory: '02_cxcywh_y1x1y2x2_1638.onnx'
...
FileNotFoundError: [Errno 2] No such file or directory: '18_nms_box_gather_nd.onnx'
```

### URL or source code for simple inference testing code

[demo_goldyolo_onnx.py](https://github.com/PINTO0309/PINTO_model_zoo/blob/main/421_Gold-YOLO-Head/demo/demo_goldyolo_onnx.py)

**Comment by PINTO0309** [comment]
Unfortunately, I can't understand what you're saying at all.

https://github.com/user-attachments/assets/e84af86a-7f70-47df-ab31-cc582f9cd513

**Comment by abysslover** [comment]
Thank you for your response. I have resolved the issue on my own.
