### ISSUE TITLE
yolov4-tiny with RaspberryPi

### ISSUE THREAD

**Issue by vinorth05** [PINTO0309/PINTO_model_zoo#44]
Hello,
It seems you have great performance with yolo tiny with an RPI :
RaspberryPi4 + CPU only + INT8 + Tensorflow Lite (4 threads) + 416x416 with 243ms/inference Performance.

I assume you used the following command :
```
bazel run -c opt tensorflow/lite/tools/benchmark:benchmark_model -- \
  --graph=${HOME}/Downloads/yolov4-tiny.tflite \
  --num_threads=4 \
  --warmup_runs=1 \
  --enable_op_profiling=true
```

However, how can I get similar results for but with my own images and classes? Do you have a repo for performing object detection optimised for RPI (aarch64/armhf)?

Also, I saw you have special wheels for TensorFlow in aarch64 (https://github.com/PINTO0309/Tensorflow-bin), but do you have the same for other packages like opencv in aarch64?

**Comment by PINTO0309** [comment]
>I assume you used the following command :

Yes. I just used Ubuntu 20.04 aarch64 and further overclocked the CPU to 2.0GHz.

>do you have the same for other packages like opencv in aarch64?

I have a binary that I built messily in May, but I don't think it's very useful.

OpenCV 4.2.0 - Ubuntu 19.10 aarch64 build
**https://drive.google.com/drive/folders/1j_9986szRt9Qpt0WDJkwjWpwkDGW6c2E?usp=sharing**

**Comment by PINTO0309** [comment]
It is closed due to lack of progress.
