### ISSUE TITLE
What dataset was used in training the 026_mobile-deeplabv3-plus OpenVINO models?

### ISSUE THREAD

**Issue by AhmedHisham1** [PINTO0309/PINTO_model_zoo#46]
I am assuming that these are the same as the ones provided by TensorFlow at [tf/models/research/deeplab](https://github.com/tensorflow/models/tree/master/research/deeplab).

If so, the models should output segmentations for 21 classes. However, the provided optimized models predict seg_maps containing only zeros and ones.

Can you please explain the difference between your output and the original model on tf? Is this because you retrained the model on a person class only? If so, what was the dataset used in training?

Thank you.

**Comment by PINTO0309** [comment]
I always commit the URLs of the repositories I refer to, see url.txt.
**https://github.com/PINTO0309/PINTO_model_zoo/blob/master/026_mobile-deeplabv3-plus/url.txt**

My Deeplabv3-plus cites the following repository. It seems to have been trained by people only.
**https://github.com/nolanliou/mobile-deeplab-v3-plus.git**

**Comment by AhmedHisham1** [comment]
This answers my question. 
Thanks a lot for the reply.
