### ISSUE TITLE
Is the blazeface_tflite_to_pb.py script supporting for converting quant TFLite model to pb

### ISSUE THREAD

**Issue by noticedollar** [PINTO0309/PINTO_model_zoo#48]
I found that the blazeface_tflite_to_pb.py script works for some float TFLite model. How about the quant TFLite model to pb? 
thanks

**Comment by PINTO0309** [comment]
A script for the Float16 quantization model has already been committed.

- Front
**https://github.com/PINTO0309/PINTO_model_zoo/blob/master/030_BlazeFace/01_float32/07_new_blazeface_front_tflite2h5_weight_int_fullint_float16_quant.py**

- Back
**https://github.com/PINTO0309/PINTO_model_zoo/blob/master/030_BlazeFace/01_float32/08_new_blazeface_back_tflite2h5_weight_int_fullint_float16_quant.py**

Simply add the following program to the end of the script.
```python
        full_model = tf.function(lambda inputs: model(inputs))
        full_model = full_model.get_concrete_function(inputs=[tf.TensorSpec(model_input.shape, model_input.dtype) for model_input in model.inputs])
        frozen_func = convert_variables_to_constants_v2(full_model, lower_control_flow=False)
        frozen_func.graph.as_graph_def()
        tf.io.write_graph(graph_or_graph_def=frozen_func.graph,
                            logdir=".",
                            name='{}/model_float32.pb'.format(model_output_path),
                            as_text=False)
```

**Comment by noticedollar** [comment]
Hi @PINTO0309 is it able to convert uint8 tflite model to pb?
