### ISSUE TITLE
posenet versions and resnet.

### ISSUE THREAD

**Issue by vpenades** [PINTO0309/PINTO_model_zoo#5]
Hi, first of all, thanks for this great repository of tensor flow models!, I am learning Tensor Flow and it's very useful!.

I am trying to use the models from Posenet, and the results I am getting don't look very good compared to what we can see in the [online posenet demo](https://storage.googleapis.com/tfjs-models/demos/posenet/camera.html).

Also, in the TensorFlow.JS repository, they say they're using the new PoseNet 2.0, which is only available for TensorFlow.JS.... and it comes in two modes:  MobileNet and ResNet.

My questions are:

The Posenet models available in your repository, are based on the old Posenet models? or are they based on the new Posenet 2.0 advertised by tensorflow.js?

Could it be possible for you to include the new Posenet ResNet models in your repository?

Thanks in advance!

**Comment by PINTO0309** [comment]
My model is from old version 1. I didn't know that a version 2 model with high accuracy was released. Thank you for sharing. I need to investigate for a while to see if v2 can be converted and put into my repository. It will take some time.

**Comment by vpenades** [comment]
Here's the anouncement of the posenet 2.0 models:

https://github.com/tensorflow/tfjs-models/tree/master/posenet#note-weve-just-released-version-20-with-a-new-resnet-model-and-api-check-out-the-new-documentation-below

It seems there's an improved version for Mobilenet, and there's also the new resnet model, which is slower, but highly accurate.

There's also a similar demo for hand and finger tracking:

https://github.com/tensorflow/tfjs-models/tree/master/handpose

Which might be interesting to have too!

**Comment by vpenades** [comment]
Hi again... after further investigation, it seems some people already succeeded in converting the models to protobuf: https://github.com/atomicbits/posenet-python

**Comment by PINTO0309** [comment]
Awesome!! The information you share is very useful to other engineers. Thank you again!

**Comment by PINTO0309** [comment]
The skeleton detection of extraterrestrial life seems to be very difficult.
**Test. 1**
![23130680901_92b2c6573e_b](https://user-images.githubusercontent.com/33194443/80100815-7100c880-85ab-11ea-8ffa-712621964b23.jpg)

**Test. 2**
![tennis_in_crowd](https://user-images.githubusercontent.com/33194443/80100848-80801180-85ab-11ea-9464-f5574c9bc5e7.jpg)

**Comment by vpenades** [comment]
Looks nice!, this is with the new posenet 2 models?

**Comment by PINTO0309** [comment]
The heaviest parameter, Resnet50.
```
--model resnet50 --stride 16 --quant_bytes 4
```

**Comment by vpenades** [comment]
For some reason, I am unable to run that python code.... I think I have a problem with some of the tensor flow dependencies. That's why I was using your repos for downloading the models.... I hope you can upload the .pb files soon!

**Comment by PINTO0309** [comment]
The .pb (saved_model) alone is ready to commit immediately. We are in the process of converting to tflite.
![Screenshot 2020-04-23 23:05:28](https://user-images.githubusercontent.com/33194443/80108283-15d4d300-85b7-11ea-987f-098980923857.png)

**Comment by vpenades** [comment]
Great!

**Comment by PINTO0309** [comment]
If you're in a hurry, you can download saved_model with this shell script.
**https://github.com/PINTO0309/PINTO_model_zoo/blob/master/03_posenet/02_posenet_v2/01_float32/download_saved_model.sh**

**Comment by vpenades** [comment]
Hi again; I've been having some trouble consuming the new posenet saved models produced by your script.

In particular, I'm trying to load them with Emgu.TF, but it complains about invalid format.

I've been inspecting the models with Netron, and I've found some subtle differences;

for example, this is what is typically expected:

![imagen](https://user-images.githubusercontent.com/5433822/80220664-778f4e80-8644-11ea-95c3-c065495f3ddf.png)

And this is what I see in your saved models:

![imagen](https://user-images.githubusercontent.com/5433822/80220715-8bd34b80-8644-11ea-99d1-18a41b8bad02.png)

So, maybe setting the format as "TensorFlow Saved Model v1" instead of "TensorFlow Graph" may be causing some differences?

**Comment by PINTO0309** [comment]
I plan to commit saved_model, freeze_graph, tflite that will solve all your problems within a few hours.
![Screenshot 2020-04-24 22:04:13](https://user-images.githubusercontent.com/33194443/80221047-ae368a80-867f-11ea-80d6-3713cb597694.png)

**Comment by PINTO0309** [comment]
I have committed to all materials. Unfortunately, only Full Integer Quantization didn't work properly.
### Posenet V2 ResNet50 225x225 - 513x513 - tflite
Weight Quantization, Integer Quantization, Float16 Quantization, saved_model, Freeze_graph
**https://github.com/PINTO0309/PINTO_model_zoo/tree/master/03_posenet/02_posenet_v2**

**Comment by vpenades** [comment]
Thanks!, the new models are working!

I have a question, though... I've noticed you've converted only the new RestNet models, which is great, since they're the most accurate ones...

But, what about the mobilenet models?   The TensorFlow.JS online demo allowed to choose between mobilenet and resnet.....   and with the online mobilenet models I got significantly better detection than with the old mobilenet versions....  so maybe the mobilenet versions have been retrained for posenet 2.0?  maybe it was just my impression...

Anyway, even if Resnet is much more accurate, mobilenet is still very useful for low end machines.

And, did you take a look at the handpose models?

**Comment by PINTO0309** [comment]
I was tired of work on weekdays, so I performed only minimal conversions. There is no other reason not to convert the MobileNet version. rest assured. I have plenty of time to work at home on Saturdays and Sundays, so I plan to convert MobileNet as well.

>But, what about the mobilenet models? The TensorFlow.JS online demo allowed to choose between mobilenet and resnet..... and with the online mobilenet models I got significantly better detection than with the old mobilenet versions.... so maybe the mobilenet versions have been retrained for posenet 2.0? maybe it was just my impression...

really? I never expected the MobileNet version to be more accurate. In any case, the conversion process is easy, so I will try it.

>And, did you take a look at the handpose models?

Yes. The MediaPipe demo is very interesting. I've been observing well for more than half a year.

**Comment by vpenades** [comment]
Don´t worry, I'm not in a hurry, actually I believe your responses have been incredibly fast!

And thanks a lot for the hard work!

**Comment by PINTO0309** [comment]
I plan to commit later today.
![Screenshot 2020-04-25 09:11:46](https://user-images.githubusercontent.com/33194443/80266721-511af300-86d8-11ea-8274-0f432f5a4cc2.png)

Btw, the video below is the result of my trial of 3D Pose Estimation, which is quite interesting.

**3D PoseEstimation + OpenVINO + Corei7 CPU only + 720p(1280x720) USB Camera + Sync Real TIme**
**https://www.youtube.com/watch?v=DgKw0Ty22PE&feature=youtu.be**

**Comment by PINTO0309** [comment]
I have committed a full version of MobileNet/ResNet model. Please update the cloned repository and execute the download script again.
