### ISSUE TITLE
Unhandled "Dequantize" operation in new MediaPipe BlazeFace model

### ISSUE THREAD

**Issue by heshuimu** [PINTO0309/PINTO_model_zoo#50]
I tried to run your BlazeFace conversion script on the most recent BlazeFace model in MediaPipe. I noticed that the dequantize operation (builtin_code = 6) was not handled in your script. I tried to edit the script to handle this, but I am not at all familiar with TensorFlow, so I am not sure what this operation maps to. Would you mind provide some advice? Thank you in advance!

(I may have used the wrong FlatBuffer definitions so the following operator_codes json might not look right. )

Model: https://github.com/google/mediapipe/blob/f15da632dec186f2c1d3c780f47086477e2286a9/mediapipe/models/face_detection_front.tflite

```json
...
  "operator_codes": [
    {
      "deprecated_builtin_code": 3,
      "version": 1,
      "builtin_code": "ADD"
    },
    {
      "deprecated_builtin_code": 19,
      "version": 1,
      "builtin_code": "ADD"
    },
    {
      "deprecated_builtin_code": 4,
      "version": 1,
      "builtin_code": "ADD"
    },
    {
      "deprecated_builtin_code": 0,
      "version": 1,
      "builtin_code": "ADD"
    },
    {
      "deprecated_builtin_code": 34,
      "version": 1,
      "builtin_code": "ADD"
    },
    {
      "deprecated_builtin_code": 17,
      "version": 1,
      "builtin_code": "ADD"
    },
    {
      "deprecated_builtin_code": 22,
      "version": 1,
      "builtin_code": "ADD"
    },
    {
      "deprecated_builtin_code": 2,
      "version": 1,
      "builtin_code": "ADD"
    },
    {
      "deprecated_builtin_code": 6,
      "version": 2,
      "builtin_code": "ADD"
    }
  ],
...
```

**Comment by PINTO0309** [comment]
The weights set in each layer were extracted by hand using **[Netron](https://netron.app/)**. It is possible to extract the weights in bulk if you create a script, but so far I have not created such a script.
![image](https://user-images.githubusercontent.com/33194443/99766468-82f81900-2b44-11eb-879f-ca0baf6f9ab5.png)

The script to convert the new model is below. All you have to do is specify the weight file in Numpy format extracted from the above work in each layer in `np.load`. I put all the weight files under a folder named `weights_front` and converted them.
**https://github.com/PINTO0309/PINTO_model_zoo/blob/master/030_BlazeFace/01_float32/07_new_blazeface_front_tflite2h5_weight_int_fullint_float16_quant.py**

https://github.com/PINTO0309/PINTO_model_zoo/blob/c50411c7956047a9b76b218ccf56bfee91f30778/030_BlazeFace/01_float32/07_new_blazeface_front_tflite2h5_weight_int_fullint_float16_quant.py#L44-L46

**Comment by PINTO0309** [comment]
I have created a conversion tool that supports Dequantize operation (built-in_code = 6). I just created it 3 days ago, so I will add more OPs to support it.
**https://github.com/PINTO0309/tflite2tensorflow**

<p align="center">
  <img src="https://user-images.githubusercontent.com/33194443/105187518-38ac0c00-5b76-11eb-869b-b518df146924.png" />
</p>

**Comment by PINTO0309** [comment]
This is closed as it has been resolved. If you have other issues, please post a new issue.
