### ISSUE TITLE
StrideSlice op only supports 1D-4D input arrays.Node number 208(STRIDED_SLICE) failed to prepare

### ISSUE THREAD

**Issue by gouliang1997** [PINTO0309/PINTO_model_zoo#52]
When I run tflite object detection with Raspberry pi 4B using yolov3_lite_voc_416_full_integer_quant.tflite, I got this problem:

RuntimeError: tensorflow/lite/kernels/strided_slice.cc StridedSlice op only supports 1D-4D input arrays.Node number 208 (STRIDED_SLICE) failed to prepare.

Thanks

**Comment by PINTO0309** [comment]
This is the specification of the TensorFlow Lite runtime.
