### ISSUE TITLE
NanoDet 416x416 edge tpu model not working for coral

### ISSUE THREAD

**Issue by fogelton** [PINTO0309/PINTO_model_zoo#54]
When I try to use your precompiled model I get an error while calling allocate_tensors()

    interpreter.allocate_tensors()
  File "/home/andrej/tf2-models/env-nightly/lib/python3.8/site-packages/tensorflow/lite/python/interpreter.py", line 259, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: Internal: :213 batches * single_output_size != output->bytes (6032 != 313664)Node number 232 (EdgeTpuDelegateForCustomOp) failed to prepare.

any ideas? I am using tf-nightly 2.5dev, libedgetpu1-max 15.0

**Comment by PINTO0309** [comment]
Unfortunately, you will have to wait for the following issues to be resolved.
https://github.com/google-coral/edgetpu/issues/274
