### ISSUE TITLE
question : what is the previous step to quantitize nanodet model ?

### ISSUE THREAD

**Issue by wwdok** [PINTO0309/PINTO_model_zoo#55]
Hi, @PINTO0309 , thank you for providing these great samples, now i am interested in using nanodet tflite model, you have provided the convertion python scripts, but i have a question, what is the file used to export tflite in `saved_model_320x320` ? is it `model_float32.pb` ? if so,  how to generate it? Could you please give me some instructions ? Many thanks !

**Comment by PINTO0309** [comment]
If I try to explain it properly, it will take a long time. Please wait a moment while I prepare it.

**Comment by wwdok** [comment]
Oh, sorry for this will take you a long time, let me narrow down the scope of the the question, the `model_float32.pb` cooms from format convertion or transfer retraining ?

**Comment by PINTO0309** [comment]
## Environment
1. PyTorch
2. ONNX Runtime
3. OpenVINO 2021.1+
4. tf-nightly

## Conversion Workflow
**`PyTorch -> ONNX -> OpenVINO IR -> openvino2tensorflow -> TFLite`**

## ONNX -> OpenVINO IR
```
$ python3 ${INTEL_OPENVINO_DIR}/deployment_tools/model_optimizer/mo.py \
 --input_model nanodet_320x320.onnx \
 --input i \
 --input_shape [1,3,320,320] \
 --output_dir openvino/nanodet_320x320/FP32 \
 --data_type FP32
```
Three types of files will be generated: .xml, .bin, and .mapping.
![Screenshot 2020-12-17 00:03:31](https://user-images.githubusercontent.com/33194443/102365839-56c4a080-3ffb-11eb-8d9e-b7ab527675a5.png)

## Edit and optimize the .xml to remove layers of meaningless garbage
### 1. Before
![Screenshot 2020-12-17 00:09:29](https://user-images.githubusercontent.com/33194443/102366754-5973c580-3ffc-11eb-8ef4-37c8e5623ec5.png)

### 2. After
![Screenshot 2020-12-17 00:09:44](https://user-images.githubusercontent.com/33194443/102366784-61cc0080-3ffc-11eb-966b-a400a11c6528.png)

### OpenVINO IR -> TFLite
```
openvino2tensorflow \
  --model_path onnx/openvino/nanodet_320x320/FP32/nanodet_320x320.xml \
  --output_saved_model True \
  --output_h5 True \
  --output_pb True \
  --output_no_quant_float32_tflite True \
  --output_weight_quant_tflite True \
  --output_float16_quant_tflite True
```

**Comment by PINTO0309** [comment]
@wwdok 

>the model_float32.pb comes from format convertion or transfer retraining ?

 format convertion

**Comment by wwdok** [comment]
Wow, the convertion process is longer than i thought, i am really thankful for this helpful guide !
