### ISSUE TITLE
Update of palm detection model in mediapipe

### ISSUE THREAD

**Issue by DanielMao2015** [PINTO0309/PINTO_model_zoo#58]
Hi, thanks for your excellent work. And I found that the palm detect model in mediapipe has been updated and the input resolution is modified from 256*256 to 128*128,whicn means smaller size and fast inference. 
https://github.com/google/mediapipe/blob/master/mediapipe/modules/palm_detection/palm_detection.tflite
Do you have any plan to update the palm detection model or do I just use the converted script in this repo then I can get the updated quantized palm detect model?

**Comment by PINTO0309** [comment]
I've started working on this. But I have a real job to do, so please wait a week or so.

**Comment by DanielMao2015** [comment]
@PINTO0309 It is very kind of you to share this repo and help a lot with deep learning on mobile!

**Comment by PINTO0309** [comment]
I have converted the 128x128 model you gave me for the various frameworks and committed it.

**TFLite (Float32/Float16/INT8), EdgeTPU, TFJS (Float32/Float16), TF-TRT (Float32/Float16), CoreML, OpenVINO (FP32/FP16)**
**https://github.com/PINTO0309/PINTO_model_zoo/tree/master/033_Hand_Detection_and_Tracking/10_new_128x128**

**Comment by DanielMao2015** [comment]
Many thanks! I will try it as possile!

**Comment by DanielMao2015** [comment]
@PINTO0309  hi, I have tried the 8-bit int quantized model,and the result shows incorrectly.For 16-float model ,everything works well and the interger quant model and the result is not correct. Concretly, when there is hand, the classification score is about 0.5 and is 0 when no hand. So the scale of classification score of interger model changes from [0,1.0] to [0,0.5]. And maybe the value of regression brach is also be rescaled??

**Comment by PINTO0309** [comment]
I have applied the following normalization Sorry, I didn't think too much about it and used INT8 quantization as an experiment.
**https://github.com/PINTO0309/PINTO_model_zoo/blob/main/033_Hand_Detection_and_Tracking/10_new_128x128/02_convert_script.txt**

```
sudo pip3 install openvino2tensorflow --upgrade

### tf-nightly
saved_model_to_tflite \
  --saved_model_dir_path saved_model \
  --output_no_quant_float32_tflite True \
  --output_weight_quant_tflite True \
  --output_float16_quant_tflite True \
  --output_integer_quant_tflite True \
  --string_formulas_for_normalization 'data / 255.0'

### tf-nightly
saved_model_to_tflite \
  --saved_model_dir_path saved_model \
  --output_edgetpu True \
  --string_formulas_for_normalization 'data / 255.0'
```

Normalization rules can be handled by changing the following parameters. Currently, it is just a simple division by 255.
```
--string_formulas_for_normalization 'data / 255.0'
```

**Comment by DanielMao2015** [comment]
@PINTO0309 I have just tested the model. In detail I make the input all zeros to the different type of model(float32 float16 and int8) and compare the output. Then found that:
1.for the float 16 and float 32 version, there is only slightly different  between output of these two models
2.for the int 8 and float 32 version , the outputs are totally different.
So, is there something wrong about int 8 model?

**Comment by PINTO0309** [comment]
Thank you for doing the research. 😄 

There is no difference in the internal conversion behavior of my script between Float32 and INT8. As mentioned earlier, only the part that performs the normalization operation is different. By the way, from my past experience, I know that keypoint calculation models are very incompatible with INT8 quantization and the accuracy degrades significantly. I don't think there is any difference in the structure of the model except for the insertion of the Quantize OP and the fact that the weights have been converted to integers.

For example, Posenet and BalzeFace's face part detection is very inaccurate and useless. It may be necessary to change the definition of the value range during dequantization to be aware of the quantization range.
