### ISSUE TITLE
Can we generate tensorflow .pb model from .tflite model?

### ISSUE THREAD

**Issue by jimmy7799** [PINTO0309/PINTO_model_zoo#59]
I have to use tensorflow full model because I want to use DNN module in OpenCV.

There are some .pb files in directory 082_MediaPipe_Meet_Segmentation, but its results are worse than tflite model.

Can we generate .pb model with similar result as tflite model?

Thanks!

**Comment by PINTO0309** [comment]
I'm going to work now, so I'll deal with it when I get home. Please wait a moment.

**Comment by jimmy7799** [comment]
Many thanks!

**Comment by PINTO0309** [comment]
Can you share the code for testing?

**Comment by jimmy7799** [comment]
Here are the test code.
The file test_tf.py is modified based on your test code.
The utils.py is originally from https://github.com/ajaichemmanam/simple_bodypix_python.

[test.tar.gz](https://github.com/PINTO0309/PINTO_model_zoo/files/5789029/test.tar.gz)

**Comment by jimmy7799** [comment]
I tested model_v2, but did not see big difference.

Here is another question, how segm_full_v679_opt.tflite is generated and what the difference between that and original model segm_full_v679.tflite?

Actually, when I replace to original model segm_full_v679.tflite in your test code, I got the following error.
So I must miss something.

Traceback (most recent call last):
  File "test_tf.py", line 50, in <module>
    interpreter.allocate_tensors()
  File "/usr/local/lib/python3.8/site-packages/tensorflow/lite/python/interpreter.py", line 243, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: Encountered unresolved custom op: Convolution2DTransposeBias.Node number 240 (Convolution2DTransposeBias) failed to prepare.

**Comment by PINTO0309** [comment]
You will need to use this shell script to use the resources you have downloaded. 
**https://github.com/PINTO0309/PINTO_model_zoo/blob/master/082_MediaPipe_Meet_Segmentation/download_full_144x256.sh**
![Screenshot 2021-01-09 15:28:46](https://user-images.githubusercontent.com/33194443/104084979-64361900-528f-11eb-8736-6cb520558d8a.png)

- **Your test code + model_v2.pb**
**test.jpg, segments2.jpg, segments1.jpg**
![Screenshot 2021-01-09 15:22:29](https://user-images.githubusercontent.com/33194443/104084871-85e2d080-528e-11eb-8446-d63cdce2fcb4.png)

- **Result after background transparency processing fg.jpg**
![Screenshot 2021-01-09 15:24:02](https://user-images.githubusercontent.com/33194443/104084896-bcb8e680-528e-11eb-9cc1-3763a1814162.png)

**Comment by jimmy7799** [comment]
Thanks! I found that the output of model_v2.pb is similar to output of model_float32.tflite too.

The difference I mentioned before is compared to segm_full_v679_opt.tflite and you said it is intermediate generation file.
But there are less noise in the output actually although the resolution is half.

Do you know why original model segm_full_v679.tflite can not be used in tflite test code?

**Comment by PINTO0309** [comment]
The reason is that the Convolution2DTransposeBias layer is not implemented in TensorFlow Lite.
![Screenshot 2021-01-09 16:28:36](https://user-images.githubusercontent.com/33194443/104086054-c1ce6380-5297-11eb-91e1-56426b258cb3.png)

**Comment by jimmy7799** [comment]
Looks like the model itself is good, the problem may be on opencv side.

We can close this issue for now.
