### ISSUE TITLE
BlazeFace confidence score

### ISSUE THREAD

**Issue by sonfire86** [PINTO0309/PINTO_model_zoo#6]
Excellent translation of models! But how can I get the correct confidence score?
My code 

```
def load_graph(frozen_graph_filename):
    detection_graph = tf.Graph()
    with detection_graph.as_default():
        od_graph_def = tf.GraphDef()
        with tf.gfile.GFile(frozen_graph_filename, 'rb') as f:
            serialized_graph = f.read()
            od_graph_def.ParseFromString(serialized_graph)
            tf.import_graph_def(od_graph_def, name='')

    return detection_graph

detection_face = load_graph('face_detection_front.pb')

img_inputs_face = detection_face.get_tensor_by_name('input:0')


classificators = detection_face.get_tensor_by_name('classificators:0')
regressors = detection_face.get_tensor_by_name('regressors:0')

img = cv2.imread('2-1.jpg')
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
img = cv2.resize(img, (128, 128))
image_np_expanded = np.expand_dims(img, axis=0)

(pred_classificators , pred_regressors) = persistent_sess.run([classificators , regressors],
        feed_dict={img_inputs_face: image_np_expanded})
```

I get very strange `pred_classificators `
```
[[-1.16985550e+01],
       [-9.47585297e+00],
       [-9.12463665e+00],
       [-5.20070457e+00],
       [-1.55940714e+01],
       [-1.01529875e+01],
       [-1.26312046e+01],
       [-4.64342594e+00],
       [-1.42407932e+01],
       [-7.08438396e+00],
       [-1.52337151e+01],
       .....]
```

**Comment by PINTO0309** [comment]
There is a lack of normalization of the input image and a lack of numerical conversion after inference.
```python
img = cv2.imread('2-1.jpg')
img = cv2.resize(img, (128, 128))
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.normalize(img, img, -1, 1, cv2.NORM_MINMAX)
image_np_expanded = np.expand_dims(img, axis=0)

(pred_classificators , pred_regressors) = persistent_sess.run([classificators , regressors],
        feed_dict={img_inputs_face: image_np_expanded})

scores = 1.0 / (1.0 + np.exp(-pred_classificators.numpy()))
```

**Comment by sonfire86** [comment]
I get very low score of `0.00013611263 .... 8.4253545e-05`How to interpret in normal probabilities `0% - 100%`?

**Comment by loptruong** [comment]
@PINTO0309 , Thanks for your help to process the prediction score(pred_classificators). However, do we have post-processing for pred_regressors, because there are many negative number here!

**Comment by Laubeee** [comment]
> There is a lack of normalization of the input image and a lack of numerical conversion after inference.
> 
> ```python
> img = img - 127.5
> img = img * 0.007843

I understand the input has to be normalized [-1 ... 1] not [0...1] (as documented in the [model card](https://developers.google.com/ml-kit/images/vision/pose-detection/accurate-modelcard.pdf) but to be fair they also are missing the *z* value in the output..)

May I ask where you got it from? Is this meant to support mean-subtraction, and, in that case, shouldn't the mean values of the training set be used?
In any case, the output I get is quite similar for both ranges..

**Comment by PINTO0309** [comment]
I understand that I need to calibrate using the data set used during training. I will follow the exact description in the document if there is one. The normalization range was used in a crude way to predict a likely value. This is because I don't know the correct way to normalize. I don't know the data set either.

If you guys are dissatisfied with the accuracy, you can easily invert the model using the tool below. The dataset used for calibration and the range of normalization can be changed by yourself by adjusting the tool parameters. The last model I converted only used this tool to perform a normalization of /255. But I don't know the certainty of that value.
**https://github.com/PINTO0309/tflite2tensorflow**
![1](https://user-images.githubusercontent.com/33194443/105187518-38ac0c00-5b76-11eb-869b-b518df146924.png)

**Comment by Laubeee** [comment]
I'm not sure I get the concept of what you propose, wouldn't setting custom normalization values have to affect all the model weights too?
