### ISSUE TITLE
Which dataset(s) are the object detection models trained on?

### ISSUE THREAD

**Issue by tleyden** [PINTO0309/PINTO_model_zoo#60]
Amazing work and thank you for this!

I can see that `045_ssd_mobilenet_v2_oid_v4` is trained on OpenImages V4, but what about `046_yolov4-tiny`?  Is it trained on Pascal VOC, Coco, or something else entirely?  

Also is it possible to get the link to the upstream model that was used for conversion?  For example was `045_ssd_mobilenet_v2_oid_v4` converted from https://tfhub.dev/google/openimages_v4/ssd/mobilenet_v2/1?

**Comment by PINTO0309** [comment]
The same is true for YoloV4-tiny and other models, and I have included the URL of my cited repository in the file **`url.txt`** as shown below. In the case of YoloV4-tiny, it is **`Pascal-VOC`**.
**https://github.com/PINTO0309/PINTO_model_zoo/blob/master/046_yolov4-tiny/url.txt**

>Also is it possible to get the link to the upstream model that was used for conversion? For example was 045_ssd_mobilenet_v2_oid_v4 converted from https://tfhub.dev/google/openimages_v4/ssd/mobilenet_v2/1?

Same as the answer above. Have a look at **`url.txt`**. 
**https://github.com/PINTO0309/PINTO_model_zoo/blob/master/045_ssd_mobilenet_v2_oid_v4/url.txt**

**https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md#open-images-trained-models**
