### ISSUE TITLE
Is nanodet working in tflite?

### ISSUE THREAD

**Issue by mosheliv** [PINTO0309/PINTO_model_zoo#62]
i am trying to use the file from saved_model_416x416//model_float16_quant.tflite

it loads and seems like inferencing but when i print interpreter.get_tensor(self.output_details[1]['index'])[0] i get:

```
[[ 1.6956738   0.9603495   0.08334054 ... -0.43478656 -0.615623
  -0.69419366]
 [ 1.3914261   1.064209    0.5480403  ... -0.3135112  -0.6691925
  -1.055948  ]
 [ 1.116673    0.7275144   0.21141839 ... -0.33032337 -0.8020203
  -1.3268852 ]
 ...
 [ 1.1918403   0.8403666   0.23102881 ... -0.78871083 -1.1012893
  -1.5689907 ]
 [ 1.1498222   1.2557286   0.9366938  ... -0.8202821  -1.1629286
  -1.481539  ]
 [ 3.8123865   2.9635813   0.75818133 ... -0.7893712  -1.0882326
  -1.1440537 ]]
```
do i need to post process it?
if yes, how? any help will be greatly appreciated.

**Comment by PINTO0309** [comment]
>do i need to post process it?

Yes.

>if yes, how? any help will be greatly appreciated.

You will need to implement Post-Process yourself in the repository cited below.
**https://github.com/RangiLyu/nanodet/blob/main/demo/demo.py**

**Comment by mosheliv** [comment]
Mmm i see... A tad more complicated than I thought. Also, code looks a bit inefficient, for example the sigmoid is called for each box (row) and not on the array. Thank you!
