### ISSUE TITLE
No module named 'utils'

### ISSUE THREAD

**Issue by Aayush795** [PINTO0309/PINTO_model_zoo#64]
When I am running the test_tf.py from 082_MediaPipe_Meet_Segmentation from my local, It throws the error-  
`No module named 'utils'`
What am I missing here? I don't see the utils folder in the repository
The error comes in the line 

`from utils import load_graph_model, get_input_tensors, get_output_tensors`

**Comment by PINTO0309** [comment]
Please do a **`git pull`** and try again. d7a2a98361371b11900f9809076cf8d08c23e2ac

**Comment by Aayush795** [comment]
Thanks, That worked.
However, I am now getting another error
`tensorflow.python.framework.errors_impl.NotFoundError: model_v2.pb; No such file or directory`
do I need to run any sh file?

**Comment by PINTO0309** [comment]
You will find "model_v2.pb" in the downloaded resources.
![Screenshot 2021-01-21 21:02:47](https://user-images.githubusercontent.com/33194443/105348749-1f659700-5c2c-11eb-861e-ccaadf606f4f.png)

Change the following path in the program to match your environment.
https://github.com/PINTO0309/PINTO_model_zoo/blob/dbcd717de5428877cd17ceb98c411cff9f1bafc7/082_MediaPipe_Meet_Segmentation/test_tf.py#L26

**Comment by PINTO0309** [comment]
Closed due to lack of progress. If you have other issues, please post a new issue.
