### ISSUE TITLE
Problem in running test for 082_MediaPipe_Meet_Segementation

### ISSUE THREAD

**Issue by fransiskusyoga** [PINTO0309/PINTO_model_zoo#67]
I tried to run test.py from this folder (082_MediaPipe_Meet_Segementation) and got error. If I use a model I downloaded from "sudo gdown --id 1qOlcK8iKki_aAi_OrxE2YLaw5EZvQn1S" , I get this error.
```
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    interpreter.set_tensor(input_details, img)
  File "C:\Users\Fransiskus Yoga Esa\AppData\Local\Programs\Python\Python38\lib\site-packages\tflite_runtime\interpreter.py", line 423, in set_tensor
    self._interpreter.SetTensor(tensor_index, value)
ValueError: Cannot set tensor: Dimension mismatch. Got 144 but expected 128 for dimension 1 of input 0.
PS D:\Users\Downloads\openCV\code\PINTO_model_zoo\082_MediaPipe_Meet_Segmentation>
```

if I use this model ( https://meet.google.com/_/rtcvidproc/release/336842817/segm_lite_v509.tflite ), I get this error
```
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    interpreter.allocate_tensors()
  File "C:\Users\Fransiskus Yoga Esa\AppData\Local\Programs\Python\Python38\lib\site-packages\tflite_runtime\interpreter.py", line 259, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: Encountered unresolved custom op: Convolution2DTransposeBias.Node number 241 (Convolution2DTransposeBias) failed to prepare.
```
What model that I can use to run the test.py?

**Comment by PINTO0309** [comment]
>I tried to run test.py from this folder (082_MediaPipe_Meet_Segementation) and got error. If I use a model I downloaded from "sudo gdown --id 1qOlcK8iKki_aAi_OrxE2YLaw5EZvQn1S" , I get this error.

The model submitted to the TFJS issue is not complete, as it was created temporarily in the process of validation. Please use the following.

**https://github.com/PINTO0309/PINTO_model_zoo/blob/main/082_MediaPipe_Meet_Segmentation/download_full_144x256.sh**
　
　
>if I use this model ( https://meet.google.com/_/rtcvidproc/release/336842817/segm_lite_v509.tflite ), I get this error

If you want to run the original model with custom layers, please install the following and try again.  However, as long as you use the model described in the first answer, you should not need to take this action.

```bash
### Customized version of TensorFlow Lite installation
$ sudo gdown --id 1RWZmfFgtxm3muunv6BSf4yU29SKKFXIh
$ sudo chmod +x tflite_runtime-2.4.1-py3-none-any.whl
$ sudo pip3 install tflite_runtime-2.4.1-py3-none-any.whl
```

By the way, you don't need to change the model used, just modify the input resolution of the image in **`test.py`** to make it work. [256, 144] -> [128,128].

**Comment by fransiskusyoga** [comment]
I download the model from the shell script and use model_float16_quant.tfile. I end up find the=is error
```
(1, 144, 256, 2)
out1: (144, 256)
out2: (144, 256)
Traceback (most recent call last):
  File ".\test.py", line 45, in <module>
    out3 = cv2.ximgproc.jointBilateralFilter(out2, out1, 8, 75, 75)
AttributeError: module 'cv2.cv2' has no attribute 'ximgproc'
```

it can be solved by this 
```
pip uninstall opencv-contrib-python opencv-python
pip install opencv-contrib-python
```


For the original model, I already have the tflite runtime. I tried to uninstall mine and install it with yours but the error message is still the same.

**Comment by fransiskusyoga** [comment]
btw, is there a way to run this model? (  https://meet.google.com/_/rtcvidproc/release/336842817/segm_lite_v509.tflite  )

**Comment by PINTO0309** [comment]
I have reiterated the steps I gave you in the beginning, and it worked fine.
```
$ sudo pip3 uninstall tensorboard-plugin-wit tb-nightly tensorboard \
                      tf-estimator-nightly tensorflow-gpu \
                      tensorflow tf-nightly tensorflow_estimator tflite_runtime -y
$ sudo gdown --id 1RWZmfFgtxm3muunv6BSf4yU29SKKFXIh
$ sudo chmod +x tflite_runtime-2.4.1-py3-none-any.whl
$ sudo pip3 install tflite_runtime-2.4.1-py3-none-any.whl --upgrade
```

```python
import numpy as np
import cv2
try:
    from tflite_runtime.interpreter import Interpreter
except:
    from tensorflow.lite.python.interpreter import Interpreter

img = cv2.imread('test.jpg')
h = img.shape[0]
w = img.shape[1]

img = cv2.resize(img, (128, 128))
img = np.asarray(img)
img = img / 255.
img = img.astype(np.float32)
img = img[np.newaxis,:,:,:]

# Tensorflow Lite
interpreter = Interpreter(model_path='segm_lite_v509.tflite', num_threads=4)
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()[0]['index']
output_details = interpreter.get_output_details()[0]['index']

interpreter.set_tensor(input_details, img)
interpreter.invoke()
output = interpreter.get_tensor(output_details)

print(output.shape)
out1 = output[0][:, :, 0]
out2 = output[0][:, :, 1]

out1 = np.invert((out1 > 0.5) * 255)
out2 = np.invert((out2 > 0.5) * 255)

print('out1:', out1.shape)
print('out2:', out2.shape)

out1 = cv2.resize(np.uint8(out1), (w, h))
out2 = cv2.resize(np.uint8(out2), (w, h))

cv2.imwrite('out1.jpg', out1)
cv2.imwrite('out2.jpg', out2)

# out3 = cv2.ximgproc.jointBilateralFilter(out2, out1, 8, 75, 75)
# cv2.imwrite('out3.jpg', out3)
```

![test](https://user-images.githubusercontent.com/33194443/106293325-37bf5c80-6291-11eb-9b61-f8c8ce9f6793.jpg)
cv2.imwrite('out3.jpg', out3)
![out2](https://user-images.githubusercontent.com/33194443/106293354-40179780-6291-11eb-9ec2-482daba2bd06.jpg)
![out1](https://user-images.githubusercontent.com/33194443/106293367-43ab1e80-6291-11eb-8eeb-818016432dc1.jpg)

**Comment by fransiskusyoga** [comment]
I tried it with the instruction you give here is the result. For info, I am using windows

```
$ python
Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from tflite_runtime.interpreter import Interpreter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Fransiskus Yoga Esa\AppData\Local\Programs\Python\Python38\lib\site-packages\tflite_runtime\interpreter.py", line 36, in <module>
    from tflite_runtime import _pywrap_tensorflow_interpreter_wrapper as _interpreter_wrapper
ImportError: cannot import name '_pywrap_tensorflow_interpreter_wrapper' from 'tflite_runtime' (C:\Users\Fransiskus Yoga Esa\AppData\Local\Programs\Python\Python38\lib\site-packages\tflite_runtime\__init__.py)
```

**Comment by PINTO0309** [comment]
Please refer to the following article to build a custom runtime for Windows.
**https://www.tensorflow.org/lite/guide/build_cmake**
