### ISSUE TITLE
Commercial Licence For Google Meet Virtual Background

### ISSUE THREAD

**Issue by NaeemKhan333** [PINTO0309/PINTO_model_zoo#69]
Thanks for releasing the Google Meet Background Segmentation Tensorflow JS Model. I have question related to commercial use that can anyone use this model in any commercial application?. Although mediapipe is open source and can this Google Meet Segmentation model can be use in commercial application. Thanks

**Comment by PINTO0309** [comment]
Recently, the license was changed from Apache 2.0 to Google Terms of Service. I am also keeping a close eye on it to see if it is available for commercial use.

https://github.com/tensorflow/tfjs/issues/4177#issuecomment-772008274

**Comment by gtunon** [comment]
Hello this issue is nearly 2 month old. Has anyone found if the model can be use in commercial application?

**Comment by benbro** [comment]
[Jitsi](https://jitsi.org/blog/march-update-new-toolbar-ui-virtual-backgrounds-and-more/) started using the model. Not sure what it says about the license.
Any idea why the result doesn't look good in the [demo](https://meet.jit.si/)?

**Comment by kirawi** [comment]
The license was [found](https://github.com/tensorflow/tfjs/issues/4177#issuecomment-839725654). I think this issue can be closed now.

**Comment by PINTO0309** [comment]
I have committed the Apache 2.0 model card. 79016cb2c7d033f014905a70c8931c10afea278b

**Comment by abhisht51** [comment]
If you look at this [comment](https://github.com/tensorflow/tfjs/issues/4177#issuecomment-858137878), I think they imply that the media-pipe model cannot be used for commercial purposes. What are your thoughts on this? @PINTO0309
