### ISSUE TITLE
model's output tensor size is not 4

### ISSUE THREAD

**Issue by robertoshiu** [PINTO0309/PINTO_model_zoo#7]
`engine = DetectionEngine("yolov4_416_full_integer_quant_edgetpu.tflite")`

**ValueError: Dectection model should have 4 output tensors!This model has 3.**

**Comment by rajansaini691** [comment]
+1 Same issue. Any update?

**Comment by PINTO0309** [comment]
Use edgetpu.basic.basic_engine.BasicEngine.BasicEngine instead of edgetpu.detection.engine.DetectionEngine.
https://coral.ai/docs/reference/edgetpu.basic.basic_engine/
