### ISSUE TITLE
Testing Code For Converted U2netp Tensorflow-Js

### ISSUE THREAD

**Issue by NaeemKhan333** [PINTO0309/PINTO_model_zoo#71]
@PINTO0309  Thanks for nice work . I have done the conversion of u2netp model using [Blog](https://qiita.com/PINTO/items/ed06e03eb5c007c2e102) and it is converted successfully. Now I want to test the converted model to show its output.

Can you provide the Testing script,So I can verify my Tensorflow-Js Converted Model is working or not.Thanks

**Comment by PINTO0309** [comment]
https://github.com/w-okada/image-analyze-workers
