### ISSUE TITLE
Diffrence between model_float32.onnx and <model_name>.onnx

### ISSUE THREAD

**Issue by Laubeee** [PINTO0309/PINTO_model_zoo#72]
I'm curious what the differences between the .onnx models you generate are. Usually there are two:  `model_float32.onnx` and `model_float32_opt.onnx`, the later seems to be a tiny bit faster. Sometimes, there is even a 3rd model, e.g. `human-pose-estimation-3d-0001.onnx`. which, in this case is noticeably faster than the `_opt` model.
Specifically, on integrated intel GPU (via DirectML) I get 2.4, 2.6 and 3.4 fps

Windows10, x86_64
[example model human-pose-estimation-3d-0001](https://github.com/PINTO0309/PINTO_model_zoo/tree/main/029_human-pose-estimation-3d-0001/01_float32)
onnx 1.8.1, onnxruntime 1.5.2 with DirectML

Code to reproduce
```python
mpath = "../models/human-pose-estimation-3d-0001.onnx"
# mpath = "../models/model_float32.onnx"
#mpath = "../models/model_float32_opt.onnx"
sess = rt.InferenceSession(mpath)
input_name = sess.get_inputs()[0].name
inblob = cv2.dnn.blobFromImage(frame, 1.0 / 255, (448, 256), mean=(0, 0, 0), swapRB=False, crop=False) #.transpose(0,2,3,1)
out = sess.run(None, {input_name: inblob})[1]  #.transpose(0,3,1,2)
```

**Comment by PINTO0309** [comment]
### 1. Model without **`_opt`**
The model is either converted from onnx to openvino and then to onnx again, or converted from onnx (NCHW) to openvino (NCHW) and then to onnx (NHWC) again via TensorFlow (NHWC). No optimization has been performed.
### 2. Model with **`_opt`**
This model optimizes the onnx structure using **`onnx-simplifier`** in addition to the operations in 1. For example, onnx, which is simply generated from PyTorch, is generated with a significantly redundant structure. Use **[onnx-simplifier](https://github.com/daquexian/onnx-simplifier.git)** to optimize the structure and weights.
### 3. The third model
The pattern is that onnx files were provided from the beginning. This is a clean model that has not undergone any work such as NCHW to NHWC conversion.

See part of my article below to see why there are advantages to using onnx-simplifier.
- [English] Converting PyTorch, ONNX, Caffe, and OpenVINO (NCHW) models to Tensorflow / TensorflowLite (NHWC) in a snap
**https://qiita.com/PINTO/items/ed06e03eb5c007c2e102#6-5-installing-onnx-simplifier**

**Comment by Laubeee** [comment]
Thanks, this is very interesting!
You say the 1st model is converted *from* onnx? Is this always the case, or only when there is an "original" onnx available, like in the human-pose-estimation-3d? If not, where does it come from in other cases (e.g. tf-pose-estimation mobilenet-thin)?
frankly, using onnx, I'd be interested in the reverse, optimizing a NCHW-onnx model that was converted from TF

**Comment by PINTO0309** [comment]
`only when there is an "original" onnx available, like in the human-pose-estimation-3d`

For the model without the original onnx, I just used tensorflow-onnx to convert the saved_model of TF without any deep thought.

Reverse conversion from TF to ONNX using my procedure is very inefficient. I received a request from a follower for onnx of all the models that had been committed in large numbers, so I spent about a week onnxing them very crudely. It's very hard because I'm maintaining all the models all by myself, and I just don't have enough time to spend onnx rigorous optimization. 😢

**Comment by Laubeee** [comment]
I see, I'm glad the onnx are now available, it helped me already quite a bit, so thank you for that!
I'm currently comparing different models and once I've chosen one or two for deeper investigation and comparison, I might be able to spend some time optimizing onnx (given one of the selected was converted from TF). If I do, I'll let you know any procedure I came up with :)
