### ISSUE TITLE
Yolact Edge to OpenVino pipeline request

### ISSUE THREAD

**Issue by ero1311** [PINTO0309/PINTO_model_zoo#74]
Hey, I am currently struggling with Yolact Edge to openvino conversion.
I swapped the yolact.py with the one in your repo. But I still fail to generate the onnx file. Can you please share your Yolact_Edge->ONNX->OpenVino pipeline?

**Comment by PINTO0309** [comment]
It is not a pipeline, but I have committed the conversion procedure and the model that converted COCO.
**https://github.com/PINTO0309/PINTO_model_zoo/tree/main/085_Yolact_Edge/20_mbnv2_550x550**

**Comment by PINTO0309** [comment]
Closed due to lack of progress.

**Comment by MiaoRain** [comment]
> Hey, I am currently struggling with Yolact Edge to openvino conversion.
> I swapped the yolact.py with the one in your repo. But I still fail to generate the onnx file. Can you please share your Yolact_Edge->ONNX->OpenVino pipeline?

Hi, have you solved the problem? Before getting openvino, we should convert yolact_edge to onnx first. However, I met the below problem, could you give me some suggestions. Thanks a lot.

**RuntimeError: Tried to trace <torch.yolact.FPN_phase_1 object at 0x5adda0d0> but it is not part of the active trace. Modules that are called during a trace must be registered as submodules of the thing being traced.**

Any suggestions would be appreciated.
