### ISSUE TITLE
Tfjs Modnet model gives strange result

### ISSUE THREAD

**Issue by mtuan4i** [PINTO0309/PINTO_model_zoo#75]
First, thank you very much for your great work.
I tried inference with tfjs Modnet model but the result is not as expected. My inference code is based on https://github.com/PINTO0309/PINTO_model_zoo/blob/main/078_MODNet/test_tflite.py
Here is what I got.
![image](https://user-images.githubusercontent.com/13715393/108604080-013bb400-73ef-11eb-8cc5-fcf607d9a9da.png)

This result is same as your result on tflite?

**Comment by PINTO0309** [comment]
I have re-committed the model. Please try again.
**https://drive.google.com/file/d/1Y6B6l72hib9t5ammT-7ya-muBzRKZ7xq/view?usp=sharing**
![Screenshot 2021-02-28 01:11:22](https://user-images.githubusercontent.com/33194443/109393106-4ddd3d00-7963-11eb-885f-b30e1ddd2995.png)

**Comment by mtuan4i** [comment]
It works now. Thank you for the new model and the conversion tool

**Comment by msurguy** [comment]
@mtuan4i could you provide a sample code of how to use this model in TFjs? I'm beginning learning about this and it would be great to see an example. Thanks!
