### ISSUE TITLE
EfficientPose conversion

### ISSUE THREAD

**Issue by Laubeee** [PINTO0309/PINTO_model_zoo#78]
There seems to be something wrong with the EfficientPose models (or at least EfficientPoseII, didnt test the others yet)
The output is very small and fuzzy, not at all like the expected keypoint heatmap. For comparison I converted the current [model](https://github.com/daniegr/EfficientPose/tree/master/models/tensorflow) myself with tf2onnx, and that one works as expected.

moreover, I wanted to compare the .pb from your repo with the original .pb, but wasn't able to load/run your version..

I see the repo also provides torch models, did you use those for conversion to ONNX? Or was it an older, buggy version? Either way, I think the efficientpose-folder might need an update :)

Windows10, x86_64
[example model EfficientPoseII](https://github.com/PINTO0309/PINTO_model_zoo/tree/main/084_EfficientPose/EfficientPoseII)
onnx 1.8.1, onnxruntime 1.5.2 with DirectML

If you want to test, following pre-processing should do the trick:
```python
sess = rt.InferenceSession("model_float32_opt.onnx")
input_name = sess.get_inputs()[0].name

# resize    (test_frame is the result of cv2 videocapture)
f = min(368 / test_frame.shape[0], 368 / test_frame.shape[1])
test_frame = cv2.resize(test_frame, (0, 0), fx=f, fy=f)

test_frame = test_frame.astype('float32') / 255  # scale to range 0..1
test_frame = test_frame[..., ::-1]  # assumes channels last! ->  x = x[::-1, ...]  # BGR->RGB

# pad
blob = np.zeros((368,368,3), dtype='float32')  # channels last
d1 = int((368-test_frame.shape[0])/2)
d2 = int((368-test_frame.shape[1])/2)
blob[d1:368-d1,d2:368-d2] = test_frame

mean=[0.485, 0.456, 0.406]
std=[0.229, 0.224, 0.225]
for i in range(3):
    blob[..., i] -= mean[i]
    blob[..., i] /= std[i]

out = sess.run(None, {input_name: [blob]})
```

**Comment by PINTO0309** [comment]
Thank you for pointing this out to me.
Two months ago I did not use an automatic conversion tool, I did the conversion work manually. So it is very likely that I made a mistake in the process of converting the model.

This time, I used the automatic conversion tool **`openvino2tensorflow`** to convert the data automatically. The .pb was a file downloaded from the [original repository](https://github.com/daniegr/EfficientPose/tree/master/models/tensorflow).

```
$ pip install openvino2tensorflow --upgrade

$ pb_to_saved_model \
--pb_file_path saved_model/EfficientPoseII.pb \
--inputs input_res1:0 \
--outputs upscaled_confs/BiasAdd:0

$ saved_model_to_tflite \
--saved_model_dir_path saved_model \
--model_output_dir_path saved_model \
--input_shapes [1,368,368,3] \
--output_no_quant_float32_tflite True \
--output_onnx True
```
![Screenshot 2021-03-01 21:37:08](https://user-images.githubusercontent.com/33194443/109498422-c7496c80-7ad6-11eb-82b3-066a85506652.png)

I will try to verify the results using the test code you provided when I have time. Once I have confirmation that it works correctly, I will update all the committed models. Just in case, I'll share the ONNX and tflite that I automatically converted using the tool.
[saved_model.tar.gz](https://github.com/PINTO0309/PINTO_model_zoo/files/6061629/saved_model.tar.gz)

Once again, thank you.

**Comment by PINTO0309** [comment]
Special procedure using inversion from tflite. **`tflite2tensorflow`** [GitHub](https://github.com/PINTO0309/tflite2tensorflow.git)
```
$ pip install tflite2tensorflow --upgrade

$ tflite2tensorflow \
  --model_path EfficientPoseII.tflite \
  --flatc_path ./flatc \
  --schema_path schema.fbs \
  --output_pb True

$ tflite2tensorflow \
  --model_path EfficientPoseII.tflite \
  --flatc_path ./flatc \
  --schema_path schema.fbs \
  --output_no_quant_float32_tflite True \
  --output_weight_quant_tflite True \
  --output_tfjs True \
  --output_coreml True \
  --output_tftrt True \
  --output_onnx True \
  --onnx_opset 13
```
![Screenshot 2021-03-01 22:29:52](https://user-images.githubusercontent.com/33194443/109503468-a9cbd100-7add-11eb-9720-767185146785.png)
**https://drive.google.com/file/d/1kIMvvRGfQ6mv4IzQ72Iv-1S57PzpxMn1/view?usp=sharing**

**Comment by Laubeee** [comment]
The onnx in the first folder gives me
```
INVALID_GRAPH : Load model from ../models/PINTO/084_EfficientPose/saved_model/model_float32.onnx failed:This is an invalid model. Error in Node:upscaled_deconv2/stack_Unsqueeze__1175 : Node (upscaled_deconv2/stack_Unsqueeze__1175) has input size 1 not in range [min=2, max=2].
```
The second looks better, but there seems to be still some differences compared to the original model

![1](https://user-images.githubusercontent.com/4159468/109507727-520e7500-7a9f-11eb-8baa-35a06808a732.png)
![2](https://user-images.githubusercontent.com/4159468/109507732-52a70b80-7a9f-11eb-822a-54d9f8b65e77.png)

I think this needs to be investigated a bit more detailed to see what exactly is going on, it seems to be a bit a special case model

**Comment by Laubeee** [comment]
wait, let me check again, it seems the order of outputs is differnt with the tflite-based model

**Comment by Laubeee** [comment]
So, just fyi:
pass3_detection2_confs/BiasAdd:0 and pass2_detection1_confs/BiasAdd:0 output look correct, e.g. detection2:
![download](https://user-images.githubusercontent.com/4159468/109509411-25f3f380-7aa1-11eb-8dc9-e52d017da875.png)

but the upscaled_confs/BiasAdd:0 is empty

**Comment by PINTO0309** [comment]
Hmmm. The tflite used as the source of the conversion is a float16, so the accuracy may be slightly worse than the weights extracted from a float32 model, but it is strange that the results are all empty.

I will need to investigate in detail the differences between the original model and the model I transformed in various patterns to identify bugs in the transformation.

Thank you for cooperating with me so many times.

**Comment by Laubeee** [comment]
no worries, thank you for your work!

**Comment by PINTO0309** [comment]
It turns out that the TransposeConv weights are not transcribing correctly. We will check other parts of the code later to see if there are any problems.
- original
![Screenshot 2021-03-01 23:30:44](https://user-images.githubusercontent.com/33194443/109511427-5ca02d00-7ae6-11eb-8734-46848b3192be.png)
- After conversion
![Screenshot 2021-03-01 23:32:58](https://user-images.githubusercontent.com/33194443/109511592-8a857180-7ae6-11eb-809d-5177b9c5ad5d.png)

**Comment by PINTO0309** [comment]
Thanks to you I was able to notice a bug in the tool and did the conversion again and found that the TransposeConv was converted correctly. Thanks!
**https://drive.google.com/file/d/1Lcgj-fLfiwLJ867nbAvrZRA952V9W7Zh/view?usp=sharing**
![Screenshot 2021-03-02 00:33:02](https://user-images.githubusercontent.com/33194443/109519760-e3590800-7aee-11eb-996c-262b3bc4b5e6.png)

**Comment by PINTO0309** [comment]
All models have been updated. The URL from which they are downloaded is the same as before the update, but the resources downloaded have been updated.
**https://github.com/PINTO0309/PINTO_model_zoo/tree/main/084_EfficientPose**

**Comment by Laubeee** [comment]
Thanks, the onnx look good!
A bit unexpectedly, they don't perform better on my (admittedly, integrated) GPU, they actually perform a bit worse sometimes. Moreover, even when using fp16, inference time is exactly the same... With other models I got better performance with GPU usage and especially fp16+GPU.
To compare I wanted to run the OpenVINO model, to see if the model itself is the problem, but I can't load it with `cv2.dnn.readNet`. Can you?

**Comment by PINTO0309** [comment]
It is probably different from the OpenCV backend you are using, but I will share my test results.
- EfficientPoseII - saved_model_openvino_myriad/openvino/FP16
```python
import cv2
import time

print('opencv version:', cv2.__version__)

xml = 'saved_model.xml'
bin = 'saved_model.bin'
image = cv2.imread('test.png')
blob = cv2.dnn.blobFromImage(image, 1, (368, 368), (104, 117, 123))

print("[INFO] DNN_BACKEND_INFERENCE_ENGINE loading model...")
net = cv2.dnn.readNetFromModelOptimizer(xml, bin)
net.setPreferableBackend(cv2.dnn.DNN_BACKEND_INFERENCE_ENGINE)
net.setPreferableTarget(cv2.dnn.DNN_BACKEND_INFERENCE_ENGINE)
net.setInput(blob)
start = time.time()
preds = net.forward()
end = time.time()
print("[INFO] DNN_BACKEND_INFERENCE_ENGINE inference took " + str((end - start) * 1000) + " ms")


print("[INFO] DNN_TARGET_OPENCL_FP16 loading model...")
net = cv2.dnn.readNetFromModelOptimizer(xml, bin)
net.setPreferableBackend(cv2.dnn.DNN_BACKEND_INFERENCE_ENGINE)
net.setPreferableTarget(cv2.dnn.DNN_TARGET_OPENCL_FP16)
net.setInput(blob)
start = time.time()
preds = net.forward()
end = time.time()
print("[INFO] DNN_TARGET_OPENCL_FP16 inference took " + str((end - start) * 1000) + " ms")


print("[INFO] DNN_TARGET_CPU loading model...")
net = cv2.dnn.readNetFromModelOptimizer(xml, bin)
net.setPreferableBackend(cv2.dnn.DNN_BACKEND_INFERENCE_ENGINE)
net.setPreferableTarget(cv2.dnn.DNN_TARGET_CPU)
net.setInput(blob)
start = time.time()
preds = net.forward()
end = time.time()
print("[INFO] DNN_TARGET_CPU inference took " + str((end - start) * 1000) + " ms")


print("[INFO] DNN_TARGET_MYRIAD loading model...")
net = cv2.dnn.readNetFromModelOptimizer(xml, bin)
net.setPreferableBackend(cv2.dnn.DNN_BACKEND_INFERENCE_ENGINE)
net.setPreferableTarget(cv2.dnn.DNN_TARGET_MYRIAD)
net.setInput(blob)
start = time.time()
preds = net.forward()
end = time.time()
print("[INFO] DNN_TARGET_MYRIAD inference took " + str((end - start) * 1000) + " ms")
```

```bash
$ python3 test.py 
opencv version: 4.5.1-openvino
[INFO] DNN_BACKEND_INFERENCE_ENGINE loading model...
[INFO] DNN_BACKEND_INFERENCE_ENGINE inference took 48395.20835876465 ms
[INFO] DNN_TARGET_OPENCL_FP16 loading model...
[INFO] DNN_TARGET_OPENCL_FP16 inference took 47927.51097679138 ms
[INFO] DNN_TARGET_CPU loading model...
[INFO] DNN_TARGET_CPU inference took 450.3624439239502 ms
[INFO] DNN_TARGET_MYRIAD loading model...
[INFO] DNN_TARGET_MYRIAD inference took 6135.213851928711 ms
```

**Comment by Laubeee** [comment]
hmm ok thanks, seems to be an issue with my setup, not the model then.
on my end python crashes upon trying to read the net, before even setting target/backend. I'll try a few more things to see if i can figure it out.
The original issue sure is solved, thanks :)

**Comment by Laubeee** [comment]
FYI: works after upgrading my openvino from 2020.4 to 2020.2 :) also GPU inference seems plausible now
