### ISSUE TITLE
Consolidation of BlazePose models

### ISSUE THREAD

**Issue by vpenades** [PINTO0309/PINTO_model_zoo#79]
#### WIndows10 , x64, TensorFlow v2.4.1

As you might know, Google updated it's BlazePose models for improved performance and detection quality.

The new models (detection, upper body and full body) have been published here:

https://google.github.io/mediapipe/solutions/models.html#pose

I've noticed that you've updated 053_BlazePose with new detection and upper body models, but 058_BlazePose_Full_Keypoints has not been updated yet.

I believe 058_BlazePose_Full_Keypoints was created originally from the model dump we found... but now that both the upper body and full body are officially published and hosted by Google, and given that the full body model depends on the detection model, I think it could be convenient to add the official, updated full body model to 053_BlazePose, and remove 058_BlazePose_Full_Keypoints to avoid confusion.

---

Another issue I've found with 053_BlazePose is this:

When I run download.sh a number of files are downloaded:

![imagen](https://user-images.githubusercontent.com/5433822/109655380-7fbcf200-7b63-11eb-9c9e-63f11e3e42a0.png)

If you notice, the .onnx files seems to be updated to January 16th, but the .pb and .tflite files seems to have a date of last year, so, have they been updated to the newest models?

**Comment by PINTO0309** [comment]
MediaPipe has undergone multiple model updates in a short period of time. Your points and observations are correct. I have not been able to keep up with the latest cross-section of models perfectly, as my priority has been to work on the requests posted on the issue bit by bit.

Now that I have my own conversion tool, it is much easier for me to respond to your suggestions than in the past. I will try to implement the work when I have enough time. :smiley:

**Comment by PINTO0309** [comment]
@vpenades
There was a bug in my conversion tool. The EdgeTPU model is not properly optimized. I will convert it again later and re-commit.

**Comment by vpenades** [comment]
Okey, I'll wait

Btw, we only use the float32 frozen .PB files; it's the only ones that run fast on x64

**Comment by PINTO0309** [comment]
@vpenades
Replaced the Google Drive model.
**https://github.com/PINTO0309/PINTO_model_zoo/tree/main/053_BlazePose**

**Comment by vpenades** [comment]
Thanks!

Btw, I undertand the frozen model best optimized for x86 is this:

    saved_model_tflite_tfjs_coreml_onnx/model_float32.pb

Is that right?

**Comment by PINTO0309** [comment]
Yes. That's right.
If you plan to do CPU inference, OpenVINO is recommended because it runs many times faster than TensorFlow.

**Comment by vpenades** [comment]
We would like to use OpenVINO, but our codebase is mostly C#, as far as I know, OpenVINO doesn't have bindings for C# yet, but as soon as there's some, we will give it a try

Thanks again!
