### ISSUE TITLE
Model conversion error

### ISSUE THREAD

**Issue by metanav** [PINTO0309/PINTO_model_zoo#8]
After running download.sh,  I am trying to convert  face_detection_front.pb to quantized tflite model. I have tried all scripts inside 30_BlazeFace/01_float32 directory but all gets failed with the following error:

`ValueError: This converter can only convert a single ConcreteFunction. Converting multiple functions is under development.`

I am using TensorFlow 2.2.0 on MacOS. Also, tried with a Linux machine with 2.1.0 and 2.2.0.

NOTE: I am trying to rebuild quantized model to run on microcontroller. The quantized model for the blazeface provided in your repo download.sh has error while running on the microcontroller: "Didn't find op for builtin opcode 'CONV_2D' version '3'" or "Didn't find op for builtin opcode 'QUANTIZE' version '2'".

**Comment by PINTO0309** [comment]
Please try using Tensorflow v1.15.2.
https://github.com/PINTO0309/PINTO_model_zoo/blob/a86a7bb18ced20e841cc86f6362ec3a04baf9c2c/30_BlazeFace/01_float32/01_blazeface_tflite_to_pb.py#L1

**Comment by metanav** [comment]
Thanks! It works but I still get  "Didn't find op for builtin opcode 'QUANTIZE' version '2'". while allocating tensors on the microcontroller. May be some ops are missing.

**Comment by PINTO0309** [comment]
I think it's just that the OP on the TF Lite micro side doesn't support it. There is nothing wrong with the conversion script itself.
https://github.com/tensorflow/tensorflow/blob/3ebdec47df6c1afaa31ea6f0aa980f0f90729e87/tensorflow/lite/micro/kernels/quantize.cc#L156-L169
```cpp
// This Op (QUANTIZE) quantizes the input and produces quantized output.
// AffineQuantize takes scale and zero point and quantizes the float value to
// quantized output, in int8 or uint8 format.
TfLiteRegistration* Register_QUANTIZE() {
  static TfLiteRegistration r = {/*init=*/quantize::Init,
                                 /*free=*/nullptr,
                                 /*prepare=*/quantize::Prepare,
                                 /*invoke=*/quantize::Eval,
                                 /*profiling_string=*/nullptr,
                                 /*builtin_code=*/0,
                                 /*custom_name=*/nullptr,
                                 /*version=*/0};
  return &r;
}
```

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/PINTO_model_zoo/blob/f5926277170a4c59a802c0cf9cd2cafa573d9fdc/30_BlazeFace/01_float32/03_integer_quantization.py#L1

**Comment by metanav** [comment]
Yes I used TF 2.2.0 for the conversion.  But the models generated by  03_interger_quantization.py or 04_full_integer_quantization.py have same error.

**Comment by metanav** [comment]
Also I am using TF Lite Micro library generated by TF 2.2.0 branch. May be it is TF Lite Micro issue.

**Comment by PINTO0309** [comment]
I empathize with you.

**Comment by metanav** [comment]
Thanks for your understanding. I am struggling with this issue for 3 days.

**Comment by PINTO0309** [comment]
Same issue. **[tensorflow/tensorflow - Didn't find op for builtin opcode 'QUANTIZE' version '2' #38488](https://github.com/tensorflow/tensorflow/issues/38488)**

**Comment by metanav** [comment]
Yes, I have seen that before. But I just have seen TF Lite Micro has pushed new changes 1 hour ago: https://github.com/tensorflow/tensorflow/commit/3ebdec47df6c1afaa31ea6f0aa980f0f90729e87

I will try with latest. changes to see if the issue is resolved.

**Comment by PINTO0309** [comment]
It's very interesting!!

**Comment by metanav** [comment]
With the latest changes, error has gone! Thanks for your help, I appreciate it. But now I am facing another issue which is related to the size of the model. The full integer quantized model needs a little over 500KB  RAM (tensor allocation, weight/activation) but the microcontroller has only 512 KB RAM. Is there any way to decrease the size (Blazeface) further?

**Comment by PINTO0309** [comment]
It is a very difficult problem. The following is a model pruning project, but it is still under development, and I could only find a sample of Keras. I haven't tried it yet, so I'm not sure if it's helpful yet.
**https://github.com/tensorflow/model-optimization.git**
**https://blog.tensorflow.org/2019/05/tf-model-optimization-toolkit-pruning-API.html**

**Comment by metanav** [comment]
Thanks for the clue. i guess I need to load "pb" saved model into TF keras.

**Comment by PINTO0309** [comment]
For example, there are model conversion tools like this one.
**https://github.com/microsoft/MMdnn.git**

**Comment by metanav** [comment]
I am trying to use model-optimization. I was able to load the model into Keras but can't see the model summary.

```
>>> import tensorflow as tf
>>> from tensorflow import keras
>>> print(tf.version.VERSION)
2.2.0
>>> model = tf.keras.models.load_model('saved_model')
>>> model
<tensorflow.python.training.tracking.tracking.AutoTrackable object at 0x101726890>
>>> model.summary()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'AutoTrackable' object has no attribute 'summary'
```

**Comment by PINTO0309** [comment]
I suffer from the same phenomenon. It may be that I used tf.compat.v1.saved_model.simple_save when I first exported the model to the saved_model format. I may need to review the initial steps to generate saved_model using v2.x, but I don't see the answer right now.

**Comment by metanav** [comment]
Yes, it would be good if we can reduce the model size further for TFlite micro.

**Comment by metanav** [comment]
The quantized model is only around 50% of the 32-bit float model. Ideally it should be reduced by 70-75%. 
face_detection_front.tflite:  413K
face_detection_front_128_full_integer_quant.tflite: 197K 

If we can achieve at least 70% reduction, it would be really great. I am wondering if it is related to TF1 to TF2 conversion?

**Comment by PINTO0309** [comment]
>Ideally, it should be reduced by 70-75%.

It may be difficult to reduce the size to this level. Even if you have pruned the branches. The model I have generated is as follows.

1. face_detection_front_128_weight_quant.tflite 163.8KB **[download here](https://drive.google.com/file/d/1dDepYmZk-WB6eDf1AuYoVmG5Wv8TRDj0/view?usp=sharing)**
2. face_detection_front_128_integer_quant.tflite 201.6KB **[download here](https://drive.google.com/file/d/11bSWk65mBoZxQh8mzUygKvc5RYc6DbZW/view?usp=sharing)**

What do you mean by the 70% reduction that you say is below?
1. face_detection_front_128_weight_quant.tflite 49.14KB (70% reduced)
2. face_detection_front_128_integer_quant.tflite 60.48KB (70% reduced)

>I am wondering if it is related to TF1 to TF2 conversion?

My script that generates saved_model uses the v1 API. However, the saved_model generated by the v1 API seems to lack some information about Keras due to backward compatibility. If I could replace my .tflite to saved_model conversion script with a v2 base, I might be able to avoid the no attribute error.

**Comment by metanav** [comment]
I mean 70% of the default 32-bit float model.
Currently: 413K --> 197K
ideally:      413K --> 124K

Please see here for the reference: 
 https://www.tensorflow.org/lite/performance/model_optimization#quantization

**Comment by PINTO0309** [comment]
I understand. In a normal model, it is reduced to a quarter of the size after quantization. However, the original size of the BlazeFace is too small, so the size reduction effect after quantization seems to be small.

**Comment by metanav** [comment]
The size of  the mediapipe/blazeface model  is 224 KB which is available here: https://github.com/google/mediapipe/blob/master/mediapipe/models/face_detection_front.tflite.
I believe this model is FP16. So it is around 1/2 of the FP32. How come integer quantized can't be reduced further? My assumption may be not correct but  Int8 quantization should reduce the size further. From where did you get the TFLite 32FP model?

**Comment by metanav** [comment]
Also, there is an example here which shows a very simple model conversion,
https://www.tensorflow.org/lite/performance/post_training_integer_quant
83424. -->  23368

**Comment by PINTO0309** [comment]
The .tflite in the link you presented to me is the Float16 model. It's about the same size as the Float16 model I produced on hand.

>From where did you get the TFLite FP32 model? I could not find it at the mediapipe GitHub repo.

The model on MediaPipe's official site was updated from Float32 to Float16 10 days ago.  The Float32 model I downloaded 15 days ago is the one I downloaded. 

>Also, there is an example here which shows a very simple model conversion,

I'm not sure about the internal behavior of the TensorflowLite Converter as I'm performing the same procedure to quantize it.

**Comment by metanav** [comment]
As per documentation pruning may not reduce the RAM requirement of the model, it will only reduce the model disk size (compression). It would be interesting to see if the size can be reduced further after you will  change your script to TF v2. Thanks for your time!

**Comment by PINTO0309** [comment]
*memorandum of understanding**
https://github.com/minus31/BlazeFace

It may be possible to perform the training from the beginning with pruning enabled in Keras.

**Comment by metanav** [comment]
I am also thinking to train it from scratch. Is training data available somewhere? Or, schema of the training data so that I can prepare my own.

**Comment by PINTO0309** [comment]
The six key points (eyes, nose, ears, and mouth) do not seem to be detectable, but a training script with FDDB dataset is available. I'm exhausted from my day job, so I'll try it tomorrow.
**https://github.com/vietanhdev/blazeface_keras**

**Comment by PINTO0309** [comment]
I have started training for BlazeFace by Keras. I'm going to try pruning after the 160 epoch is done.
![Screenshot 2020-06-03 23:55:29](https://user-images.githubusercontent.com/33194443/83653337-9d6e2280-a5f6-11ea-85bf-785117e348b6.png)

**Comment by metanav** [comment]
Great! It would be interesting to see the final model size.

**Comment by metanav** [comment]
That's sad. But I think pruning won't help in the RAM usage, it would only make the model size smaller for storage.
