### ISSUE TITLE
Background matting using in the browser using BackgroundMattingV2?

### ISSUE THREAD

**Issue by benbro** [PINTO0309/PINTO_model_zoo#82]
The [BackgroundMattingV2](https://github.com/PeterL1n/BackgroundMattingV2) project can remove the background if you have a separate image of the background without the subject.
The models are [here](https://drive.google.com/drive/folders/1cbetlrKREitIgjnIikG1HdM4x72FtgBh).
Is it possible to do it in the browser?

**Comment by PINTO0309** [comment]
If you are referring to TensorFlow.js, it was currently impossible to transform the model by any means. The layer used for the model is too special.

onnx-tf -> [Error] No schema registered for 'Celu'
openvino -> [Error] There is no registered "infer" function for node "If_433" with op = "If"

**Comment by benbro** [comment]
Maybe [BackgroundMattingV2-TensorFlow](https://github.com/PeterL1n/BackgroundMattingV2-TensorFlow) can help.

It will be great if we could use 082_MediaPipe_Meet_Segmentation but I can't find the original model card pdf with the Apache license.

Is it possible to use [MODNet](https://github.com/ZHKKKe/MODNet) or [078_MODNet](https://github.com/PINTO0309/PINTO_model_zoo/tree/main/078_MODNet) in a web browser?

**Comment by PINTO0309** [comment]
>Maybe BackgroundMattingV2-TensorFlow can help.

I'll try tomorrow.

>Is it possible to use MODNet or 078_MODNet in a web browser?

Yes.
https://github.com/w-okada/image-analyze-workers

**Comment by benbro** [comment]
> > Maybe BackgroundMattingV2-TensorFlow can help.
> 
> I'll try tomorrow.
> 
> > Is it possible to use MODNet or 078_MODNet in a web browser?
> 
> Yes.
> https://github.com/w-okada/image-analyze-workers

I think MODNet demo is missing from this [README](https://github.com/w-okada/image-analyze-workers/blob/master/README.md).
Demo [README](https://github.com/w-okada/image-analyze-workers/blob/master/010demo_modnet-worker-js-demo/README.md) says "WIP: WebGL can not work."
Does it means that performance will be bad?

**Comment by PINTO0309** [comment]
>Maybe BackgroundMattingV2-TensorFlow can help.

In the process of converting it to a browser model, I temporarily converted it to the tflite format, but there are so many special operations that converting it to a browser model looks impossible. This model is very difficult to handle and is not recommended. I don't think it will be fast enough.

<details><summary><b>tflite converted model structure</b></summary><div>

![model_float32 tflite (1)](https://user-images.githubusercontent.com/33194443/111058893-eda6d900-84d4-11eb-9d1e-014d0f8209f0.png)

</div></details>

>Does it means that performance will be bad?

He is diverting the model I generated, but there was a problem when I generated the model a few months ago.

**Comment by benbro** [comment]
Thanks.

Which one perform better in the browser, 082_MediaPipe_Meet_Segmentation or MODNet?

**Comment by PINTO0309** [comment]
>Which one perform better in the browser, 082_MediaPipe_Meet_Segmentation or MODNet?

082_MediaPipe_Meet_Segmentation >>>>>> MODNet

**Comment by benbro** [comment]
Do you have the PDF of the original card model with Apache license?

**Comment by PINTO0309** [comment]
I don't download them and keep them on hand.

**Comment by benbro** [comment]
Thanks
