### ISSUE TITLE
HiFill CoreML ?

### ISSUE THREAD

**Issue by bkrkc** [PINTO0309/PINTO_model_zoo#86]
Hello
I need a coreml for hifill. can you help me ?

**Comment by PINTO0309** [comment]
Unfortunately, the model uses too many special layers to be supported by CoreML. **`ExtractImagePatches`**

**Comment by VenanEmre** [comment]
Do you have a solution for iOS?
@PINTO0309

**Comment by PINTO0309** [comment]
No, it's not.

**Comment by VenanEmre** [comment]
thanks for your help
