### ISSUE TITLE
 yolact_edge & onnx issues

### ISSUE THREAD

**Issue by MiaoRain** [PINTO0309/PINTO_model_zoo#88]
#yolact_edge

Hi, thanks for your work. Before getting openvino, we should convert yolact_edge to onnx first. However, I met the below problem, could you give me some suggestions. Thanks a lot.

**RuntimeError: Tried to trace <torch.yolact.FPN_phase_1 object at 0x5adda0d0> but it is not part of the active trace. Modules that are called during a trace must be registered as submodules of the thing being traced.**

Any suggestions would be appreciated.

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/085_Yolact_Edge/30_Full_Converted_mbnv2_550x550
