### ISSUE TITLE
MediaPipe holistic model

### ISSUE THREAD

**Issue by vpenades** [PINTO0309/PINTO_model_zoo#89]
#### 1. OS you are using e.g. Ubuntu 20.04, WIndows10, etc
Windows10
#### 2. OS Architecture e.g. x86_64, armv7l, aarch64, etc
x64
#### 4. Version of TensorFlow e.g. v2.4.1, tf-nightly==2.5.0.dev20210128, etc
2.4.1
#### 9. URL of the repository from which the transformed model was taken
https://google.github.io/mediapipe/solutions/holistic.html
#### 11. Issue Details

Google recently introduced the "holistic" model into the MediaPipe family:  this model works together with the already existing BlazePose, HandsLandmarks and FaceMesh to produce an unified set of landmarks.

Could you take a look at it?

Thanks!

**Comment by PINTO0309** [comment]
The model linked in the URL you showed me has been committed long time ago.

- hand-recrop
https://github.com/PINTO0309/PINTO_model_zoo#5-2d3d-hand-detection

**Comment by vpenades** [comment]
Ahhh, okey, since it had a different name I missed it.

Thanks!

**Comment by vpenades** [comment]
Sorry to bother again... reading further, the google documentation seems to suggest there's two separate models: one for hand-recrop, and another for face-recrop.

I'm already looking into the hand-recrop model, do you have the face-recrop model somewhere under a different name?

Thanks!

**Comment by PINTO0309** [comment]
I could not find a model named face_recrop.
https://github.com/google/mediapipe/search?q=face_recrop&type=
