### ISSUE TITLE
Trying to understand output of 25 head pose estimator

### ISSUE THREAD

**Issue by vpenades** [PINTO0309/PINTO_model_zoo#9]
Hi again!

I am trying to use 25 head pose estimator; I'be been able to load and run the frozen_inference_graph.pb model, but I don't know how to decode the tensor output.

The model has an image input of 128x128 pixels....  and outputs an array of 136 float values.

The python code seems to imply there's several output tensors: scores, boxes, etc.... but I only see this 136 float output tensor.

So, how do I decode it?

As a side note: I am looking for a fast way of detecting faces on an image, at distances of up to 5 metres, so BlazeFace is not suitable for me. I don't need landmarks or any other kind of information, just face rectangles on an image.... given you have a collection of face detection models, which one do you think is the best for that task?

Thanks in advance!

**Comment by PINTO0309** [comment]
Have you tried the following? A working test code has already been committed.
1. **https://github.com/PINTO0309/PINTO_model_zoo/tree/master/25_head_pose_estimation/03_integer_quantization/head_pose_estimation.py**

2. **https://github.com/PINTO0309/PINTO_model_zoo#sample3---head-pose-estimation-multi-stage-inference-with-multi-model**

**Comment by vpenades** [comment]
Okey, I can see now that I was trying to use the Pose_Estimator in place of the Face_Detector.

Now, I tried to use the face detection models on Emgu.TF (C#) and I am having these problems:

If I load `ssdlite_mobilenet_v2_face_300_integer_quant_with_postprocess.tflite` on `Emgu.TF.Lite` it seems it points to the incorrect input tensor. Instead of pointing to `normalized_input_image_tensor`, it points to `BoxPredictor_4/BoxEncodingPredictor/weights` which is not good to use...

Then, I tried to use the PB model at `25_head_pose_estimation\01_float32\01_face_detector`, but when I try to load it, it gives me this error:

> Op type not registered 'TFLite_Detection_PostProcess' in binary running on DESKTOP-XXXXXXXX. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) 

Also, keep in mind my knowledge of Python is very limited, I'm trying to use some of your models using C#.

**Comment by PINTO0309** [comment]
**TFLite_Detection_PostProcess** is a custom OP for Tensorflow Lite. Cannot run on Pure Tensorflow.  If you don't need a custom OP, use the Object Detection API to train and just generate a .pb file without specifying "--add_postprocessing_op=True".

**https://github.com/tensorflow/models/tree/master/research/object_detection**

```
$ python3 object_detection/export_tflite_ssd_graph.py \
    --pipeline_config_path=pipeline.config \
    --trained_checkpoint_prefix=model.ckpt-44548 \
    --output_directory=export #\
#    --add_postprocessing_op=True
```

**https://qiita.com/PINTO/items/865250ee23a15339d556#4-2-7-1-generating-a-pb-file-with-post-processi**

**Comment by PINTO0309** [comment]
Closed due to lack of progress.
