### ISSUE TITLE
Output issue after training

### ISSUE THREAD

**Issue by MShchoholiev** [PINTO0309/PINTO_model_zoo#93]
Hello! I saw your great TF realization. I would be thankful for your help. Now, I'm realizing a similar task for the BlazePose model in TF2. I use another architecture of the model, but it's the same as yours. I'm using this model with pre-trained weights by this graph. And I train this model on our specific dataset, after augmentation we have more 30 000 images.
But, one problem appears during this process: as an output, we have a set of points (coordinates), which is the same for any input, so all coordinates are constant. Perhaps, you have some ideas or direction of thinking for this?
I would be very grateful for your help!

**Comment by MShchoholiev** [comment]
Hello! I saw your great TF realization. I would be thankful for your help. Now, I'm realizing a similar task for the BlazePose model in TF2. I use another architecture of the model, but it's the same as yours. I'm using this model with pre-trained weights by this graph. And I train this model on our specific dataset, after augmentation we have more 30 000 images.
But, one problem appears during this process: as an output, we have a set of points (coordinates), which is the same for any input, so all coordinates are constant. Perhaps, you have some ideas or direction of thinking for this?
I would be very grateful for your help!

**Comment by PINTO0309** [comment]
I have no idea.
