### ISSUE TITLE
MobileStyleGAN

### ISSUE THREAD

**Issue by DonkeySmall** [PINTO0309/PINTO_model_zoo#94]
Hello, how to use [MobileStyleGAN](https://github.com/PINTO0309/PINTO_model_zoo/tree/main/105_MobileStyleGAN), what should be in the input?

**Comment by PINTO0309** [comment]
It can be found here.
https://github.com/bes-dev/MobileStyleGAN.pytorch/blob/75fe0069d52c498b0766a8b1a02e029a8537c471/demo.py#L18-L24

**Comment by DonkeySmall** [comment]
Strange model inputs and outputs, don't no what to do with this

![Untitled](https://user-images.githubusercontent.com/66531939/115890881-1d46ea80-a45e-11eb-9562-79e58f85674f.jpg)
