### ISSUE TITLE
Yolov5 edgetpu inference RuntimeError

### ISSUE THREAD

**Issue by BernardinD** [PINTO0309/PINTO_model_zoo#98]
#### 10. URL or source code for simple inference testing code
```python
import cv2
import numpy as np
import tflite_runtime.interpreter as tflite

if __name__ == '__main__':
	interpreter = make_interpreter(model)
	interpreter.allocate_tensors()
	input_details = interpreter.get_input_details()
	output_details = interpreter.get_output_details()
	input_shape = input_details[0]["shape"]

	cap = cv2.VideoCapture(video)
	fw = int(cap.get(3))
	fh = int(cap.get(4))

	while cap.isOpened():
		ret, frame = cap.read()
		if not ret:
			break
		
		img = np.zeros((img_size_h, img_size_w))
		input_img = np.array(np.expand_dims(img, 0), dtype=np.uint8)
		interpreter.set_tensor(input_details[0]['index'], input_img)
		interpreter.invoke()
			
```
#### 11. Issue Details:
When trying to run  your edgetpu model as well as other Yolov5 models we've converted we get the error:
`RuntimeError: Internal: :213 batches * single_output_size != output->bytes (6630 != 172380)Node number 14 (EdgeTpuDelegateForCustomOp) failed to prepare.`

Can you explain how you were able to get your model to run? Thanks in advance

**Comment by PINTO0309** [comment]
This is a problem with the EdgeTPU runtime, please submit an issue to the edgetpu repository. It seems that models containing 5D tensors are not supported. I have submitted this issue to the edgetpu repository, but it has been ignored for a long time. 
https://github.com/google-coral/edgetpu
