### ISSUE TITLE
Meet Segmentation Model on Myriad X

### ISSUE THREAD

**Issue by thepycoder** [PINTO0309/PINTO_model_zoo#99]
# Info
OS: Manjaro Linux x86_64 
Kernel: 5.4.116-1-MANJARO
Architecture: x86_64
OpenVINO version: 2021.1.110

Model url:
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/082_MediaPipe_Meet_Segmentation

# Testing code:
tflite: https://github.com/PINTO0309/PINTO_model_zoo/blob/main/082_MediaPipe_Meet_Segmentation/test.py
openvino code:
```python
from openvino.inference_engine import IECore, Blob, TensorDesc
import numpy as np
import cv2

XML_PATH = "/project/082_MediaPipe_Meet_Segmentation/openvino/FP16/144x256/saved_model.xml"
BIN_PATH = "/project/082_MediaPipe_Meet_Segmentation/openvino/FP16/144x256/saved_model.bin"

ie_core_handler = IECore()
network = ie_core_handler.read_network(model=XML_PATH, weights=BIN_PATH)

executable_network = ie_core_handler.load_network(network, device_name='CPU', num_requests=1)

inference_request = executable_network.requests[0]

# random_input_data = np.random.randn(1, 3, 144, 256).astype(np.float32)
random_input_data = cv2.resize(cv2.imread('/project/test.jpeg'), (144, 256)).astype(np.float32)
tensor_description = TensorDesc(precision="FP32", dims=(1, 3, 144, 256), layout='NCHW')
input_blob = Blob(tensor_description, random_input_data)

input_blobs = inference_request.input_blobs
print(input_blobs)
input_blob_name = next(iter(input_blobs))
inference_request.set_blob(blob_name=input_blob_name, blob=input_blob)

inference_request.infer()

output_blob_name = next(iter(inference_request.output_blobs))
output = inference_request.output_blobs[output_blob_name].buffer

print(output.shape)

out1 = (output[0][0, :, :] > 0.5) * 255
out2 = (output[0][1, :, :] > 0.5) * 255

print((out1 / 255).sum())

cv2.imwrite('/project/out/openvino_mask_1.bmp', out1)
cv2.imwrite('/project/out/openvino_mask_2.bmp', out2)

test = np.load(open('/project/frame_detection_openvino.npy', 'rb'))
print(test)
```

for your testing convenience, I ran this in Intel's own docker container using the following command:
```bash
docker run --rm -it -v `pwd`:/project openvino/ubuntu18_runtime:2021.1 bash
```
My working directory is:
- openvino_test.py (code above)
- 082_MediaPipe_Meet_Segmentation

The command will mount this folder `pwd` to `/project` in the container and go from there. It uses the downloaded openvino model from within `082_MediaPipe_Meet_Segmentation`

# Issue Details

Thank you so much for this awesome model zoo and all the work you do, really appreciate it!

The output of the openvino model version of the mediapipe meet model is very bad, not in terms of accuracy, but in terms of it not being usable output at all.

When running your tflite test script, the output looks good and I get an array back from tflite with dimensions `(1, 144, 256, 2)` and after thresholding the output looks exactly like expected, awesome!

But then, openvino. When using netron to look at the xml model it already says the output will be `(1, 2, 144, 256)` which is already different. If I then take a look at the output, all numbers in the [0, 0, :, :] slice are positive and all numbers in the [0, 0, :, :]
 slice are negative, leading to a black and white mask output.

Did something go wrong in conversion? I'm willing to help out here, but don't have in depth experience with openvino conversion. If you need any extra info, I'll share it :)

Thanks!

**Comment by thepycoder** [comment]
Thanks to your testing code, I was able to also confirm that the `.pb` file works as intended. So somewhere in the conversion tensorflow -> openVino is where it goes wrong.

**Comment by PINTO0309** [comment]
```python
try:
    from tflite_runtime.interpreter import Interpreter
except:
    from tensorflow.lite.python.interpreter import Interpreter
from openvino.inference_engine import IECore, Blob, TensorDesc
import numpy as np
import cv2

fw = 'openvino' #openvino or tflite
segmentation_drawing_mode = 'grayscale' # grayscale or binarization
bin_threshold = 111
img = cv2.imread('test.jpg')


def get_segmap(img):
    segmap = None
    color_bytes = 1
    color_bits = 8 * color_bytes
    retrun_color_type = f'uint{color_bits}'

    segm_min = img.min()
    segm_max = img.max()
    max_val = (2 ** color_bits) - 1
    if (segm_max - segm_min) > np.finfo("float").eps:
        img = max_val * (img - segm_min) / (segm_max - segm_min)
    else:
        pass
    if segmentation_drawing_mode == 'binarization':
        img[img < bin_threshold]  = 0
        img[img >= bin_threshold] = 255
    elif segmentation_drawing_mode == 'grayscale':
        pass
    segmap = img
    return segmap


if fw == 'openvino':
    XML_PATH = "saved_model/openvino/FP32/saved_model.xml"
    BIN_PATH = "saved_model/openvino/FP32/saved_model.bin"

    ie = IECore()
    net = ie.read_network(model=XML_PATH, weights=BIN_PATH)
    input_blob = next(iter(net.input_info))
    exec_net = ie.load_network(net, device_name='CPU', num_requests=1)
    inference_request = exec_net.requests[0]

    h = img.shape[0]
    w = img.shape[1]

    img = cv2.resize(img, (256, 144))
    img = np.asarray(img)
    img = img / 255.
    img = img.astype(np.float32)
    img = img[np.newaxis,:,:,:]
    img = img.transpose((0,3,1,2))

    exec_net.infer(inputs={input_blob: img})

    output_blob_name = next(iter(inference_request.output_blobs))
    output = inference_request.output_blobs[output_blob_name].buffer

    img1 = output[0][0, :, :]
    img2 = output[0][1, :, :]

    segm_map1 = get_segmap(img1)
    segm_map2 = get_segmap(img2)
    segm_map1 = cv2.resize(np.uint8(segm_map1), (w, h))
    segm_map2 = cv2.resize(np.uint8(segm_map2), (w, h))

    cv2.imwrite('out1_openvino.jpg', segm_map1)
    cv2.imwrite('out2_openvino.jpg', segm_map2)


elif fw == 'tflite':
    h = img.shape[0]
    w = img.shape[1]

    img = cv2.resize(img, (256, 144))
    img = np.asarray(img)
    img = img / 255.
    img = img.astype(np.float32)
    img = img[np.newaxis,:,:,:]

    interpreter = Interpreter(model_path='model_float32.tflite', num_threads=4)
    interpreter.allocate_tensors()
    input_details = interpreter.get_input_details()[0]['index']
    output_details = interpreter.get_output_details()[0]['index']

    interpreter.set_tensor(input_details, img)
    interpreter.invoke()
    output = interpreter.get_tensor(output_details)

    img1 = output[0][:, :, 0]
    img2 = output[0][:, :, 1]

    segm_map1 = get_segmap(img1)
    segm_map2 = get_segmap(img2)
    segm_map1 = cv2.resize(np.uint8(segm_map1), (w, h))
    segm_map2 = cv2.resize(np.uint8(segm_map2), (w, h))

    cv2.imwrite('out1_tflite.jpg', segm_map1)
    cv2.imwrite('out2_tflite.jpg', segm_map2)
```
- out1_openvino_grayscale.jpg
![out1_openvino_grayscale](https://user-images.githubusercontent.com/33194443/118463006-3f204e00-b73a-11eb-9e9f-d3db98884392.jpg)
- out2_openvino_grayscale.jpg
![out2_openvino_grayscale](https://user-images.githubusercontent.com/33194443/118463066-4d6e6a00-b73a-11eb-911b-1efbddf327b4.jpg)
- out1_openvino_binary.jpg
![out1_openvino_binary](https://user-images.githubusercontent.com/33194443/118463209-7d1d7200-b73a-11eb-9ffd-d87147c0f6d8.jpg)
- out2_openvino_binary.jpg
![out2_openvino_binary](https://user-images.githubusercontent.com/33194443/118463241-84448000-b73a-11eb-94ed-3e9ad573449d.jpg)
- original
![test](https://user-images.githubusercontent.com/33194443/118463388-a9d18980-b73a-11eb-99f0-6be38fcf08aa.jpg)

**Comment by thepycoder** [comment]
Confirmed working, thank you for the example @PINTO0309. Really appreciate it!
